### ISSUE TITLE
best way to process a large hindi wordlist for hunspell

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#10]
I want to create an affix file and dictionary from a large hindi wordlist. I see a number of tools - munch, wordlist2hunspell, affixcompress, docubleaffixcompress, makealias etc.

Which is the recommended tool for handling a a large word list in utf8 in a complex script like devanagri which is used for hindi language?

BTW, munch does not seem to handle utf8 for devanagari and create an aff file.

Thanks.

Original comment by: shreeshrii

Original Ticket: [hunspell/bugs/253](https://sourceforge.net/p/hunspell/bugs/253)

**Comment by dimztimz** [comment]
We probably can close this as it is related to dictionary development. Anything related to the Hindi dictionary should be reported to the [according repository](https://github.com/Shreeshrii/hindi-hunspell).

Regarding munch and munch we can too close this as newer tools should be created with unicode support and everything else.
