### ISSUE TITLE
In lowriter in Italian, "possiede" is said to be spelt wrong

### ISSUE THREAD

**Issue by martinwguy** [hunspell/hunspell#1000]
Version: hunspell-it 1:7.5.0-1 used by lowriter 7.4.7.2 (Debian bookworm i386)
Document: possiede
[F7] and it pops up a window saying "Not in dictionary / possiede / Suggestions: posseder"

Well. I'm bilingual en-it since 30 years and possedere declines irregularly following sedere

It doesn't recognise any of

possiedo possiedi  possiede possediamo possedete possedono
 
I get the same wrong flags of misspelled word in Firefox how a I am typing: the words in the above line are have a pink squiggly underline.

Thanks & keep up the good work!

   M

**Comment by fin-w** [comment]
This Hunspell repository doesn't manage dictionary data, it only uses data that other people provide, so you should contact the dictionary maintainer(s) directly to point out the omission.

Perhaps you are using this dictionary in Firefox?
https://addons.mozilla.org/en-GB/firefox/addon/dizionario-italiano/
https://github.com/flodolo/dizionario-it

And according to the changelog in the `hunspell-it` Debian package, these people are maintaining the Italian dictionary for Debian:
https://www.libreitalia.org

If you contact those people, hopefully they can add the words to the dictionary!

**Comment by martinwguy** [comment]
Thanks. No, none of the addon but thanks for those. I've emailed the libreitalia dictionary maintainer.
