### ISSUE TITLE
unmunch do not work correctly with "long" FLAG

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#130]
1\) create the a.aff file:

\----8&lt;--------8&lt;--------8&lt;--a.aff--8&lt;--------8&lt;--------8&lt;----
NAME Dizionario italiano
LANG it\_IT
HOME http://linguistico.sourceforge.net
SET UTF-8
FLAG LONG
TRY aioertnsclmdpgubzfvh`q'ACMSkBGPLxEyRTVrIODNwFiyhljUZKHWJYQXY@RHLI

SFX A1 Y 1
SFX A1 a bb a

SFX A2 Y 1
SFX A2 a cc a
\----8&lt;--------8&lt;--------8&lt;--------8&lt;--------8&lt;--------8&lt;----

2\) create the a.dic file:

\----8&lt;--------8&lt;--------8&lt;--a.dic--8&lt;--------8&lt;--------8&lt;----
1
aa/A1
\----8&lt;--------8&lt;--------8&lt;--------8&lt;--------8&lt;--------8&lt;----

3\) execute the following command:
$ unmunch a.dic a.aff
\[...\]
aa
abb
acc

Note that the results is for a dictionary with: aa/A1A2
You have the same result with a dictionary with: aa/A9

$ hunspell -d a -m
aa
aa  st:aa

abb
abb  st:aa fl:A1

acc
acc

So hunspell work correctly.

I'm using hunspell under Debian Squeeze:

$ hunspell --version
@\(\#\) International Ispell Version 3.2.06 \(but really Hunspell 1.2.8\)

$ dpkg -l hunspell | grep hunspell
ii  hunspell                              1.2.8-6                      spell checker and morphological analyzer \(program\)

Ciao
Davide

Original comment by: davideprina

Original Ticket: [hunspell/bugs/139](https://sourceforge.net/p/hunspell/bugs/139)

**Comment by dimztimz** [comment]
Similar to #342 . Unmunch seems to be very limited. Maybe a completely new tool should be created for the same needs.
