### ISSUE TITLE
Twofold suffixing and unmunch

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#143]
It seems unmunch partially ignores twofold suffixes - when unmunching, I get a list like:
original\_word
original\_word\_with\_1st\_level\_sfx/esond\_aff

not the full list including unmunched words regarding second rule.

Original comment by: jancs

Original Ticket: [hunspell/bugs/153](https://sourceforge.net/p/hunspell/bugs/153)

**Comment by dimztimz** [comment]
This is by design. As I jumped around issues, i learned that munch and unmunch are tools for MySpell dictionaries which does not support two twofold suffixing.
