### ISSUE TITLE
Cannot add words to personal dictionary

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#153]
when working with ru_RU dictionary, the add word function is bugged,,, it asks for a model word but _whichever_ word is entered it says 'A model word should be in a dictionary!' please fix it asap its unacceptable!!! ru_RU.UTF-8 locale was used.

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/165](https://sourceforge.net/p/hunspell/bugs/165)

**Comment by dimztimz** [comment]
Closing this due to lack of information.
