### ISSUE TITLE
Divide-by-zero error in HashMgr::hash

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#154]
When stress testing hunspell under low memory conditions I got a divide-by-zero error in HashMgr::hash(const char * word)

Fix is pretty simple: just add the following code just before the return statement:

// avoid divide by zero error in % operator if tablesize == 0
if ( tablesize == 0 )
return 0;

Thanks
MarkR

Original comment by: mrogers6

Original Ticket: [hunspell/bugs/166](https://sourceforge.net/p/hunspell/bugs/166)

**Comment by dimztimz** [comment]
Quoting from #246. Also related to #245 

> For example, if a dictionary fails to load, calling Hunspell::add will try to divide by zero when you get down into the HashMgr::hash method because tablesize is 0.
