### ISSUE TITLE
-q/-v option to munch

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#16]
It would be handy to have a quiet or verbose option to
munch.  Currently, it's spitting out tons of
information.  For me, that's annoying, because I need
to call it almost hundred times \(it cannot handle our
lexicon at once: after 16 hours it wasn't finished
yet\).  In a script, I sent the stderr output to
/dev/null, but then it took me a day to discover that
the path wasn't set correctly and the permissions
weren't right \(because they were also sent to
/dev/null\).  -q would hide the parsing information on
request, but still show other errors.

Original comment by: fouvry

Original Ticket: "hunspell/bugs/13":https://sourceforge.net/p/hunspell/bugs/13

**Comment by linuxjackto1** [comment]
thanks www.movied.org

**Comment by dimztimz** [comment]
Closing this since no improvements should be made on the old much (only bugfixes). A new issue can be opened for the new munch.
