### ISSUE TITLE
ABI breakage in 1.2.15/1.3.0?

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#168]
When lookging over a diff 1.2.15 -&gt; 1.1.25/1.3.0 I see this:

@@ -152,7 +159,7 @@
void        setcminmax\(int \* cmin, int \* cmax, const char \* word, int len\);
struct hentry \* compound\_check\(const char \* word, int len, short wordnum,
short numsyllable, short maxwordnum, short wnum, hentry \*\* words,
\-            char hu\_mov\_rule, char is\_sug\);
\+            char hu\_mov\_rule, char is\_sug, int info\);

int compound\_check\_morph\(const char \* word, int len, short wordnum,
short numsyllable, short maxwordnum, short wnum, hentry \*\* words,

hentry unfortunately is a public: truct, though there wasn't a SONAME bump here?

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/182](https://sourceforge.net/p/hunspell/bugs/182)

**Comment by dimztimz** [comment]
Lot of API changes happened, not just ABI, so this is kinda irrelevant.
