### ISSUE TITLE
ensure only one instance of each dict is in memory

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#169]
Use Case: 
Lokalize \(computer-aided translation system\) uses standard KDE plugins for spell checking \(in my case enchant plugin uses hunspell library\)

Also i create Hunspell instance directly for stemming purposes, so this means there is two dict instances in RAM for each language \(dict file\)
Massif tool of valgrind report Hunspell::Hunspell\(\) -&gt; HashMgr::HashMgr\(\) -&gt; HashMgr::load\_tables\(\) -&gt; HashMgr::add\_word\(\) allocating and keeping 12 megs of RAM in my case.

Is it possible that you add some static map that maps dict filepath to a Hunspell\*?
Then a static Hunspell\*-returning method may be added to Hunspell api.
P.S. i think it would be wise to protect access to internal data structures for each dict with mutexes \(or at least their creation and deletion\)

Original comment by: shaforostoff

Original Ticket: [hunspell/bugs/183](https://sourceforge.net/p/hunspell/bugs/183)

**Comment by dimztimz** [comment]
From what I understand, this is sharing the same Hunspell object among two processes. Or maybe two Hunspell objects (from different processes) to share the same resource.

That is really out of the scope of this project. It is too platform specific. This can be achieved with making some COM or CORBA wrappers, or maybe with a web-service.

Closing this.
