### ISSUE TITLE
clang and gcc compiler warnings in hunspell and hyphen

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#17]
hunspell-1.3.2/src/hunspell/hashmgr.hxx:74:21 [-Wunused-private-field] private field 'userword' is not used

hyphen-2.8.6/hyphen.c:308:4 [-Wtype-limits] comparison is always false due to limited range of data type
hyphen-2.8.6/hyphen.c:332:27 [-Wsign-compare] comparison between signed and unsigned integer expressions

Original comment by: cpeterso

Original Ticket: [hunspell/bugs/247](https://sourceforge.net/p/hunspell/bugs/247)

**Comment by dimztimz** [comment]
The line `for (i = 0; ((buf[i] > ' ') || (buf[i] < 0)); i++)` is the problematic one.
`buf[i] < 0` probably checks is the char a high ASCII char (128 <= c <= 255)
with the assertion that the type `char` is implemented as signed. In that case the high ASCII chars are negative.

There is a small problem that writing `char` alone in C is implementation defined, it can be signed on one and unsigned on another compiler.
