### ISSUE TITLE
en_US.zip missing COPYING

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#170]
The English spelling dictionary is licensed under LGPL, according to the file README\_en\_US.txt.  If that is true, it violates LGPL by not including the text of the license agreement with it.

Original comment by: yecril71pl

Original Ticket: [hunspell/bugs/184](https://sourceforge.net/p/hunspell/bugs/184)

**Comment by dimztimz** [comment]
There are no dictionaries in the source repo. If you mean the [sourceforge files](https://sourceforge.net/projects/hunspell/files/Spelling%20dictionaries/en_US/), then there is notice about the license in the readme which maybe is enough. The full text is available on gnu.org website.
Closing.
