### ISSUE TITLE
fail on WIN-1251 encoding

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#174]
if aff file in win-1251 encoding and aff file begins of "SET WIN-1251", then get_current_cs returns 0, so spelling will be incorrect.
to fix that, add this to endcs array:
{"win1251",cp1251_tbl},                    //WIN-1251

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/189](https://sourceforge.net/p/hunspell/bugs/189)

**Comment by dimztimz** [comment]
It should be `SET  microsoft-cp1251`
