### ISSUE TITLE
compound and twofold affix stripping uncompatible

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#176]
I'm trying to move to twofold affix stripping, but run into this problem:

STEM+COMPOUND does work.
STEM+AFFIX+COMPOUND does work.
STEM+AFFIX1+AFFIX2+COMPOUND does not.

Is this by design? Looks strange when only the first level stripping+compound works, and not the second...

\-----------files--------------

\# VERBS COMMON CONJUGATIONS common first level
SFX v Y 2
SFX v na na//+c na       \# stem
SFX v na kuna//+c na     \# gerund

\# VERBS COMMON CONJUGATIONS common second level 
SFX c Y 2
SFX c na na//+ na          \# Infinitive
SFX c na nki//+ na         \# Present 2nd person singular | Future 2nd person singular/plural

\--------end files--------
Testing:
$ echo rikuna rikunapash rikumunapash rikunki rikunkipash|hunspell -d qu\_EC -m

\[STEM\] works
rikuna  st:rikuna
rikuna  st:rikuna \# stem
rikuna  st:rikuna \# stem \# Infinitive

\[STEM+COMPOUND\] works
rikunapash  pa:rikuna \(  st:rikuna \# stem |  st:rikuna \# stem \# Infinitive \)  pa:pash

\[MORPH level1+COMPOUND\] works
rikumunapash  pa:rikumuna \(  st:rikuna \# coming here doing |  st:rikuna \# coming here doing \# Infinitive \)  pa:pash

\[MORPH level 2\] works
rikunki  st:rikuna \# stem \# Present 2nd person singular | Future 2nd person singular/plural

\[MORPH level 2+COMPOUND\] does not work:
rikunkipash

Original comment by: arnotixe

Original Ticket: [hunspell/bugs/191](https://sourceforge.net/p/hunspell/bugs/191)

**Comment by arnotixe** [comment]
OK just tried this again after having downloaded newest tar.gz (1.3.3) and built it myself, running it with "hunspell-1.3.3/src/tools/hunspell -d test -m test.txt" and yeyyy:

selfexplainednessishish  pa:selfexplainedness st:self # Level1 # Level2 pa:ish st:ish pa:ish

yup that's twofold affix stripping with no less than two follow-up compounds!

please mark this as SOLVED :)
