### ISSUE TITLE
Use AC_CANONICAL_HOST for detecting cross-compilation

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#179]
The current use of AC_CANONICAL_SYSTEM is deprecated.

--- hunspell-1.2.12/configure.ac    2010-07-14 09:33:05.000000000 +0200
+++ hunspell-1.2.12/configure.ac    2010-09-01 16:42:07.000000000 +0200
@@ -8,4 +8,4 @@

-AC_CANONICAL_SYSTEM
+AC_CANONICAL_HOST
AC_SUBST(XFAILED)

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/194](https://sourceforge.net/p/hunspell/bugs/194)

**Comment by dimztimz** [comment]
Duplicate of #192. Already fixed.
