### ISSUE TITLE
munch creates unnecessary duplicates

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#182]
Input file:
\------------------------------------------------
9
aalfvrmig
aalfvrmige
aalfvrmigem
aalfvrmigen
aalfvrmiger
aalfvrmiges
Aasgeier
Aasgeiern
Aasgeiers
\----------------------------------------------------

aff file:
\----------------------------------------------------------------
SET UTF-8
TRY esianrtolcdugmphbyfvkwd|v_aij`bqESIANRTOLCDUGMPHBYFVKWD\V

SFX A Y 46
SFX A   0       r          e
SFX A   0       n          e
SFX A   0       m          e
SFX A   0       s          e
SFX A   0       e          \[^elr\]
SFX A   0       er         \[^elr\]
SFX A   0       en         \[^elr\]
SFX A   0       em         \[^elr\]
SFX A   0       es         \[^elr\]
SFX A   0       e          \[^e\]\[rl\]
SFX A   0       er         \[^e\]\[rl\]
SFX A   0       en         \[^e\]\[rl\]
SFX A   0       em         \[^e\]\[rl\]
SFX A   0       es         \[^e\]\[rl\]
SFX A   0       e          \[^u\]er
SFX A   0       er         \[^u\]er
SFX A   0       en         \[^u\]er
SFX A   0       em         \[^u\]er
SFX A   0       es         \[^u\]er
SFX A   er      re         uer
SFX A   er      rer        uer
SFX A   er      ren        uer
SFX A   er      rem        uer
SFX A   er      res        uer
SFX A   0       e          \[eil\]el
SFX A   0       er         \[eil\]el
SFX A   0       en         \[eil\]el
SFX A   0       em         \[eil\]el
SFX A   0       es         \[eil\]el
SFX A   el      le         \[^eil\]el
SFX A   el      ler        \[^eil\]el
SFX A   el      len        \[^eil\]el
SFX A   el      lem        \[^eil\]el
SFX A   el      les        \[^eil\]el
SFX A   lig     elig       \[^aeiouhlrd|v\]lig
SFX A   lig     elige      \[^aeiouhlrd|v\]lig
SFX A   lig     eliger     \[^aeiouhlrd|v\]lig
SFX A   lig     eligen     \[^aeiouhlrd|v\]lig
SFX A   lig     eligem     \[^aeiouhlrd|v\]lig
SFX A   lig     eliges     \[^aeiouhlrd|v\]lig
SFX A   erig    rig        \[^hi\]erig
SFX A   erig    rige       \[^hi\]erig
SFX A   erig    riger      \[^hi\]erig
SFX A   erig    rigen      \[^hi\]erig
SFX A   erig    rigem      \[^hi\]erig
SFX A   erig    riges      \[^hi\]erig

SFX N Y 1
SFX N   0       n          .

SFX S Y 4
SFX S   0       s          \[^s_\]
SFX S   0       es         _
SFX S   0       es         ss
SFX S   s       ses        \[^s\]s

SFX W Y 8
SFX W   en      0          \[^imn\]en
SFX W   en      0          eien
SFX W   en      0          \[^bght\]\[mn\]en
SFX W   en      0          \[^c\]hnen
SFX W   n       0          e\[lr\]n
SFX W   st      0          \[^s\]st
SFX W   t       0          sst
SFX W   t       0          \[^s\]t
\----------------------------------------------------------
munch input\_file aff\_file creates:
\---------------------------------------------
aalfvrmig/A
aalfvrmigen/W
Aasgeier/NS
Aasgeiern/W
\---------------------------------

an unmunch test shows, /W words are completely unnecessary duplicates:
unmunch output\_file aff\_file
\-----------------------------------
aalfvrmig
aalfvrmige
aalfvrmiger
aalfvrmigen
aalfvrmigem
aalfvrmiges
aalfvrmigen
aalfvrmig
Aasgeier
Aasgeiern
Aasgeiers
Aasgeiern
Aasgeier
\------------------------------------

Original comment by: tyuk

Original Ticket: [hunspell/bugs/197](https://sourceforge.net/p/hunspell/bugs/197)

**Comment by dimztimz** [comment]
It is not an ideal compressor, it probably works as intended.
