### ISSUE TITLE
Contraction "everything's" Missing from en-US Dictionary

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#185]
I found that the contraction "everything's"/"Everything's" is missing form the en-US dictionary in Firefox. 

Original comment by: jonahbron

Original Ticket: [hunspell/bugs/200](https://sourceforge.net/p/hunspell/bugs/200)

**Comment by dimztimz** [comment]
It's there now with a suffix rule in the en-US SCOWL dict which is used in Firefox.
