### ISSUE TITLE
small configure.ac patch

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#192]
The right macro to use here is AC\_CANONICAL\_HOST. This is the one needed for cross-compilation, etc.

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/207](https://sourceforge.net/p/hunspell/bugs/207)

**Comment by dimztimz** [comment]
This fix makes sense, acording to this [guide](https://autotools.io/autoconf/canonical.html)

> One common mistake is to “go all the way” and always use the AC_CANONICAL_TARGET macro, or its misnamed predecessor AC_CANONICAL_SYSTEM.

**Comment by dimztimz** [comment]
Fixed
