### ISSUE TITLE
hunSPELL.bak conflict btw users

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#195]
I am using 1.2.8 on CentOS 6

When one users does "hunspell -c /tmp/foobar.txt", a file with the name /tmp/hunSPELL.bak is created while that runs. During this time, no other user can run "hunspell -c /tmp/..." as it will fail to write the /tmp/hunSPELL.bak file owned by the other user.  This is a big problem for example on shared server machines where hunspell is externally called from programs like alpine which puts temp message text in /tmp to spell check.

That temporary file needs to be given a unique name per user/process

Original comment by: *anonymous

Original Ticket: [hunspell/bugs/210](https://sourceforge.net/p/hunspell/bugs/210)

**Comment by dimztimz** [comment]
This seems to be fixed. Temporary filenames are created with unique name where needed.

There is only one file /tmp/hunspell.log that is with constant name, but that logfile is used only in debug builds. The [LOG define is manually disabled](https://github.com/hunspell/hunspell/blob/866e0ea935579a4211aa329852e39fdcdcc2c908/src/tools/hunspell.cxx#L68)

So, closing this as it is already fixed.
