### ISSUE TITLE
False negatives with leading capital letter and UTF-8

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#20]
Summary:
Hunspell (using the example program) seems to mark
words that start with a capital letter and contain
non-ASCII characters as mis-spelled and then lists the
same word
as one of the suggestions. This seems to happen only when
using UTF-8 encoded dictionary and string.

Steps to reproduce:
1. Using the example program, and (for example) the
Estonian UTF-8 encoded affix and dict file
(mug.imo.ee/speller/et_EE.zip) check a properly spelled
wordlist where words start with capital letters (included
in that package)

Expected results:
The words should pass the spell check.

Actual results:
Every word is marked as mis-spelled and the suggestion
lists contain the same words.

Notes/Workarounds:
Everything is fine when using Latin-1 for example. The 
problem is, there are some letters that don't map in that
space in Estonian. :-) I haven't tried this with other
languages, but one of the posts here about Russian seems
to maybe relate to the same problem.

Original comment by: filippl

Original Ticket: "hunspell/bugs/11":https://sourceforge.net/p/hunspell/bugs/11

**Comment by linuxjackto1** [comment]
thanks www.movied.org
