### ISSUE TITLE
hunspell: hangs with -D option

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#202]
Originally reported at http://bugs.debian.org/659281

hunspell -D does not return control to the console unless ^C is used.

This change has been proposed by Eli Zaretskii in emacs-devel mailing list

http://article.gmane.org/gmane.emacs.devel/149245

--- src/tools/hunspell.cxx~0   2011-01-21 19:01:29.000000000 +0200
+++ src/tools/hunspell.cxx  2012-03-21 16:40:31.255690500 +0200
@@ -1756,6 +1763,7 @@ int main(int argc, char** argv)
fprintf(stderr, gettext("SEARCH PATH:\n%s\n"), path);
fprintf(stderr, gettext("AVAILABLE DICTIONARIES (path is not mandatory for -d option):\n"));
search(path, NULL, NULL);
+      if (arg_files==-1) exit(0);
}

if (!privdicname) privdicname = mystrdup(getenv("WORDLIST"));

Original comment by: agmartin

Original Ticket: [hunspell/bugs/218](https://sourceforge.net/p/hunspell/bugs/218)

**Comment by svmhdvn** [comment]
Just made a PR to incorporate this change since there hasn't been much activity on the subject, let me know if it isn't suitable.
