### ISSUE TITLE
EN-US dict: "transfer"

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#208]
The "transfer" entry in the US english dictionary is bogus and allows "transfered" as a correct derivative term.
"transferred" \(note the double "r"\) is already included as a standalone entry.
Please edit the "tranfer" entry so "transfered" is not accepted as a valid word,

Thank you
A. Fournier

Original comment by: alexfournier

Original Ticket: [hunspell/bugs/226](https://sourceforge.net/p/hunspell/bugs/226)

**Comment by dimztimz** [comment]
Quick test in Firefox says this is fixed. transfered gets underlined.
