### ISSUE TITLE
Move source code to Git in SourceForge

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#209]
Please move source code to Git in SourceForge. Having the source code in Git makes it easy for the different communities developing dictionaries and hyphenation patterns to develop and test them. Merging changes for a new release will also be much more efficient.

If you want to find out why you want to do this and not be called stupid and ugly by Linus Torvalds ;\) see http://youtu.be/4XpnKHJAok8

Original comment by: pander

Original Ticket: [hunspell/bugs/230](https://sourceforge.net/p/hunspell/bugs/230)

**Comment by PanderOpenTaal** [comment]
Eventually that became https://github.com/hunspell/hunspell

Could you please close this issue? Thanks
