### ISSUE TITLE
Marathi,Urdu,Malayalam languages don't show similar suggestions that are shown by latin languages

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#215]
How to reproduce the issue:-
1: For Marathi language type word "अंप" which is inaccurate 
2: On suggestions you would expect suggestions but you get only one suggestion अंपायर
Fix:-
This is issue because to check permutations and combinations of missing words which is done using TRY part in aff file are missing

I have attached patch for Marathi language but i could not find aff file for Urdu language and Malayalam language in 
http://sourceforge.net/projects/openofficeorg.mirror/files/contrib/dictionaries/

Original comment by: anish_developer

Original Ticket: [hunspell/bugs/240](https://sourceforge.net/p/hunspell/bugs/240)

**Comment by ItsDavehere** [comment]
Hi my hunspell only recognized  and flaged words with 11 characters which should do with 2 characters any suggetions ?
