### ISSUE TITLE
Hunspell fails if user has shell aliases

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#225]
In bash, I set the following alias:

  alias ls='ls -bCFv'

The -F part appends "*" to the end of executable files.

This causes hunspell to fail with a message such as

  ls: cannot access /home/mernst/bin/Linux-x86_64/../install/hunspell-cvs/src/tools/hunspell*: No such file or directory

Note the trailing \* in the filename; the file does exist without the trailing *.

Hunspell should work properly regardless of shell aliases that a user may have set.

The attached patch corrects the problem for an alias of the ls command, by using "\ls" instead of "ls" as the command.

Original comment by: mernst

Original Ticket: [hunspell/bugs/256](https://sourceforge.net/p/hunspell/bugs/256)

**Comment by dimztimz** [comment]
Is this a patch not to the source but to the shell script that is outputted by libtool, lol. Libtool puts proxy shell scripts where we would expect the binaries, and the actual binaries are in the folder `.libs`. Closing.
