### ISSUE TITLE
Hunspell English dictionary needs update

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#229]
I hope I am reporting this in the right place, but if not please direct me to the right place before closing the bug.

It seems like the English Dictionary that comes with Hunspell hasn't been updated for a long time. Many newer words are not included in the dictionary, some words are only included in older dictations (e.g. Internet, vs lower case internet which is what people use now).

I believe an update to the dictionary is necessary. I don't know who would be in charge of doing it; hopefully this project?

I have some ideas about how to do the update, which I would love to share.

Original comment by: huji

Original Ticket: [hunspell/bugs/260](https://sourceforge.net/p/hunspell/bugs/260)

**Comment by dimztimz** [comment]
http://wordlist.aspell.net/
https://github.com/en-wl/wordlist
