### ISSUE TITLE
hungarian string causes crash in hyphenate

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#235]
Hi,

I using the current hunspell86.dll Version 1.2.554.16953 from nuget with NHunspell .Net wrapper. 
Internal we are calling the function:
MarshalHunspellDll.HyphenHyphenate(this.unmanagedHandle, word);

Now we have a string in hungarian that cases a Crash / Segmentation fault.

Examples:

"Vakuumszivattyz: szama szivattyz"

or 

"Vakuumszivattyz: tzllipte a bekapcsolasok srankinti maximalis szamat. A bekapcsolasok szamanak tzllipise a szivattyz karosodasat okozza."

Please fix this bug.

Thanks,

Gregor

Original comment by: glgweeke

Original Ticket: [hunspell/bugs/268](https://sourceforge.net/p/hunspell/bugs/268)

**Comment by dimztimz** [comment]
Duplicate of #12 and hunspell/hyphen#11. Closing here.
