### ISSUE TITLE
Condition field correction (dot and 'no more characters')

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#237]
Hello,
I was making dictionary and faced the situation where two words with similar endings must be in one SFX flag.
Plain example,

file.dic

> 2
> work/A
> rework/A

file.aff

> SFX A Y 2
> SFX A 0 less work #work --> workless
> SFX A 0 ing ework #work --> working; rework -> reworking

The target is, second word (rework) must not be affixed with first rule. But at the same time the first word (work) must be.
It is logicaly that dot (.) must be the first character in condition field to permit affixing word that has same ending. And if there's no dot (.) at the first place - the condition must mean "only these characters"
Like:

> SFX A 0 ing .work #rework -> reworking; but no 'work -> working' affixing.

and

> SFX A 0 ing work #work -> working; but no 'rework -> reworking' affixing.

So, is it possible to fix this in next release?

Original comment by: sspphheerraa

Original Ticket: [hunspell/bugs/270](https://sourceforge.net/p/hunspell/bugs/270)

**Comment by sspphheerraa** [comment]
This issue can be closed cause has no sense. Now I understand that 'no more characters' can't be implemented because we need affix sample for words of 'any length' and in case of 'no more characters' we would must determine length. And, so, that drops any sense of our spellchecker.

**Comment by dimztimz** [comment]
In some near of far future more powerful regular expressions (with stuff like ^ and $ which mean start and end of string) somewhere in the whole Hunspell processing. Now, closing this as requested.
