### ISSUE TITLE
Realloc leak in hunspell.cxx:337

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#238]
Visual Studio code analysis picked this up, [a C6308](https://msdn.microsoft.com/en-us/library/kkedhy7c.aspx).

In the function `get_parser`, at the line:

    casechars = (char *) realloc(casechars, strlen(casechars) + strlen(wordchars) + 1);

...if `realloc` fails, `casechars` is assigned `NULL`, and the address of the original allocation is clobbered, thus leaking the memory.

    C6308	Realloc leak	
    337	'realloc' might return null pointer: assigning null pointer to 'casechars', which is passed as an argument to 'realloc', will cause the original memory block to be leaked.

Original comment by: ariccio

Original Ticket: [hunspell/bugs/271](https://sourceforge.net/p/hunspell/bugs/271)

**Comment by ariccio** [comment]
Self-xref: @ariccio

**Comment by dimztimz** [comment]
Similar to #239 and #152 , already fixed.
