### ISSUE TITLE
segfaults with words of >100 chracters

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#24]
Hi Laci,

when there are words with more than 100 characters,
Hunspell (1.1.4) segfaults during spellchecking. With
"-" being a wordchar, 100 "-"'s in real life texts are
not so unusual as real words with 100 characters :-)

The hunmorph OOo component just refuses to check so
long words but crashes are at least not visible.

Bjoern

Original comment by: *anonymous

Original Ticket: "hunspell/bugs/15":https://sourceforge.net/p/hunspell/bugs/15

**Comment by linuxjackto1** [comment]
thanks www.movied.org
