### ISSUE TITLE
Local variable shadowing in hunspell.cxx:442

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#240]
Visual Studio code analysis picked this up, [a C6246](https://msdn.microsoft.com/en-us/library/eeb7y4c0.aspx).

In function `putdic`, at line 442:

```
int ret;
```

...shadows `int ret` from 435. I don't think that's what was intended.

```
C6246
Local declaration of 'ret' hides declaration of the same name in outer scope.
For additional information, see previous declaration at line '435'
```

Original comment by: ariccio

Original Ticket: [hunspell/bugs/273](https://sourceforge.net/p/hunspell/bugs/273)

**Comment by dimztimz** [comment]
Seems like it's already fixed.
