### ISSUE TITLE
Using uninitialized memory in hunspell.cxx:452 (related to local variable shadowing in #273)

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#242]
Visual Studio code analysis picked this up, [a plain-old C6001](https://msdn.microsoft.com/en-us/library/3fb5eatz.aspx).

In function `putdic` (I feel immature while reading that in my head), because of the variable shadowing that I reported in issue #273, the _outer_ `ret` might not be initialized.

C6001   Using uninitialized memory 'ret'.
    435 'ret' is not initialized
    437 Skip this branch, (assume '((w=strstr(word+1, "/")))==0' is false)
    452 'ret' is used, but may not have been initialized

Original comment by: ariccio

Original Ticket: [hunspell/bugs/275](https://sourceforge.net/p/hunspell/bugs/275)

**Comment by dimztimz** [comment]
Also, already fixed.
