### ISSUE TITLE
MAYBE using uninitialized memory in hunspell:497

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#243]
I'm not sure what's going on here, so I'll just post the warning that came from Visual Studio code analysis:

C6001	Using uninitialized memory '*r'.
	496	'*r' is not initialized
	497	'*r' is used, but may not have been initialized

Original comment by: ariccio

Original Ticket: [hunspell/bugs/276](https://sourceforge.net/p/hunspell/bugs/276)

**Comment by dimztimz** [comment]
I can't find this, probably it is already fixed.
