### ISSUE TITLE
write overrun in hashmgr.cxx:295

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#244]
Visual Studio code analysis picked this up, [a C6386](https://msdn.microsoft.com/en-us/library/ms182089.aspx).

In function `HashMgr::remove_forbidden_flag`, it looks like Hunspell is writing one-past-the-end of `flags2`.

`flags2` is allocated as:

```
unsigned short * flags2 =
(unsigned short *) malloc(sizeof(short) * (dp->alen - 1));
```

...and then written-to with:

```
for (i = 0; i < dp->alen; i++) {
    if (dp->astr[i] != forbiddenword) flags2[j++] = dp->astr[i];
}
```

I wouldn't see it myself (although I **_HATE**_ any use of the increment operator _inside_ of an array index, and thus would audit it carefully)...but `/analyze` sees it. Note that the size of `flags2` is `dp->alen - 1`, while the loop bound is `i < dp->alen`

```
C6386   Buffer overrun while writing to 'flags2':  the writable size is 'sizeof(short)*((dp->alen-1))' bytes, but '4' bytes might be written.

    290 'flags2' is an array
    292 Skip this branch, (assume '!flags2' is false)
    294 Enter this loop, (assume 'i<dp->alen')
    295 Enter this branch, (assume 'dp->astr[i]!=forbiddenword')
    294 Continue this loop, (assume 'i<dp->alen')
    295 Enter this branch, (assume 'dp->astr[i]!=forbiddenword')
    295 'j' may equal 1
    295 Invalid write to 'flags2', (outside its writable range)
```

Original comment by: ariccio

Original Ticket: [hunspell/bugs/277](https://sourceforge.net/p/hunspell/bugs/277)

**Comment by ariccio** [comment]
Self-xref: @ariccio

**Comment by dimztimz** [comment]
This is fine, the the new affix vector `flags2` is always smaller by exactly one. The `TESTAFF` above makes sure we can safely delete a flag from the previous `aStr`.
