### ISSUE TITLE
aspell dicts -> hunspell dicts

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#251]
From http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=324639:

--- snip ---
please add information how to build hunspell dictionaries from aspell
dicts. these dictionaries are mentioned on the hunspell home page.
--- snip ---

Original comment by: *anonymous

Original Ticket: "hunspell/feature-requests/6":https://sourceforge.net/p/hunspell/feature-requests/6

**Comment by samirmh00** [comment]
> Logged In: YES
> user_id=726595
> Originator: NO
> 
> Conversion steps:
> 
> A. dictionary (xx.cwl -> xx.wl):
> 1. preunzip xx.cwl # Aspell preunzip tools uncompress the word list
> 2. add word count to the first line of the word list:
> wc -l <xx.wl >xx.dic
> cat xx.wl >>xx.dic
> 
> B. affix file (Aspell uses MySpell’s format, so it is compatible with Hunspell, too)
> 1. if exist, rename it:
> mv xx_affix.dat xx.aff
> 2. if not, make it with the suitable character encoding (see xx.dat):
> echo “SET ISO8859-x” >xx.aff
> or
> echo “SET UTF-8” >xx.aff
> 
> It’s useful to add a TRY option with the characters of the dictionary with frequency order to set edit distance suggestions:
> 
> echo “TRY qwertzuiopasdfghjklyxcvbnmQWERTZUIOPASDFGHJKLYXCVBNM” >>xx.aff
> 
> Original comment by: nemethl

worked as well.
