### ISSUE TITLE
Move logic for locating the dictionaries to the library

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#257]
Especially useful if the patch for 1731630 gets applied:

It would be useful to move the "locate the dictionary" code from the command line frontend to the library, so applications don't need to reinvent the wheel to figure out what parameters to pass to the Hunspell constructor.

A new

Hunspell(const char * language=0)

constructor (with language being set to getenv("LANG" / "LC_MESSAGES" / "LC_ALL") if it's 0) would be a nice way to add it to the API.

Original comment by: bero

Original Ticket: "hunspell/feature-requests/14":https://sourceforge.net/p/hunspell/feature-requests/14

**Comment by dimztimz** [comment]
Some progress has been made for this, see file `src/hunspell/dict_finder.cxx`. So far I have support for searching dictionaries on GNU/Linux, OSX and possibly other POSIX OSs that follow the GNU/Linux file structure (they have `/usr/share` etc.)

I will close this once I add Windows functionality.

**Comment by dimztimz** [comment]
Done for v2
