### ISSUE TITLE
Should be a way to check without expense of suggestions

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#271]
Generating near-misses is a very expensive proposition computation-wise, especially when using large dictionaries, or when a word is encountered \(say, in source code embedded in an English document\) that is nowhere near any English words in its spelling. Yet much spell-checking done today does not need suggestions all of the time — say, when an interactive program is checking words just to underline them or otherwise flag a problem for the user. For example, if Emacs "flyspell" mode is used with a big hunspell dictionary, the editor can pause for a large fraction of a second each time the cursor encounters a mis-spelled word.

There ought, therefore, to be an option like "terse-mode" that turns off near-miss calculations in "-a" mode and just returns whether a word is a mis-spelling or not. It could just return zero for &lt;count&gt; and then list no mis-spellings, so that its output was compatible with the current format.

Or, if you wanted to avoid creating yet another mode, you could create a variant of the "^" command that never generates misses; I note that underscore "\_" is available and is a semantic opposite of "^" in many programmer's minds. :-\)

Original comment by: brandonrhodes

Original Ticket: [hunspell/feature-requests/30](https://sourceforge.net/p/hunspell/feature-requests/30)

**Comment by dimztimz** [comment]
At API level there are separate spell() and suggest() methods. At the level of the hunspell executable (.exe), there are the switches -L and -G
```
-G            print only correct words or lines
-L            print lines with mispelled words
```
