### ISSUE TITLE
Dictionary search path on OS X

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#273]
when buliding hunspell on OS X (darwin) the dictionary directories used by OS X should be added to the search path, e.g. /Library/Spelling/ and ~/Library/Spelling/, as well as the system dictionary directory (i don't know where it is).

when ./configure builds for installation in /usr/local, shouldn't /usr/local/share/myspell/ be added to the search path in addition to /usr/share/myspell/ ?

Original comment by: vidarg

Original Ticket: [hunspell/feature-requests/32](https://sourceforge.net/p/hunspell/feature-requests/32)

**Comment by client9** [comment]
* `/Library/Spelling` no longer exists on Mac OS X
* Mac OS X may use hunspell the library but they have a proprietary or binary binary wordlist.
* `/usr/local/share/hunspell/` should be added to default Prefix.  Home-brew and other distributions have to make a patch to add this.
*  or better use value of configure's `PREFIX` (thats probably a separate ticket)
*  `~/Library/Spelling/LocalDictionary` is now the personal dictionary (one word per line)

all misspell and ispell references should be removed in my opinion

**Comment by dimztimz** [comment]
I think this is done in v1 and version 2.

For v1 commit ef7a3255212c1d00c1618fdacff4652a6ed1d581 fixes so `~/Library/Spelling` is properly added.

For v2 commit 18ecdb406b93f63b93113036d2f527828050284c adds this folder in the search path.
