### ISSUE TITLE
Add UTF-8 APIs on Win32

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#276]
Right now hunspell uses ANSI strings and ANSI CRT, which limits it's functionality. Something among the lines of

Hunspell::Hunspell\(const char \* affpath, const char \* dpath, const char \* key, bool utf8\)

which sets a flag that HashManager & co. should decode utf-8 arguments and use wfopen instead.

Original comment by: *anonymous

Original Ticket: [hunspell/feature-requests/35](https://sourceforge.net/p/hunspell/feature-requests/35)

**Comment by dimztimz** [comment]
A better solution for windows is to directly provide additional functios with wchar_t * for filenames. That would be only windows. No utf-8 at all. I already described the situation here #329.
