### ISSUE TITLE
Use Ubuntu-compliant license headers

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#279]
Greetings,

Thank you for your great work for hunspell.
As discussed in Chromium Bug 98134 &lt;http://crbug.com/98134&gt; and Bug 29291 &lt;http://crbug.com//28291&gt;, hunspell uses license headers not compliant with the license-check script of Ubuntu. \(Unfortunately, this script does not allow using \#include to include license headers.\) It would be great to copy-and-paste kicense.hunspell to all .cxx and .hxx files.

Regards,

Hironori Bono

Original comment by: *anonymous

Original Ticket: [hunspell/feature-requests/38](https://sourceforge.net/p/hunspell/feature-requests/38)

**Comment by dimztimz** [comment]
I guess this is fixed in 59dc4be79add0f91b1da81415ab23f6bc138d144
