### ISSUE TITLE
Web service and web interface for test usage and demo

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#280]
Please offer a web service and web interface for test usage and demo in a similar way Language Tool has done this. Their demo usage web interface can be found here:
http://community.languagetool.org/
and example usage of their web service here:
http://archeus.ro/languagetool/check?language=en&text=Hello%20world,%20how%20are%20are%20you?
Usage of these must of course be throttled.

Benefits of offering this are live demonstration of spell checking for all supported languages and to have a reference implementation for testing for the latest stable software and latest stable dictionaries. Within the limitation of the server, these interface and service can also provided spell checking to software and users which don't have hunspell installed, such as certain mobile applications.

Original comment by: pander

Original Ticket: [hunspell/feature-requests/39](https://sourceforge.net/p/hunspell/feature-requests/39)

**Comment by PanderOpenTaal** [comment]
See also https://sourceforge.net/p/hunspell/mailman/message/30353346/ and http://www.brousant.nl/opentaal/online-hunspell

I am going to revive this code and contribute it to GitHub but I need somebody who is experienced in writing scripts for init and/or systemd. I have no preference so why not support both. Who can help out? @kroeckx ?

**Comment by kroeckx** [comment]
I really don't have the time for that.

**Comment by PanderOpenTaal** [comment]
Understood. Do you perhaps know anybody that could help with that from the Hunspell community or the Debian community?

**Comment by PanderOpenTaal** [comment]
The OpenTaal community is preparing a pull request for a daemon implementation. We have code that offers Hunspell spell checking as a service via UDP. For this we would like to register a default port number. What do the maintainers of Hunspell think of registering a port number at https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt or in HTML https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml ?

**Comment by dimztimz** [comment]
Web services are out of the scope of this project. This project is only about the core. One can easily create a RESTful web service exposing the spell() and suggest() functions.

Instead this, I just got the idea, maybe we should keep official bindings to other popular languages. But this is just an idea, should be done only if there is interest.
