### ISSUE TITLE
hunspell does not prepend $HOME to all USEROODIRs

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#32]
hunspell does not prepend $HOME to all USEROODIRs

patch attached

Original comment by: tpani

Original Ticket: [hunspell/bugs/236](https://sourceforge.net/p/hunspell/bugs/236)

**Comment by dimztimz** [comment]
This is already merged.

**Comment by dimztimz** [comment]
This patch actually isn't already merged. The diff is kinda wrong, the new changes are marked with minus sings and the old with pluses, that's why I though it was already merged.

**Comment by dimztimz** [comment]
I fixed this for v1. For v2 search for OOo dirs will be completely dropped.
Instead I will search Firefox and LibreOffice directories, both in the system wide location and in the user location.
