### ISSUE TITLE
Parser for docbook files

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#324]
When checking docbook files it turned out more convenient to have several tags and their content taken out of processing as they never contain something one can spell check. Mostly they contain non-words that appear just once in a document. The patch also contains a number of my docbook extensions commented out as a marker for people where to add their extensions.

Original comment by: ewald-arnold

Original Ticket: [hunspell/patches/42](https://sourceforge.net/p/hunspell/patches/42)

**Comment by dimztimz** [comment]
Same as #325 and #326 .
