### ISSUE TITLE
parser for source files when using gettext 

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#325]
the attached archive contains my parser for source files. I kept the parser rather losely so probably every source file can be checked. The parser assumes that there is always a leading keyword indicating a gettext call. Other strings are ignored and most probably of no interest to the end users.

When invoking the app you have to add "-S gettext" in the following examples for C and Lua:

gettext\("hello word"\);

gettext "hello word"

Original comment by: ewald-arnold

Original Ticket: [hunspell/patches/43](https://sourceforge.net/p/hunspell/patches/43)

**Comment by dimztimz** [comment]
I will say the same answer I said in #326 .
