### ISSUE TITLE
parser for pot files

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#326]
One more parser :-\) to check the pot/po files after merging and translating them. The parser only checks the translated content of the msgstr section.

My implementation needs option -O to select this parser.

Original comment by: ewald-arnold

Original Ticket: [hunspell/patches/44](https://sourceforge.net/p/hunspell/patches/44)

**Comment by dimztimz** [comment]
I don't think that adding parsers for the command line hunspell tool is productive. There are millions file formats. The command line hunspell is there mainly for testing so it should support only the most basic formats. Instead, for PO one can use text editor with a spellchecker, or even better a specialized editor for PO files, e.g. [Lokalize](https://userbase.kde.org/Lokalize), which includes this spellchecker.
