### ISSUE TITLE
display the current line

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#327]
I found it convenient to know the current line as I sometimes find other problems when spell checking. The attached patch displays the line right after the filename. 

I had to manually extract the relevant lines from a larger diff so there might be broken chunks. But the changes are small and you should get the idea anyway.

Original comment by: ewald-arnold

Original Ticket: [hunspell/patches/45](https://sourceforge.net/p/hunspell/patches/45)

**Comment by dimztimz** [comment]
The actual patch is missing even on Sourceforge. Closing.
