### ISSUE TITLE
-D shows all loaded dicts

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#328]
I was a bit  confused that hunspell -D showed only the first loaded dict. So after some investigation I added another line to display the alternatives as well:
# Index: src/tools/hunspell.cxx

--- src/tools/hunspell.cxx (Revision 20750)
+++ src/tools/hunspell.cxx  (Arbeitskopie)
@@ -1711,6 +1711,8 @@
pMS[dmax] = new Hunspell(aff, dic, key);
dic_enc[dmax] = pMS[dmax]-&gt;get_dic_encoding();
dmax++;
+                            if (showpath)
+                              fprintf(stderr, gettext("LOADED %d. DICTIONARY:\n%s\n%s\n"), dmax, aff, dic);
} else fprintf(stderr, gettext("error - %s exceeds dictionary limit.\n"), dicname2);
} else if (dic) pMS[dmax-1]-&gt;add_dic(dic);
}

BTW some lines to the top there is:

pMS[0] = new Hunspell(aff, dic, key);
dic_enc[0] = pMS[0]-&gt;get_dic_encoding();
dmax = 1;
if (pMS[0] && dicplus) while (dicplus) {

The check for pMS != 0 should be before pMS[0]-&gt; otherwise the app crashes in the unlikely case of a 0 from new.

Original comment by: ewald-arnold

Original Ticket: [hunspell/patches/46](https://sourceforge.net/p/hunspell/patches/46)

**Comment by dimztimz** [comment]
Fixed
