### ISSUE TITLE
script to get a full wordlist

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#335]
Laci, please find my script \(based on wordforms\) that outputs the whole dictionary to a file. Many people were asking for this, and if they don't mind the speed, here it is.

Original comment by: milek_pl

Original Ticket: [hunspell/patches/55](https://sourceforge.net/p/hunspell/patches/55)

**Comment by dimztimz** [comment]
Related to unmunch and #404 . Closing this.

**Comment by MonsterMMORPG** [comment]
@gpakosz any news about this? i need a tool that will iterate every word in dictionary and export to a file like unmunch. but unmunch doesnt work correctly so i need wordforms command
