### ISSUE TITLE
munch and hunspell v unmunch

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#340]
Hi,

You said that unmunch lacks some of the capabilities of
hunspell.  What is that status with munch?  We may have
to compile larger lexica, and would obviously need
munch for that.

And another question: if unmunch cannot generate all
strings from the lexicon, can hunspell find all
suggestions \(since that involves the same procedure\)?

Thanks,

Frederik

Original comment by: fouvry

Original Ticket: "hunspell/support-requests/1":https://sourceforge.net/p/hunspell/support-requests/1

**Comment by dimztimz** [comment]
Closing all issues related to unmunch.
