### ISSUE TITLE
Problem installing dictionary

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#341]
Hi!
I just got the newest Hunspell (German) for my OO 2.0.
After a lot of browsing I found out that I need a
reworked dictionary as well. I got it here:
http://j3e.de/hunspell/

Now, how to install the friggin thing? I loaded it with
the package manager, but it cannot be activated. It
doesn't show up in the linguistics-section either. So
Hunspell is pretty much useless to me at this point...
Any suggestions? 

cheers,
Tom

tomploeger "at" web.de 

Original comment by: *anonymous

Original Ticket: "hunspell/support-requests/3":https://sourceforge.net/p/hunspell/support-requests/3

**Comment by linuxjackto1** [comment]
thanks www.movied.org
