### ISSUE TITLE
unmunch vs hunspell

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#342]
You said theres a poor mans solution to unmunch with unicode affix rules, double suffix stripping and special flags e.g. circumfix,needaffix e.t.c

You gave the example below

[P x D x S x S] | hunspell -l

Could you give an example? I have such a challenge, i am developing a dictionary for OpenOffice using Hunspell

Attached are an example of a simple affix file and dictionary file

Original comment by: mauchege

Original Ticket: "hunspell/support-requests/4":https://sourceforge.net/p/hunspell/support-requests/4

**Comment by MonsterMMORPG** [comment]
@phajdan  i need help about wordforms. i need to iterate all words in a given dictionary and export found words into a file
