### ISSUE TITLE
Looking for DLL

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#343]
As I know, the DLL library available within "Delphi Text editor example \(with Hunspell 1.1.4 DLL\)" is not up-to-date. Where I can find up-to-date \(binary\) DLL?

Original comment by: gskoczylas

Original Ticket: [hunspell/support-requests/5](https://sourceforge.net/p/hunspell/support-requests/5)

**Comment by dimztimz** [comment]
Prebuilt binaries are not provided at the moment here. One can use easily compile the project. For DLL the Visual Studio .sln can be used.

And generally, for C++, only prebuilt executables, but not libraries, make sense. That is due to ABI incompatibilities among compilers.
