### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#346]
Hi,

I had modified Hunspell for windows to work on windows mobile. To adhere to the license models, how may I go about redistributing my changes for the community. I understand I may do so on a personal website but I'd like for it to survive that case.

Secondly, GNU Library or Lesser General Public License \(LGPL\), Mozilla Public License 1.1 \(MPL 1.1\) are whats is listed, by any chance are the GPL and LGPL licenses version 1?

Thanks in advance.

Original comment by: totallymystic

Original Ticket: [hunspell/support-requests/9](https://sourceforge.net/p/hunspell/support-requests/9)

**Comment by dimztimz** [comment]
In the era of Github one can just fork, and all copyright notices, licences and whatever remains there.

As a additional note, licencing a code under GPL is done by including a [copyright notice](https://www.gnu.org/licenses/gpl-howto.html).
