### ISSUE TITLE
Wrong hyphenation Hunspell

### ISSUE THREAD

**Issue by tonymeijer** [hunspell/hunspell#347]
Hi,

I am using Hunspell for hyphenate and spell check in InDesign CC2014. I have this issue:

When I use a word with a hyphen sign already in (like Sint-Petersburg), Hunspell does not hyphenate right. Two (both wrong) possibilities:

When I don't have the line 'NOHYPHEN -' in the hyph_nl_NL.dic, it hyphenates like this:
.... ..... .... Sint-
-Petersburg .... ....

In other words, it generates the hyphen but leafs the self typed hyphen.

When i DO use the line 'NOHYPHEN -' in the hyph_nl_NL.dic, it hyphenates like this:
.... ..... ....
Sint-Petersburg .... ....

Which of course is exactly what the line means.

But: In InDesign CS5.5 and earlier, it hyphenated like this:
.... ..... .... Sint-
Petersburg .... ....
Which is exactly what should be done.

When we set Proximity instead of Hunspell it works fine.

What to do???

regards, Tony Meijer

**Comment by baarsrj** [comment]
Unfortunately, the hyphenation software only allows only ascii letters, not a hyphen, and is limited in number of characters in the pattern. It certainly needs a big update.

**Comment by dimztimz** [comment]
Closing as not related to the spellchecker. Forwarded to the proper project.
