### ISSUE TITLE
Fix links at http://hunspell.sourceforge.net

### ISSUE THREAD

**Issue by changwoo** [hunspell/hunspell#349]
The sourceforge project page link "Issue tracker" refers to this github issue page, but the http://hunspell.sourceforge.net page still refers to the sourceforge issue page.

I think this github one is the current one. But README has http://hunspell.sourceforge.net link so many people think sf.net issue tracker is the current.

Please fix links at http://hunspell.sourceforge.net. And if possible, I also hope you move the home page out of sourceforge.net.

**Comment by plicease** [comment]
This confused me as well.
http://sourceforge.net/p/hunspell/mailman/hunspell-devel/?viewmonth=201507
