### ISSUE TITLE
Broken language code standard URL at src/hunspell/langnum.hxx

### ISSUE THREAD

**Issue by changwoo** [hunspell/hunspell#350]
In src/hunspell/langnum.hxx,

```
/*
 language numbers for language specific codes
 see http://l10n.openoffice.org/languages.html
*/
```

But the openoffice.org link is not available anymore.

(I guess these are basically the international calling codes which are not actually good for "language" codes.)

**Comment by dimztimz** [comment]
Fixed in 48339d77a875d72561c2367803315c4571780d07
