### ISSUE TITLE
Space Replacement.

### ISSUE THREAD

**Issue by b00f** [hunspell/hunspell#352]
Hi,

I am working for Morphological Hunspell Dictionary for Persian Language. I have faced some problems. Fortunately I could find some workarounds for my issues. but just for one issue still I am working. Let me explain it here.

Verbs in Persian Language have three main parts: Prefix, Stem and Suffix. (PFX+STM+SFX)
The problem is between prefix and stem (or stem and suffix) can be a space, zero-with-non-joiner, or none of them.
look at here. to make it simple I just show you a simple verb with prefix and stem here:

http://i60.tinypic.com/4r9slu.png

As you can see,
Number one is combination of prefix and stem without space.
Number two is combination of prefix and stem with zero-with-non-joiner.
Number three is combination of prefix and stem with a space. (it is a common mistake in written persian language)

As I understood from the manual (hunspell manual) there is an amazing example:
It can suggest "a lot" (with space) instead of "alot", simplily by this line:
REP alot a_lot

So, my question is: Is there any way for vise versa? I mean to suggest "alot" instead of "a lot";
REP a_lot alot  (???)

my second question: Is there any way to suggest hunspell for removing a character for better predict, like:
REP X

Regards,

**Comment by baarsrj** [comment]
Unfortunately, Hunspell gets the text word by word. Therefore there is no way to correct two words into one.

**Comment by chrispy-snps** [comment]
Thanks @baarsrj! This is the information I was searching the issue archives for.
