### ISSUE TITLE
1.3.4 test failures

### ISSUE THREAD

**Issue by tgurr** [hunspell/hunspell#360]
12 tests fail for me, please see the attached test-suite.log
[test-suite.log.zip](https://github.com/hunspell/hunspell/files/126481/test-suite.log.zip)

The same errors can be observed on our CI:
https://galileo.mailstation.de/jenkins/job/arbor/5945/console

**Comment by reneengelhard** [comment]
sounds like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814968 to me? The fix is in that bug, and also upstream already (see ded5b4c62c37084d216154e02e4d5e6efbd3ccfa)

**Comment by reneengelhard** [comment]
if that is the case (which I assume) this a) should be reitled with "test failures because of new grep behaviour" or somesuch and b) be closed :). Don't have permission for either :)

**Comment by tgurr** [comment]
@reneengelhard indeed that was the case, thank you very much! I've applied the mentioned patch to our hunspell package. Closing this bug as it is already fixed in git master.
