### ISSUE TITLE
Word missing from en_au dictionary

### ISSUE THREAD

**Issue by adamfowlerit** [hunspell/hunspell#369]
'consequence' is a valid EN AU word, but missing from the dictionary.

**Comment by PanderMusubi** [comment]
Thas has to be reported at http://wordlist.aspell.net/ and can be closed here.

**Comment by adamfowlerit** [comment]
I can't even see an EN_AU dictionary option on that website?

**Comment by dimztimz** [comment]
Hard to find where that dictionary is maintained. It is mentioned here http://wordlist.aspell.net/other-dicts/ which follows to link on OpenOffice wiki https://wiki.openoffice.org/wiki/Australian-English_Spelling_Dictionary

Also there are two extensions that contain en_AU on openOffice, one is with all the [SCOWL dicts](http://extensions.openoffice.org/en/project/english-dictionaries-apache-openoffice), and one is older with [only en_AU](http://extensions.services.openoffice.org/project/AustralianDictionary). The readmes and changelogs might point to the source.

**Comment by adamfowlerit** [comment]
Ended up using Mozilla Firefox's dictionary file located here:

https://addons.mozilla.org/en-US/firefox/language-tools/

That seems to be continually updated.
