### ISSUE TITLE
Android build bustage with Hunspell tip

### ISSUE THREAD

**Issue by rvandermeulen** [hunspell/hunspell#373]
From Mozilla's CI:
https://treeherder.mozilla.org/logviewer.html#?job_id=19240045&repo=try

17:42:02     INFO -  /builds/slave/try-and-api-15-000000000000000/build/src/extensions/spellcheck/hunspell/src/affixmgr.cxx: In member function 'int AffixMgr::parse_cpdsyllable(char*, FileMgr*)':
17:42:02     INFO -  /builds/slave/try-and-api-15-000000000000000/build/src/extensions/spellcheck/hunspell/src/affixmgr.cxx:3873:41: error: 'class std::vector<w_char>' has no member named 'data'
17:42:02     INFO -                 memcpy(cpdvowels_utf16, w.data(), w.size());
17:42:02     INFO -                                           ^

**Comment by caolanm** [comment]
Its in C++11, so presumably your baseline is C++98. I can hack around that for now. But eventually more things are going to require C++11 and that baseline will have to be raised
