### ISSUE TITLE
Huge list of Security Issues with Hunspell 

### ISSUE THREAD

**Issue by AbhijatSaxena** [hunspell/hunspell#375]
Hi,

We have downloaded Hunspellx64.dll from OpenOffice,
We regularly scan our code with Veracode for security vulnerability scans,

While scanning your dll, we found a list of 23 flaws (check the image below)
This is the well known CWE 391 Flaw > Unchecked Error Condition
Further description about this flaw can be found in the below link
https://cwe.mitre.org/data/definitions/391.html

I was wondering if all these issues could be resolved and we can get a new version release from your end.

Any pointers/help/suggestions would be really helpful.

List of Flaws pointed out >

![veracode](https://cloud.githubusercontent.com/assets/4438308/14459694/08d73de6-00d7-11e6-8242-513057f00aeb.jpg)

**Comment by caolanm** [comment]
We don't provide dlls, only the source. Latest source in master when built will likely have a lot less of these.

**Comment by AbhijatSaxena** [comment]
Thanks @caolanm, that would help, I'll try building the latest source code, and will see if that fixes these issues, I'll upload the latest results soon !
