### ISSUE TITLE
Compiling with Visual Studio, missing files form project

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#378]
After opening the file with Visual Studio 2013 (and converting the project to vcxproj) I got compilation errors about missing object files and a missing header.

I manually added the sources for the xml parser and odf parser and the errors were gone, although other errors are shown but those are another issue.

Basically these files:

- xmlparser.cxx
- xmlparser.hxx
- odfparser.cxx
- odfparser.hxx

are missing from `hunspell.vcproj` and `hunspell.vcproj`. Just manually editing these files should do the trick.

There was another file related error, the file `hunvisapi.h` was missing so i renamed `hunvisapi.h.in`. As far as i see, in the makefiles the .h gets generated from .in. But that does not happens in Visual studio. Maybe defining a prebuild step is needed? Is that file ever modified or simple rename is enough?

**Comment by caolanm** [comment]
merged fix for this now, thanks
