### ISSUE TITLE
Visual studio error: can not allocate array of size 0 in the new parser files.

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#379]
After I managed the file dependencies in the VS project as described in #378 i got only 4 errors.

Visual Studio complains about the following line
`static const char* __PATTERN2__[][2] = {};`
in `xmlparser.xcc` and `odfparser.cxx`.

The error is `error C2466: cannot allocate an array of constant size 0`.

This is apparently non standard. Zero sized arrays are not allowed in C and in C++, e.g. `int a[0]`. Only GCC seems to support it http://stackoverflow.com/questions/9722632/what-happens-if-i-define-a-0-size-array-in-c-c.

**Comment by caolanm** [comment]
caused merged branch to fix this, thanks
