### ISSUE TITLE
Use of Unix only functions in tools\hunpell.cxx related to temporary files

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#381]
If few recent changes, particularly 95d580bb3f29804bd7aafdcabc288c572f2c1320 and f363580addc3a602ee113477d0e58693ce2d53d3 in the file src/tools/hunspell.cxx (the command line interface) functions like:

- mkdtemp
- unlink

 are used. Makes problems when compiling on Windows. I am not sure what is the security problem with the old `tmpnam` there, but some more portable way should be used, or at least conditional compilation with ifdefs.

**Comment by caolanm** [comment]
I'm open to patches

**Comment by dimztimz** [comment]
Ok, I did a liitle research, i'll post here.

Let's first see the scenario when creating a SINGLE temporary FILE.

For reference, GNU LibC http://www.gnu.org/software/libc/manual/html_node/Temporary-Files.html

1. We can either use `tmpnam()` to generate filename and `fopen()` to open the file. The security problem here is that between name generation and file opening, another process can create a file with the same name (or symlink). The solution is to use POSIX `open()` with a flag O_EXCL.
2. Second way of creating temp file is with `tmpfile()`. This seems safe and portable as is part of C standard library.
3. Third way of creating a temp file is with `mkstemp()`, similar to tmpfile but not part of the standard library. It differs in that it returns a posix file descriptor, not a standard `FILE *` stream.

At this moment, for SINGLE FILE, way 3 is used and previously way 2 was used. The change was probably unnecessary.

Now we have another scenario, creating a single TEMPORARY DIRECTORY. I will post that later.

**Comment by dimztimz** [comment]
As for temporary directory, we can

1. Generate dir name with `tmpnam()` and create that directory with `mkdir()` or `system("mkdir <dirname>")`. It may seem as we have the same problem as point 1 in the previous comment, the operations are not atomic. Bit mkdir (at least on windows) fails if the directory exists which is analogous to using `open()` with the flag O_EXCL.
2. Use `mkdtemp()` which makes the name generation and directory creation atomic, POSIX only.

But there is another problem here, even if we use safe temp dir creation, we must use safe temp file creation on any files inside that dir, which is not the case.

In the code, after the directory is created we use external command to create a file inside that directory (unzip and sed) and the atomicity is broken, making all these safety measures less useful.

**Comment by dimztimz** [comment]
Here is a possible fix, it reverts to tmpnam + mkdir for temp dir https://github.com/dimztimz/hunspell/commit/17a7e50bbed03c7c4d414d18008c67f418cb4550
