### ISSUE TITLE
Failing on tests

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#383]
Travis CI reports that the builds from about 10 days ago are failing on the tests. This is the first build that fails https://travis-ci.org/hunspell/hunspell/builds/125015251

Between that build and the last that works there are about 60 commits (can be seen on the compare button).

The command [git bisect](https://git-scm.com/docs/git-bisect) can be used to track down the exact buggy commit. Although, that operation should be done on Linux as those commits were problematic for compiling on windows.

**Comment by caolanm** [comment]
I had to switch to an older gcc/libstdc++ to find this, gcc >= 5.3 on Fedora 23/24 has always passed the tests. Back to Fedora 20 and I could reproduce and fix it
