### ISSUE TITLE
Various Wimplicit-fallthrough and Wabsolute-value warnings

### ISSUE THREAD

**Issue by rvandermeulen** [hunspell/hunspell#385]
On clang 3.8.0 on Hunspell master:

affentry.cxx:175:7: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
affentry.cxx:556:7: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

affixmgr.cxx:4573:7: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

hunspell.cxx:488:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
hunspell.cxx:564:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
hunspell.cxx:901:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
hunspell.cxx:1013:7: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

suggestmgr.cxx:917:11: error: absolute value function 'abs' given an argument of type 'typename iterator_traits<__normal_iterator<char *, basic_string<char> > >::difference_type' (aka 'long') but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
suggestmgr.cxx:936:11: error: absolute value function 'abs' given an argument of type 'typename iterator_traits<__normal_iterator<w_char *, vector<w_char, allocator<w_char> > > >::difference_type' (aka 'long') but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]

**Comment by rvandermeulen** [comment]
Some of those fallthroughs look intentional given the comments nearby, but some don't have any comments either.

Also, a couple new ones after today's changes:

hunzip.cxx:62:68: error: passing NULL to non-pointer argument 1 of 'std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&) [with _Tp = bit; _Alloc = std::allocator<bit>; std::vector<_Tp, _Alloc>::size_type = unsigned int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<bit>]' [-Werror=conversion-null]

suggestmgr.cxx:568:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
suggestmgr.cxx:570:18: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
suggestmgr.cxx:576:24: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
suggestmgr.cxx:583:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

**Comment by caolanm** [comment]
I think I've got most of the now, except for the fall through ones. The annotation thing would have to ifdeffed in I guess like the mozilla MOZ_FALLTHROUGH equivalent. All of them are currently marked as /*FALLTHROUGH*/ except for the ones that clang seems to be erroneously not parsing correctly. e.g.
hunspell.cxx:1013 is...

case NOCAP: {
  pSMgr->ngsuggest(slst, scw.c_str(), m_HMgrs);
  break;
}
