### ISSUE TITLE
hspell does not compile in mingw-w64

### ISSUE THREAD

**Issue by JPeterMugaas** [hunspell/hunspell#386]
When compiling hunspell 1.4.1 in mingw-w64, I encountered an issue with invalid type casts with munch.cxx and unmunch.cxx.

The problem is that code such as:
 nc = (int)((unsigned long)dp - (unsigned long)mp);

will assume that some types grow in size when compiled for 64-bits.  In Windows, this is not always true.  I did make a patch for this so that it could compile in mingw-w64 which use size_t instead of  int and unsigned long.

This is in a submission at:
https://github.com/Alexpux/MINGW-packages/pull/1412

MSYS2 also has some nice touches in their distribution that might be worth looking at, IMAO.

**Comment by dimztimz** [comment]
ptrdiff_t is probably the best solution there.

**Comment by dimztimz** [comment]
This is fixed and should be closed.
