### ISSUE TITLE
Hungarian: incorrect syllabication for world összevetésből

### ISSUE THREAD

**Issue by akoscomp** [hunspell/hunspell#388]
At line and hunspell hyphenate the world összevetéséből:
özs-szevetéséből
instead of
ösz-szevetéséből
but only if in the world exist a soft hyphen.
ex: összeveté(-)séből

I test it in LibreOffice 5.1.3.2 and 5.2.0.0.beta2

![2016-06-16 14_08_37-untitled 1 - libreofficedev writer](https://cloud.githubusercontent.com/assets/3304977/16114825/0308df64-33cc-11e6-9afd-3bf15883a9e8.png)

**Comment by akoscomp** [comment]
I test with összességében and faggyú world.
Without soft hyphen works fine, but if I put a soft hyphen in the worlds, the results was:
özs-szességében
fayg-gyú

**Comment by dimztimz** [comment]
I think the issue should be reported here https://github.com/hunspell/hyphen
This project is not responsible for hyphenation.

Also you kinda put the same hyphenation twice, which is the correct and which one is the wrong one?

**Comment by akoscomp** [comment]
Incorrect:
özs-szevetéséből
özs-szességében
fayg-gyú

Correct:
ösz-szevetéséből

**Comment by akoscomp** [comment]
I report the issue on hyphen project.

**Comment by dimztimz** [comment]
This should be closed here.

**Comment by akoscomp** [comment]
Yes.
