### ISSUE TITLE
Learning material for working with .aff file

### ISSUE THREAD

**Issue by JeyKeu** [hunspell/hunspell#392]
Hi, I working on a spell checker project for my language.
I can't find much learning material on the usage of affix rules.

I have managed to learn the bare basics but I need to learn more in order to complete the project.
It would be great if you guys could help me with articles or better, videos

Regards,

**Comment by dimztimz** [comment]
See here #395 I already answered a similar question.

**Comment by Kruno-S** [comment]
I had the same problem not so long ago. Check my dictionary repository here on Github (development branch) and if you think I can help you, leave an email here. Maybe your questions can help me to see which topics such learning material should cover.

**Comment by JeyKeu** [comment]
That would be really helpful. How can I contact you?

**Comment by Kruno-S** [comment]
I guess Github is not very good at this kind of collaboration. Email address is in licence.md file over in my dictionary repository...

**Comment by dimztimz** [comment]
I will close this as similar to #409 . In v2.0 documentation should be improved.
