### ISSUE TITLE
Is autoconf used anywhere by libhunspell?

### ISSUE THREAD

**Issue by jeroenooms** [hunspell/hunspell#394]
Because the API has broken between 1.3 / 1.4 / 1.5 we switched our application to bundle a copy of the `libhunspell` code. The only issue with this is that the configure script is difficult to bundle in a portable application that needs to build on e.g. windows as well.

However it looks to me that none of the autoconf macros are used anywhere in `libhunspell`? The only `#include "config.h"`statement exists in `src/hunspell/hunspell.cxx` but it doesn't seem to be needed? Can we just take this out?

If the `configure` script is really only needed to build the command line utilities form `src/tools` but the `libhunspell` and `parsers` code is fully portable by itself, it might be worth splitting the build or fully getting rid of autoconf.

**Comment by caolanm** [comment]
yeah, it seems to be the case that config.h isn't needed in src/hunspell/hunspell.cxx so that's gone now.

IIRC there is a bundled config.h which is suitable for windows anyway. For LibreOffice with bundled hunspell we don't run configure under Windows
