### ISSUE TITLE
Add a language

### ISSUE THREAD

**Issue by laberba** [hunspell/hunspell#395]
How do I add my local language: Akan (ak)?

**Comment by dimztimz** [comment]
You need to create two files, .dic and .aff.
Please check the [documentation](https://sourceforge.net/projects/hunspell/files/Hunspell/Documentation/), especially the file Hunspell4.pdf.

It is not a fast process, there are two milestones. 1. Collecting words and pitting them in the .dic file, and 2. writing grammatical rules in the .aff file.
