### ISSUE TITLE
PFX of PFX not supported?

### ISSUE THREAD

**Issue by Gallaecio** [hunspell/hunspell#398]
I am writing a basic unmunch program in C++ that aims to ignore errors as long as user intentions are unambiguous. So although if this is a bug I would like it to be fixed, what I really want to know is whether this is a bug, desired behavior or some mistake on my side, so that I can adjust my program to treat these cases accordingly. 

I have the following Hunspell files that I expect to support ‘c’, ‘bc’ and ‘abc’:

    [achaves@chakra temporal]$ cat test.aff 
    SET UTF-8
    FLAG num
    PFX 1 Y 1
    PFX 1 0 a
    PFX 2 Y 1
    PFX 2 0 b/1
    
    [achaves@chakra temporal]$ cat test.dic
    1
    c/2
    

However, ‘abc’ is not considered a valid word:

    [achaves@chakra temporal]$ cat test.txt 
    a b c d e ab ac ad ae bc bd be cd ce de abc abd abe acd ace ade bcd bce bde cde abcd abce abde acde bcde abcde
    [achaves@chakra temporal]$ echo $(cat test.txt) | hunspell -d test -G
    c
    bc
    [achaves@chakra temporal]$

The same does seem to work with SFX:

    [achaves@chakra temporal]$ cat test.aff 
    SET UTF-8
    FLAG num
    SFX 1 Y 1
    SFX 1 0 c
    SFX 2 Y 1
    SFX 2 0 b/1

    [achaves@chakra temporal]$ cat test.dic
    1
    a/2

    [achaves@chakra temporal]$ echo $(cat test.txt) | hunspell -d test -G
    a
    ab
    abc
    [achaves@chakra temporal]$

**Comment by dimztimz** [comment]
Look at the part "Twofold **suffix** stripping" in the documentation http://linux.die.net/man/4/hunspell

There is some option COMPLEXPREFIXES.

**Comment by Gallaecio** [comment]
Thanks, I am sorry I missed that part of the documentation.
