### ISSUE TITLE
munch is really slow

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#40]
Hi,

from http://bugs.debian.org/428284:

\--- snip ---
From: Kurt Roeckx &lt;kurt@roeckx.be&gt;
To: submit@bugs.debian.org
Subject: hunspell-tools: munch is really slow
Date: Sun, 10 Jun 2007 14:27:28 +0200

Package: hunspell-tools
Version: 1.1.5-6

Hi,

The munch command is really slow.  It does almost the same as
munchlist from the ispell package, which takes 7.5 seconds here, while
munch takes 22 minutes.

aspell also has something to do that, does it in 2 seconds,
but doesn't seem to produce simular/compatible output.

They basicly all 3 do the same thing, so I wonder why hunspell's is
so slow compared to the other 2.

Kurt

\[...\]
From: Thijs Kinkhorst &lt;thijs@debian.org&gt;
To: 428284@bugs.debian.org
Subject: Re: hunspell-tools: munch is really slow
Date: Sun, 10 Jun 2007 19:59:18 +0200

\[Message part 1 \(text/plain, inline\)\]

Hi,

&gt; The munch command is really slow.  It does almost the same as
&gt; munchlist from the ispell package, which takes 7.5 seconds here, while
&gt; munch takes 22 minutes.

Yes, I can reproduce this here. It's particularly annoying since the tool is 
used in the build process of our package 'dutch', and as such every build 
takes very long.

I'd highly appreciate it if this could be addressed. Please let me know if you 
need more information.

thanks\!
Thijs
\--- snip ---

Regards,

Rene

Original comment by: *anonymous

Original Ticket: "hunspell/bugs/29":https://sourceforge.net/p/hunspell/bugs/29

**Comment by dimztimz** [comment]
Closing this. Newer methods for automatic detection of suffixes and prefixes should probably be written.

Looking into research papers is a good idea. https://scholar.google.com/scholar?q=natural+language+processing+suffix+compress
