### ISSUE TITLE
HU_hu still crashes

### ISSUE THREAD

**Issue by jeroenooms** [hunspell/hunspell#402]
The crashes with `hu_HU` dictionaries were only partially fixed in https://github.com/hunspell/hunspell/commit/589e3c96715db099216a78f38f609fb84fd36e62. 

When using `hu_HU` with a text parser or `suggests()` function it still segfaults after a while. Strangely this does not happen for other languages, I have only seen this for Hungarian.

**Comment by caolanm** [comment]
There's just been another hu-HU fix committed. Does that make a difference, otherwise can you provide a sample that crashes ?

**Comment by jeroenooms** [comment]
Maybe my dictionary is messed up. Do you have a non-utf8 `hu_HU` dict that you test with?

**Comment by jeroenooms** [comment]
All Debian and Ubuntu systems have a UTF8 hungarian dictionary:

```
# hu_HU dict in UTF-8
sudo apt-get install hunspell-hu
```

But there is also a legacy dictionary with `encoding: ISO8859-2`:

```
# hu_HU dict in ISO8859-2
sudo apt-get install myspell-hu
```

You can reproduce most problems by installing (only) the latter dictionary.

**Comment by caolanm** [comment]
I'm not using debian, but by digging into old versions of hu_HU.aff I found a 
VERSION Magyar 1.0-RC3-beta_1
SET ISO8859-2
.aff

But using master hunspell against that dictionary
./src/tools/hunspell -d ~/builds/hunspell-hu/hu_HU
I get...
Hunspell 1.5.0 - Magyar 1.0-RC3-beta_1
magyar
*

magyas
& magyas 5 0: magas, magyal, magyar, magvas, Magyarsas
without an error.

Is there scenario which I can reproduce locally for the crash you have ?

**Comment by jeroenooms** [comment]
I will try to write an example. My bindings are using the C++ API...

**Comment by jeroenooms** [comment]
I am working on a simple case here: https://gist.github.com/jeroenooms/44c814a5c9eee26cc450490fdf3f8f14

This is very primitive (completely ignores encoding for now) but I think you can already reproduce some problems with it.

**Comment by jeroenooms** [comment]
I wrote a simple program that tests the most important hunspell features: https://gist.github.com/jeroenooms/44c814a5c9eee26cc450490fdf3f8f14

The program hardcodes some Hungarian words so you can reproduce the problem. You might find that it does not work at all with the Hungarian`ISO8859-2` dictionary.

**Comment by chroby** [comment]
Issue #403 seems to support the idea there's a general issue with hu-HU checking. (With sample dict/aff file as well, reduced to a fairly minimal case)

As for why only Hungarian, I'd bet on the fact that there are plenty of special cased code paths just targeting hu-HU.

**Comment by jeroenooms** [comment]
@caolanm @dimztimz on a sidenote, a minimal (< 100 line) example with basic functionality such as the one I posted above would be great to include with the library as a test/util. As a new user, it took me about a week to figure this out. 

It is not immediately obvious that it is up to the user to convert strings to the dictionary encoding before testing (I would have assumed the library would do this) or that you need to invoke the parser differently for UTF-8 dictionaries than for 8bit dictionaries.

**Comment by jeroenooms** [comment]
Were you able to reproduce this problem using my [example program](https://gist.github.com/jeroenooms/44c814a5c9eee26cc450490fdf3f8f14#file-main-cpp)?

**Comment by dimztimz** [comment]
What versions are affected? Is it the upstream master or some of the releases?

**Comment by jeroenooms** [comment]
This is in the master branch

**Comment by dimztimz** [comment]
I can not reproduce a crash (segfault). The example you posted when in non utf mode does not even calls `spell()`. And when in utf it works. So I do get the same behavior as you got but that is not a crash.

The myspell-hu package contains 2 Hungarian dictionaries, one with ISO and one with UTF encoding. And with the main hunspell binary i get the following.

```
$ sudo apt install myspell-hu
...
$ ./hunspell -d hu_HU

Hunspell 1.5.0 - Magyar 1.6
Jó napot kívánok asfasfasfsdfasdfsadfasdf
*
& napot 6 3: napos, napol, napbot, napout, napút, naponta
& k�v�nok 3 9: kíván ok, kíván-ok, kív
# asfasfasfsdfasdfsadfasdf 17

$ ./hunspell -d hu_HU_asd
Can't open affix or dictionary files for dictionary named "hu_HU_asd".

$ ./hunspell -d hu_HU_u8
Hunspell 1.5.0 - Magyar 1.6     
Jó napot kívánok asfasfasfsdfasdfsadfasdf
*
& napot 6 3: napos, napol, napbot, napout, napút, naponta
& kívánok 3 9: kíván ok, kíván-ok, kíván
# asfasfasfsdfasdfsadfasdf 17

```

**Comment by dimztimz** [comment]
Issue #403 being resolved, you might want to test with the branch ver1-5 about this.

**Comment by jeroenooms** [comment]
Just checked against the `v1.5.4` release and the problem seems to have been fixed. Thank you!
