### ISSUE TITLE
Suffixes (in hu-HU) not handled correctly

### ISSUE THREAD

**Issue by kaboomium** [hunspell/hunspell#403]
We've created a minimal case that demonstrates the failure. "kuldetest" should pass but doesn't. Commenting out the COMPOUNDSYLLABLES rule makes it work, so perhaps related.

[huntest.zip](https://github.com/hunspell/hunspell/files/464108/huntest.zip)

**Comment by chroby** [comment]
Note: This also happens with the full hu-HU dictionary as shipped with Chromium (in case there's an issue in the reduced testcase - we did not have Hungarian speakers to help us formulate that)

**Comment by dimztimz** [comment]
Since it is not a crash, I'm moving this to v2.0.

And since it appears in chromium, and chromium uses hunspell v1.3.2, it is probably older bug.

**Comment by chroby** [comment]
Nope, it's not an older bug. Updating Chromium to the latest version triggers that bug in our unit tests. This bug is in HEAD. The first comment contains a repro case as well, so you can easily verify.

Meanwhile, while it might not be a crash, it prevents Chromium from updating hunspell. And if you move this to 2.0, we'll have to migrate from 1.3.2 to 2.0, which is not a prospect that makes people happy because we expect a large delta.

We'd really appreciate it if you could investigate this sooner, so we can update our version continually.

**Comment by rvandermeulen** [comment]
At Mozilla, I've gotten reports of Hungarian spellchecking issues since we updated to v1.5. I'll add a bug reference here once it's filed.

**Comment by rvandermeulen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1320746 tracks this for Firefox

**Comment by dimztimz** [comment]
Tracking this bug should probably be done with `git bisect`. I am somewhat tired right now so it will wait unless someone else tracks it.

**Comment by dimztimz** [comment]
Git bisect inside the branch ver1-5

**Comment by dimztimz** [comment]
I still did the bisect. This is the final report

58b73a599b2820cd392358e6e6eb6f42b808c04a is the first bad commit
commit 58b73a599b2820cd392358e6e6eb6f42b808c04a
Author: Caolán McNamara <caolanm@redhat.com>
Date:   Tue Apr 19 12:22:40 2016 +0100

    const up

:040000 040000 8aea84ea8b314cefc0cb84627785715a50f5d762 d970843512a575ba44be996f9829bb3b506e0fa2 M	src

**Comment by dimztimz** [comment]
I guess i did the bisection wrong. Kinda does not makes sense. I should clean the of binaries in each step.

**Comment by dimztimz** [comment]
I've redone the procedure

44c870f7b7367d413d832c066ca3b1fbc4379eaf is the first bad commit
commit 44c870f7b7367d413d832c066ca3b1fbc4379eaf
Author: Caolán McNamara <caolanm@redhat.com>
Date:   Tue Apr 19 13:00:59 2016 +0100

    std::stringify a bit more

:040000 040000 d970843512a575ba44be996f9829bb3b506e0fa2 e68a17a491f652200557b536b242da3fda1f3f69 M	src

**Comment by dimztimz** [comment]
So that commit and maybe the commit after that 7999c39376bd55c6cdfc8fd8a71431e90ead0c2f (convert defcpdtable over now) are the culprit.

**Comment by chroby** [comment]
Thanks for doing this.

 Given that the test case is specifically related to COMPOUNDSYLLABLES, I'd suspect 7999c39  - except, that only touches COMPOUNDRULE. 

The other CL (std::stringify) does not exactly look like a suspect either... The only possible problem I can see there is in the default path for decode_flags, the old code cast to an unsigned char* first, while the current code casts the char directly to unsigned short (which sign-extends. The original doesn't)

I'm away from a compiler right now, so I can't try - but IIUC, the default path is indeed through there.

**Comment by dimztimz** [comment]
The cast actually is the problem. Hungarian dictionary uses characters as flags that are greater than 127. With char or signed char those are negative and sign extension happens.

The thing with the cast bug was fixed later in august 589e3c96715db099216a78f38f609fb84fd36e62 yet the head still has bugs with hu.
That suggests there is another buggy commit introduced in the meantime.

**Comment by dimztimz** [comment]
I did a bisect applying the cast fix on each step. This is the second culprit.

commit 32592380a2b8f58ef46db5cf896bf2970d286cf1
Author: Caolán McNamara
Date:   Thu Apr 21 12:45:04 2016 +0100

    convert parse_cpdsyllable to new apis
    
    also add sort of cpdvowels and use binary_search there too

**Comment by dimztimz** [comment]
Should be fixed in branch ver1-5. If unit tests pass for Chromium, please close this.

**Comment by rvandermeulen** [comment]
I'll generate a test Firefox build with this fix as well and see if our
reporter can confirm that things work as expected.

On Wed, Nov 30, 2016 at 11:21 AM, Dimitrij Mijoski <notifications@github.com

**Comment by kaboomium** [comment]
Verified in separate clone, looks good to me.
