### ISSUE TITLE
Documenting the code

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#409]
Current focus for further improvements should be on documenting the code.

Doxygen style should be used to document each class and each function. The tool apparently has the ability to generate include graph and call graph which should ease the process.

Documentation is necessary if contributors from outside are to be expected. I recently got into he team and I have hard time understanding the code.

**Comment by baarsrj** [comment]
Documenting the functionality (what the program is supposed to do), outside the code is even more important.

**Comment by dimztimz** [comment]
For reading v1 algorithms, the following helper tools may be used.

1. Doxygen with call graphs enabled on v1 code
2. CodeCompass
3. Sourcetrail

**Comment by dimztimz** [comment]
I was investigating what diagrams to use in the algorithm documentation, the INternal Specs page on the wiki.

Besides plain english and pseudocode, we can use various charts.

From the UML suite, Activity diagram and Sequence diagram are a possibility. The first is more centred towards the control flow and the second towards the data flow. But personally I don't find UML a good tools to document algorithms.

Instead I'd use [DFD](https://en.wikipedia.org/wiki/DRAKON) for the data flow, and [DRAKON](https://en.wikipedia.org/wiki/DRAKON). I was especially amazed with DRAKON, see the online editor. https://drakon-editor.com/

**Comment by PanderMusubi** [comment]
Thanks. I am reading up on affix file documentation and source code. Will look into the links you send me and we can discuss tomorrow.

**Comment by dimztimz** [comment]
Ok now, just to post some decisions here.

1. Code documentations is standard doxygen, no uml there. We document all public interfaces from v1 and v2. As for the internal function, we will document them only for v2, where appropriate.
2. The documentation outside of the code will be done mainly on the Wiki pages.
    1. Out of code documentation contains algorithm specs.
    2. May contain charts. Charts are put in the `misc-hunspell` repository.
    3. For UML we use [PlantUML](http://plantuml.com/)
    4. For DFD we can use this https://github.com/sonyxperiadev/dataflow (similar ro plantuml)
    5. For DRAKON we use [Fabula editor](http://drakon.su/programma_fabula_._redaktor_drakon-sxem). On Linux run with `wine`. Only wine is needed, nothing extra (`sudo apt install wine-stable`).
