### ISSUE TITLE
unmunch error

### ISSUE THREAD

**Issue by MayuraVerma** [hunspell/hunspell#412]
Kannada dictionary found in https://github.com/mgharish/kn-hunspell when unmunched. unmunch does not add multiple layer suffices. It stops at the first layer. 

Please advise

I install hunspell from this link http://macappstore.org/hunspell/

and below procedure

Install hunspell on Mac OSX
About the App

App name: hunspell
App description: Spell checker and morphological analyzer
App website: http://hunspell.sourceforge.net/
Install the App

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
and press enter/return key. Wait for the command to finish.
Run:
brew install hunspell
Done! You can now use hunspell.

**Comment by dimztimz** [comment]
That is a limitation of the unmunch tool.

Instead try unmoving with the bash tool word forms. https://github.com/hunspell/hunspell/blob/master/src/tools/wordforms
