### ISSUE TITLE
Suggest applications support the DICPATH variable

### ISSUE THREAD

**Issue by Jookia** [hunspell/hunspell#413]
It would be nice to have some official documentation or note suggesting applications should support reading various dictionaries (hunspell, hyphen, mythes) out of user-specified paths fed through an environmental variable. This would help users that want to supply their own dictionaries as well as exotic package managers like Guix or Nix set up environments with working spell checking.

Two applications I can count already do this: The hunspell executable and the enchant library (though that only supports one directory in the path). Having more applications add this feature shouldn't be too hard, I already have a patch on the way for LibreOffice that does this. A recommendation or even informal agreement would help boost acceptance for patches that add this feature aside from saying this is how the hunspell binary does it.

**Comment by dimztimz** [comment]
This is doable. Similar to #257 and #273.

Should be done outside of the main Hunspell class. Something like Dictionary_Search_Path_Manager.

**Comment by Jookia** [comment]
I don't know if code in hunspell needs to do this, just get applications to read the DICPATH variable then have distros/binaries set it appropriately.

**Comment by Jookia** [comment]
To elaborate on this: *right now* it seems easier to get upstreams of projects to agree to read DICPATH and factor that in to their custom code and data structures than it would be to get them to backport code from hunspell to their bundled versions or require distros to backport changes.

A good solution for now would be for projects to add some code like this to their projects then change it down the track if/when hunspell has this feature:

    char* pDicPath = getenv("DICPATH");
    if (pDicPath)
    {
        for ( char* pDir = strtok(pDicPath, ":"); pDir != NULL; pDir = strtok(NULL, ":") )
        {
            // loaddicts will make sure the dictionary is the right
            // type based on its prefix, that way hyphen, mythes and regular
            // dictionaries can live in one directory
            loadDicts(pDir);
        }
    }

    // load system directories last so that DICPATH prevails
    loadDicts(pSystemDir);

(Hunspell could provide an API eventually that just returns a list of paths based on multiple factors, including DICPATH)

What I'd like to see is agreement and recommendation on the variable's use for applications to implement in, mainly in these details:

- DICPATH is a list of dictionaries separated by ':'
- DICPATH is preferred over other directories
- DICPATH may contain hunspell, mythes and hyphen dictionaries, prefixed properly

An example DICPATH would be '/usr/share/hunspell:/usr/share/hyphen:/usr/share/mythes'

I intend to patch a few applications to look for dictionaries like this, and it'd be good if there could be agreement on these details by the hunspell project itself to aid the process of getting applications to do this officially. Currently the rationale is 'mimic the behaviour of the hunspell executable', but it would be nice for it to be 'follow hunspell recommendations and read DICPATH'

Of course, all this could be wrong and another system might be needed.

**Comment by Jookia** [comment]
See hunspell/hunspell#413 and https://gerrit.libreoffice.org/#/c/29543 for current upstream issues

**Comment by Jookia** [comment]
DICPATH pushed upstream as https://gerrit.libreoffice.org/gitweb?p=core.git;a=commitdiff;h=8e8afc358b7537d493b478b429e1711c6ab46bdc

**Comment by Jookia** [comment]
DICPATH for Firefox has passed review! https://hg.mozilla.org/integration/mozilla-inbound/rev/b9cd3d1a34e0

**Comment by dimztimz** [comment]
OK, since for v2 I am putting some functions to the library for locating the dictionaries, documenting this is the same as documenting the functions.

So far I consider DICPATH as a single path, I don't split it. See `src/hunspell2/dict_finder.cxx`

Additionally I'd like to point out that the code example 4 comments up is wrong and it contains undefined behavior. The contents of the returned buffer of `getenv` should not be modified, and `strtok` modifies it.

**Comment by Jookia** [comment]
Hey there- Yes the code was wrong, it was a draft. The actual code in LibreOffice and Firefox use the same basic flow but safe functions.

I'd heavily suggest DICPATH to be an actual PATH (instead of a DIR), the reasoning is that users or scripts may want to append different dictionaries packages at runtime. I set my system to generate DICPATH a while ago and it currently looks like 'DICPATH=/home/jookia/.nix-profile/share/hunspell:/home/jookia/.nix-profile/share/mythes:/nix/var/nix/profiles/default/share/hunspell:/nix/var/nix/profiles/default/share/mythes:/run/current-system/sw/share/hunspell:/run/current-system/sw/share/mythes'

This includes system-wide dictionaries, as well as ones I install locally as a user without root privileges. Currently I'm also dumping hyphenated dictionaries and thesauruses files in there too.

**Comment by dimztimz** [comment]
I think I am done with this.

**Comment by Jookia** [comment]
On Wed, Jan 11, 2017 at 10:37:13AM -0800, Dimitrij Mijoski wrote:
> I think I am done with this.

Thanks for your work!
