### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [hunspell/hunspell#415]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [HashMgr](https://github.com/hunspell/hunspell/blob/589e3c96715db099216a78f38f609fb84fd36e62/src/hunspell/hashmgr.cxx#L87 "Constructor for HashMgr")
* [HunspellImpl](https://github.com/hunspell/hunspell/blob/a6d32ee604e99ffc1919f38664817a2ee1500774/src/hunspell/hunspell.cxx#L159 "Constructor for HunspellImpl")

**Comment by dimztimz** [comment]
Can you point out the actual lines of code?

**Comment by elfring** [comment]
Did you dare to click on the provided links?

Examples:

Place | Update candidate | Line
----- | ---------------- | ----
1 | hashmgr.cxx | 87
2 | hunspell.cxx | 159
3 | suggestmgr.cxx | 142

**Comment by dimztimz** [comment]
I was expecting links to the lines with the calls to free.

Good notice. You can send a patch if you like.

**Comment by dimztimz** [comment]
Not a real bug, and also calls to free will probably get refactored in the future.

**Comment by elfring** [comment]
* I am curious if this software can become a bit faster by the suggested deletion of unnecessary null pointer checks.
* Would you like to use any "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")" instead?
