### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [hunspell/hunspell#416]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/hunspell/hunspell/blob/866e0ea935579a4211aa329852e39fdcdcc2c908/src/tools/hunspell.cxx#L1754 "main() function")" does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by dimztimz** [comment]
I'm not sure that exceptions are used in Hunspell at all.
I've heard this idea, of having a global try catch but that is only useful if you implement something like an error reporter.

Also, the article is just a joke. Not everything on the net is a good programming advice.

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](https://stackoverflow.com/questions/5557555/raii-and-stack-unwinding "RAII and Stack unwinding")?

**Comment by dimztimz** [comment]
Is there an actual unhandled exception?

**Comment by elfring** [comment]
How would you like to [handle an exception like "std::bad_alloc"](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Description for std::bad_alloc")?
