### ISSUE TITLE
Update gettext

### ISSUE THREAD

**Issue by doughdemon** [hunspell/hunspell#417]
Would it be possible to update the gettext infrastructure? In particular, I would like `m4/gettext.m4` to come from gettext of at least version 0.19.4. (With that version `AM_GNU_GETTEXT` recognizes the `gettext()` of musl libc.)

To update, use `gettextize -f` or `gettextize -f --intl` (deprecated).

I was going to submit a pull request but got sidetracked on considering whether it would not be better to not keep the generated files from gettext/autoconf/automake/aclocal/libtool in the repository.

**Comment by dimztimz** [comment]
I think that if you have gettext installed by your package manager, that version is used. The included version in the repo is just a fallback.

**Comment by doughdemon** [comment]
Dimitrij Mijoski wrote:
> I think that if you have gettext installed by your package manager,
> that version is used. The included version in the repo is just a
> fallback.

At least glibc and musl have gettext included in the c library. Many
other systems have an external libintl.

On systems using the musl c library currently always the included
libintl is used because of a bad configure test in gettext.m4. That's
why I am asking for an update of gettext.m4. (This would also fix
`AM_PROG_MKDIR_P` warnings when generating configure.)

**Comment by dimztimz** [comment]
Aha I see. What is the minimal fix without calling autoreconf?

**Comment by doughdemon** [comment]
The minimal fix would be to somehow apply

http://git.savannah.gnu.org/cgit/gettext.git/commit/gettext-runtime/m4/gettext.m4?id=b67399b40bc5bf3165b09e6a095ec941d4b30a97

to the configure script. The minimal sensible fix would apply the same
patch also to `m4/gettext.m4`. Alas, the patch from git does not apply
directly at all.

The next approach would be to replace `m4/gettext.m4` with the newest
version (and update configure accordingly). I don't know whether that
gives something functional, though.

**Comment by dimztimz** [comment]
Please try 6681a84f2d218d053830947016a1830b40a395c2

**Comment by doughdemon** [comment]
Thank you very much for the update!

Unfortunately I was wrong about the version of gettext:
At least version 0.19.7 is required for the issue I am interested in.
(When gettext in libc is not detected a file "locale.alias" is
generated, which causes file collisions between different packages
using gettext) I am sorry about that.

**Comment by dimztimz** [comment]
The updated version is 0.19.7. If the issue is resolved then you can close here.





-------- Оригинална порака --------
Од: Felix Janda
Датум:27/10/2016 17:39 (GMT+01:00)
До: hunspell/hunspell
Cc: Dimitrij Mijoski , Comment
Наслов: Re: [hunspell/hunspell] Update gettext (#417)

Thank you very much for the update!

Unfortunately I was wrong about the version of gettext:
At least version 0.19.7 is required for the issue I am interested in.
(When gettext in libc is not detected a file "locale.alias" is
generated, which causes file collisions between different packages
using gettext) I am sorry about that.

-

**Comment by doughdemon** [comment]
Dimitrij Mijoski wrote:
> The updated version is 0.19.7. If the issue is resolved then you can
> close here.

Oh, you are right.

It is still not fixed because I was again wrong about the necessary
version of gettext. gettext-0.19.8 is necessary. Right now I still get

checking for GNU gettext in libc... no

but when gettextizing with my locally installed version 0.19.8, it gets
correctly detected.

Now, it would be enough to drop a new version of gettext.m4 into m4,
and regenerate the autoconf script.

**Comment by dimztimz** [comment]
Do test again the latest commit and close the issue. I'm pretty sure everything is fixed now.

**Comment by doughdemon** [comment]
Yes, it is fixed now. Thanks a lot!
