### ISSUE TITLE
make failed for "canonicalize.h"

### ISSUE THREAD

**Issue by moonscar** [hunspell/hunspell#421]
Make message as below:
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in intl
gcc -c -DLOCALEDIR=\"/usr/local/share/locale\" -DLOCALE_ALIAS_PATH=\"/usr/local/share/locale\" -DLIBDIR=\"/usr/local/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/usr/local/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I..  -g -O2 -fvisibility=hidden  relocatex.c
relocatex.c:30:10: fatal error: 'canonicalize.h' file not found
#include "canonicalize.h"
         ^
1 error generated.
make[2]: *** [relocatex.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by moonscar** [comment]
My platform is macOS Sierra 10.12.1.

**Comment by dimztimz** [comment]
Seems like when I updated gettext, i included the the gettext bundled with MSYS2, which has some [windows specific patches](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gettext/00-relocatex-libintl-0.18.3.1.patch).

I will now include a vanilla gettext.

**Comment by dimztimz** [comment]
The latest commit 6fc00803bcc008b6f09d31308c59719e3f1de97f should fix the issue, please test and close.

**Comment by moonscar** [comment]
There is still a compile error message due to lack config.h.

In file included from xsize.c:3:
./xsize.h:31:3: error: "Please include config.h first."
 #error "Please include config.h first."
  ^
./xsize.h:33:1: error: unknown type name '_GL_INLINE_HEADER_BEGIN'
_GL_INLINE_HEADER_BEGIN
^
./xsize.h:59:13: error: expected ';' after top level declarator
XSIZE_INLINE size_t
            ^
            ;
./xsize.h:70:1: error: unknown type name '_GL_EXTERN_INLINE'
XSIZE_INLINE size_t
^
xsize.c:2:22: note: expanded from macro 'XSIZE_INLINE'
#define XSIZE_INLINE _GL_EXTERN_INLINE
                     ^
In file included from xsize.c:3:
./xsize.h:72:27: error: expected ';' after top level declarator
__attribute__ ((__pure__))
                          ^
                          ;
5 errors generated.

**Comment by dimztimz** [comment]
Please test. Compile like this:

```sh
./configure --with-included-gettext
make
```

Also test this:
```sh
brew update
brew install gettext
brew link gettext --force
./configure
make
```

The first case uses included gettext in the source tree, the second uses system installed gettext. The first case was happening on your side, but please test both if you can.

**Comment by moonscar** [comment]
Thanks for your help! Every thing is ok now.
I think things about gettext should be add in readme.md for mac user.

**Comment by gimansour** [comment]
the first option didn't work for me:
```
./configure --with-included-gettext
make
```

i had to do this:
```
brew update
brew install gettext
brew link gettext --force
./configure
make
```
