### ISSUE TITLE
Mozilla sponsoring

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#422]
In the beginning of 2016, I started an application for Hunspell to get some funding from Mozilla. At that time there was not much activity in the project so because of some delays and less time from my side, the application was put on hold by the side from Mozilla. However, they did encourage to continue the application at a later point in time when situation was more favourable. In order to get this going again, I need a person to help me with this, preferably to take over role for doing the application at Mozilla or at least do it together. for this application process I already have a lot of work done in motivating the request. Please, contact me for getting this support for Hunspell.

**Comment by dimztimz** [comment]
Seems like a nice idea.

**Comment by PanderMusubi** [comment]
See also https://www.mozilla.org/en-US/moss/ Let me know when you want to work on writing the application together.

**Comment by dimztimz** [comment]
How can I contact you, email maybe?

**Comment by dimztimz** [comment]
@PanderMusubi what happened with this?

**Comment by dimztimz** [comment]
@PanderMusubi any info on this or you left the idea?

**Comment by PanderMusubi** [comment]
Yes, I have info, sorry for the delay. Can you e-mail me users sourceforge (be creative)

**Comment by dimztimz** [comment]
I just sent you an email.

**Comment by dimztimz** [comment]
@PanderMusubi why you don't respond?

**Comment by PanderMusubi** [comment]
Something called X-mas. Will write you soon. Happy holidays!

**Comment by PanderMusubi** [comment]
Yes! I will dig up all correspondence for you.

**Comment by PanderMusubi** [comment]
See email

**Comment by dimztimz** [comment]
Thanks. I saw it.

**Comment by tbm** [comment]
Is there an update on this?

Oh, it [sounds like you received a grant](https://blog.mozilla.org/blog/2017/04/10/mozilla-awards-365000-to-open-source-projects-as-part-of-moss/).

Should this ticket be closed?
