### ISSUE TITLE
hunspell exited with code 53 when used in Emacs on Windows

### ISSUE THREAD

**Issue by x-ji** [hunspell/hunspell#423]
I downloaded hunspell from this Github repo and built it with Cygwin. I also provided it with various dictionary files. I can launch hunspell in Cygwin command prompt just fine. However, in Emacs I get the following error:

    Starting new Ispell process hunspell with en_US,de_DE,es_ES dictionary...
    Error enabling Flyspell mode:
    (hunspell exited with code 53)

I have the following code during Emacs initialization:

    (with-eval-after-load "ispell"
      (setq ispell-program-name "hunspell")
      (setq ispell-dictionary "en_US,de_DE,es_ES")
      ;; (setq ispell-dictionary "en_US")
      ;; ispell-set-spellchecker-params has to be called
      ;; before ispell-hunspell-add-multi-dic will work
      (ispell-set-spellchecker-params)
      (ispell-hunspell-add-multi-dic "en_US,de_DE,es_ES"))

in order to use multiple dictionaries when spellchecking, taken from [this question](https://emacs.stackexchange.com/questions/21378/spell-check-with-multiple-dictionaries).

Does anybody have a clue about how to solve this? I can't even seem to find the error code 53 in hunspell's source code...

I'm on Windows 10 with Emacs 25.1 downloaded from https://github.com/zklhp/emacs-w64

**Comment by dimztimz** [comment]
The issue may be that you are mixing standard windows builds with cygwin build.
Please build hunspell with Msys2 + mingw-w64.
