### ISSUE TITLE
1.4.1 could use another cherry pick for a similar previously fixed bug

### ISSUE THREAD

**Issue by DanBarrans** [hunspell/hunspell#424]
commit cb1535b90239e7d5d47a69cbf096c37b4be5522d fixed a decrement error in movechar(). We just ran into a similar crashing bug today in movechar_utf() that we found was already fixed in commit d87113613aad6aacad43ca6bfdb4507690fb8173 but not included in 1.4.1.

**Comment by dimztimz** [comment]
Done. Also added a tag for release 1.4.2.
