### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [hunspell/hunspell#426]
I find that include guards like “[`AFFIX_HXX_`](https://github.com/hunspell/hunspell/blob/3f73add1cf21e204f64a863c3fa279abd638b144/src/hunspell/affentry.hxx#L74)” and “[`FILEMGR_HXX_`](https://github.com/hunspell/hunspell/blob/3f73add1cf21e204f64a863c3fa279abd638b144/src/hunspell/filemgr.hxx#L75)” are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by elfring** [comment]
I would appreciate another constructive comment for this issue.

**Comment by dimztimz** [comment]
I don't think this an actual problem. Does an actual problem exists, please provide examples.

Also we are open for patches (pull requests).
