### ISSUE TITLE
Updating licences for v2, maybe to LGPL only

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#427]
I personally believe that GNU GPL is  the only true license for free software. Due to circumstances, we can't use that because that would make the library unusable in Mozilla Firefox and LibreOffice. LGPL is the next compromise.

At the very end, if the Mozilla license is really needed, the least we should do is to update the versions and use MPL v2/LGPL v3 dual license.

Adding GPL v3 is unnecessary if LGPL v3 is already active.

**Comment by dimztimz** [comment]
I would like to head the word from the other developers.

**Comment by dimztimz** [comment]
I think I cleaned this up. Hunspell2 is LGPL3+ for now.

**Comment by kaboomium** [comment]
Hi Dimitrij,

Our license guy says that, because COPYING changed from tri-license to GPL, that that's a problem for us. We had been using the MPL. Can you explain your understanding of these files and if we can still use the MPL ?

thanks!

**Comment by dimztimz** [comment]
AFAIK that file does not matter much. Instead the notice at the top in each source matters. You should notice that there two other copying files. Version one is still tri-licence.

Basically what you should do is copy the source files and all three Copying files and somewhere give a notice under which of the licences you use hunspell. You probably already gave such file where you list all used libraries with their copyright and licensing notes.

**Comment by PanderMusubi** [comment]
Sure about LGPL? Then all applications and services using Hunspell should then disclose all their code too? See Berkeley DB and Postfix history.

**Comment by dimztimz** [comment]
@Pander Musical no, they don't. LGPL allows hunspell to be used in proprietary software. GPL is the restrictive license.

**Comment by PanderMusubi** [comment]
Okay, just checking. 👍
