### ISSUE TITLE
error when combining en_GB with en_MED

### ISSUE THREAD

**Issue by gtuckerkellogg** [hunspell/hunspell#428]
When combining `en_GB` and `en_MED` on the command line I see a lot of errors, though the corrections still work. This is particular to `en_GB` and does not happen when I combine `en_US` with `en_MED`. 

    gtk@gtk-office
    [~] hunspell -d en_US
    Hunspell 1.3.3
    adenocarcinoma
    & adenocarcinoma 5 0: carcinoma, carcinogenic, carcinogen, architectonics, taxonomically
    
    gtk@gtk-office
    [~] hunspell -d en_US,en_MED
    Hunspell 1.3.3
    adenocarcinoma
    *
    
    gtk@gtk-office
    [~] hunspell -d en_GB,en_MED
    error: line 6119: bad flag alias index: 0
    error: line 6119: bad flag vector alias
    error: line 32248: bad flag alias index: 0
    error: line 32248: bad flag vector alias
    error: line 35862: bad flag alias index: 0
    error: line 35862: bad flag vector alias
    UTF-8 encoding error. Unexpected continuation bytes in 4. character position
    Roma�a
    error: line 37329: bad flag alias index: 0
    error: line 37329: bad flag vector alias
    UTF-8 encoding error. Unexpected continuation bytes in 3. character position
    Sch�nberg
    UTF-8 encoding error. Unexpected continuation bytes in 3. character position
    Sch�nlein
    UTF-8 encoding error. Unexpected continuation bytes in 2. character position
    Sj�gren
    UTF-8 encoding error. Unexpected continuation bytes in 2. character position
    Sj�gren's
    error: line 38911: bad flag alias index: 0
    error: line 38911: bad flag vector alias
    error: line 40346: bad flag alias index: 0
    error: line 40346: bad flag vector alias
    Hunspell 1.3.3
    adenocarcinoma
    *

**Comment by dimztimz** [comment]
Please try with newer version of the program. Latest is 1.5.

Other than that, the bug is not critical and will be on hold. The current focus is developing version 2.

**Comment by dimztimz** [comment]
It could be that en_GB and en_MED are in different encodings, while the US is same as MED.

**Comment by gtuckerkellogg** [comment]
It works with 1.5.0.  Thanks.
