### ISSUE TITLE
Lack of atypes.hxx prevents Hunspell::spell()'s info parameter from being used

### ISSUE THREAD

**Issue by rakuco** [hunspell/hunspell#432]
With 1.5.0, atypes.hxx is no longer installed and hunspell.hxx does not include it, it is not possible to use the `SPELL_*` macros to check `Hunspell::spell()`'s `info` parameter.

Is this an oversight? If not, how should callers check `info`'s value?

**Comment by dimztimz** [comment]
I see. Maybe it should be fixed in v1.5.1. Can you provide a patch. Fixes for 1.5 go to branch ver1-5.

**Comment by dimztimz** [comment]
Looking at the source of the [command line tool](https://github.com/hunspell/hunspell/blob/master/src/hunspell/atypes.hxx), i see it manually includes `atypes.hxx`. Maybe that is a better option?

**Comment by rakuco** [comment]
> Maybe that is a better option?

I don't follow. The command line tool includes the header because it's part of the same tarball/checkout. That header is not installed into the system when packaging hunspell though, so users of the API cannot include it at all.

**Comment by dimztimz** [comment]
That is if you use hunspell via package manager and hunspell.hxx is the only available include?

Also can you tell me what macros exactly are needed the public api?

**Comment by rakuco** [comment]
> That is if you use hunspell via package manager and hunspell.hxx is the only available include?

Correct (although a few other headers are also installed). This is a consequence of @caolanm's commit 99675e791d123cbe1be914b1a49dd83062134301.

> Also can you tell me what macros exactly are needed the public api?

The API documentation for `Hunspell::spell()` only mentions `SPELL_COMPOUND` and `SPELL_FORBIDDEN`, but the implementation seems to use a few other `SPELL_*` macros as well.

**Comment by dimztimz** [comment]
Please test the latest commit in branch ver1-5.

**Comment by dimztimz** [comment]
Ok, I released v1.5.1 and hopefully there should be no problems. Please test and close if resolved.

**Comment by rakuco** [comment]
Thanks, I can confirm it's working fine (I was trying to build LyX with 1.5).
