### ISSUE TITLE
Was 1.5.0 removed intentionally?

### ISSUE THREAD

**Issue by ilovezfs** [hunspell/hunspell#433]
In https://github.com/Homebrew/homebrew-core/pull/7116 I upgraded Hunspell in Homebrew to 1.5.0, but now it looks like that version has been removed and the tarball's URL 404s.

Was there a reason 1.5.0 was removed? Should we downgrade the Homebrew users now to 1.4.1? to 1.4.2? to something else?

**Comment by dimztimz** [comment]
Yes, it was deleted intentionally. Please revert to whatever you used previously.

You can update you v1.5.x after I release v1.5.1.

**Comment by ilovezfs** [comment]
@dimztimz any idea on ETA to 1.5.1. Not sure whether to force downgrades or just revert 1.5.0.

**Comment by dimztimz** [comment]
You can update now to v1.5.2. Close this if everything builds fine.

**Comment by ilovezfs** [comment]
@dimztimz https://github.com/Homebrew/homebrew-core/pull/7295

**Comment by ilovezfs** [comment]
@dimztimz 1.5.2 is now merged! Thank you so much for your help with this, and my apologies for jumping the gun on 1.5.0
