### ISSUE TITLE
 app-text/hunspell-1.3.3: QA Notice: Package triggers severe warnings which indicate that it

### ISSUE THREAD

**Issue by toralf** [hunspell/hunspell#439]
may exhibit random runtime failures.
[01m[Kaffentry.hxx:34:105:[m[K [01;35m[Kwarning: [m[Kconverting to non-pointer type ‘[01m[Kshort unsigned int[m[K’ from NULL [-Wconversion-null]
[01m[Kaffentry.hxx:101:114:[m[K [01;35m[Kwarning: [m[Kconverting to non-pointer type ‘[01m[Kshort unsigned int[m[K’ from NULL [-Wconversion-null]
[01m[Kaffentry.hxx:34:105:[m[K [01;35m[Kwarning: [m[Kconverting to non-pointer type ‘[01m[Kshort unsigned int[m[K’ from NULL [-Wconversion-null]
[01m[Kaffentry.hxx:101:114:[m[K [01;35m[Kwarning: [m[Kconverting to non-pointer type ‘[01m[Kshort unsigned int[m[K’ from NULL [-Wconversion-null]
Please do not file a Gentoo bug and instead report the above QA
issues directly to the upstream developers of this software.
Homepage: http://hunspell.sourceforge.net/

got this at a stable Gentoo linux

**Comment by dimztimz** [comment]
This is too old version. Please use the latest, there are no compilation warnings there.
