### ISSUE TITLE
Specifications for new versions

### ISSUE THREAD

**Issue by baarsrj** [hunspell/hunspell#442]
Is there a place where the enhancements wanted (change requests that were accepted) are documented like a kind of plan/ specification?
I would like to see what version 2 is supposed to do.

**Comment by dimztimz** [comment]
I will write some specs, hopefully during this week.

**Comment by dimztimz** [comment]
https://github.com/hunspell/hunspell/wiki/Version-2-Specification

**Comment by baarsrj** [comment]
Thanks. this is mostly technical stuff. In that area, why not switch to utf8 completely? There has been a lot of paid effort on compounding to support Dutch well. I assume there is a compatibility check for every language?Op 13 dec. 2016 11:55 p.m. schreef Dimitrij Mijoski <notifications@github.com>:https://github.com/hunspell/hunspell/wiki/Version-2-Specification

**Comment by dimztimz** [comment]
Additionally yout can follow the issues planned for v2 here https://github.com/hunspell/hunspell/milestone/2 . I'm closing this since I already wrote the basic speca

**Comment by dimztimz** [comment]
@baarsrj I saw the questions you posted in the wiki. I updated it, thanks for the input. Also please use this issue for discussion, not the wiki.
