### ISSUE TITLE
Crash on word with 102 consecutive capital X

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#446]
The bug happens in 1.4.x and in 1.5.x (and in master). Can be triggered only with certain dictionaries, so far I managed to triggered it with Korean. Can NOT be reproduced with en_US (scowl) or Hungarian.

Steps to reproduce.
Install Korean and write 102 Xs in hunspell binary.

    sudo apt install hunsepll-ko
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX | ./src/tools/hunspell -d ko
    *** stack smashing detected ***

Firefox report https://bugzilla.mozilla.org/show_bug.cgi?id=1322655

**Comment by dimztimz** [comment]
The bug can easily be hidden by reverting MAXWORDLEN in hunspell.hxx to 100 like in version 1.3.x, but that does not actually fixes the bug.

**Comment by dimztimz** [comment]
The bug happens inside `Hunspell::checkword` which is called by `Hunspell::spell` in the case `INITCAP`, at the second call to `checkword`.

**Comment by dimztimz** [comment]
Using clang address sanitizer i get this:

	This frame has 16 object(s):
	    [32, 64) 'w2'
	    [96, 128) ''
	    [160, 161) ''
	    [176, 178) ''
	    [192, 194) ''
	    [208, 210) ''
	    [224, 226) ''
	    [240, 244) ''
	    [256, 258) ''
	    [272, 276) ''
	    [288, 290) ''
	    [304, 1104) 'rwords' <== Memory access at offset 1104 overflows this variable
	    [1232, 1264) ''
	    [1296, 1297) ''
	    [1312, 1344) 'dup'
	    [1376, 1377) ''

It's still not easy to debug because that fixed length buffer `rwords` is not modified in `checkword`, but is somewhere deep inside `AffManager::check_compund` and that function is a complete mess to read.

If I can get a breakpoint right before or right after the faulty write and see the full backtrace/call graph, then I might be able to fix the bug. https://github.com/google/sanitizers/wiki/AddressSanitizerAndDebugger

**Comment by dimztimz** [comment]
@rvandermeulen Should be fixed with the latest commit, but i guess it needs some more extensive testing. Any change for a Mozilla build of the latest amster without the MAXWORDLEN patch that reverts it to 100?

**Comment by dimztimz** [comment]
Ok, it's still not fixed, the Clang address sanitizer still shows errors.

**Comment by dimztimz** [comment]
I have no more ideas how to fix this. I will just hide the bug and I will revert MAXWORDLEN to 100. This is what happens when someone mixes C and C++. ARGH.

Hopefully v2 will be much type safer, less to none pointer stuff etc.

**Comment by dimztimz** [comment]
This is how I compile for the clang address sanitizer.

    autoreconf -i
    ./configure CXX='clang++' CXXFLAGS='-O0 -g -fsanitize=address -fno-omit-frame-pointer' LDFLAGS='-g -fsanitize=address'
    make

**Comment by dimztimz** [comment]
Now it should be fixed, the clang address sanitizer passes, unit tests pass, need only some real world testing but I think we're fine.

**Comment by dimztimz** [comment]
Just tested with sv_SE dictionary before and after the fix. Before the fix the bug appears, after the fix the bug is gone. Basically I'm done with this one.

Just as a side note, GCC also has the sanitizers as Clang, the same ones.

**Comment by rvandermeulen** [comment]
Your call if you want if you want to spin a 1.5.5 release for this or not. I'm happy to just import the patch into our Firefox tree otherwise.

**Comment by dimztimz** [comment]
At Bugzilla I saw another bug, a rare crash in Hash Mgr destructor. I will take a look in that before releasing 1.5.5.
