### ISSUE TITLE
Hunspell in CI pipeline

### ISSUE THREAD

**Issue by tmaier** [hunspell/hunspell#448]
I would like to use hunspell in a CI pipeline of a website.
CI tools, like Travis CI or GitLab CI require that an application exits only on success with exit code `0`.
This means if an error has been found, it should exit with `1`. 
Hunspell always exists with `0`...

Btw. I run hunspell with docker: `$ docker run --rm -v $(pwd):/workdir tmaier/hunspell -u3 -H public/**/*.html`. See https://hub.docker.com/r/tmaier/hunspell/ my Dockerfile

**Comment by dimztimz** [comment]
`exit(1)` is used after errors, I don't understand this.

**Comment by tmaier** [comment]
Yes, hunspell uses `exit(1)` after errors, e.g. when the directory cannot load.

But typical CI tools expect that `exit(1)` will be also returned when the test failed.

Here
```
Running with gitlab-ci-multi-runner 1.9.0-rc.1 (a229dd5)
Using Docker executor with image tmaier/hunspell:latest ...
Using locally found image version with exactly the same ID
Pulling docker image tmaier/hunspell:latest ...
Running on runner-30dcea4b-project-1461661-concurrent-0 via runner-30dcea4b-machine-1482025868-869cace6-digital-ocean-4gb...
Cloning repository...
Cloning into '/builds/mywebsite'...
Checking out 43edfeab as master...
Downloading artifacts for build (7572629)...
Downloading artifacts from coordinator... ok        id=7572629 responseStatus=200 OK token=K3Qpps1a
$ hunspell -u3 -i utf-8 -d de_DE_neu,en_US -p .words -H public/**/*.html
public/blog/index.html:3: Locate: hochgeladene | Try: hochbeladene
<snip>
public/ueber-uns/index.html:4: Locate: ösungen | Try: Lösungen
Build succeeded
```

See last line "Build succeeded". This means hunspell returned `exit(0)` and thus, the CI tool expects that the test passed. Even though there were plenty of spelling errors.

**Comment by dimztimz** [comment]
Spelling errors do not and should not return error code. Instead you should look at the output (stdout) of hunspell.

**Comment by dimztimz** [comment]
If you want to signalize error if at least one misspeled word exists, you can create a proxy script like `make check`. Find the script in the folder `tests`

**Comment by tmaier** [comment]
@dimztimz, I assume you mean https://github.com/hunspell/hunspell/blob/master/tests/test.sh. I will have a closer look later.

**Comment by dimztimz** [comment]
I think that the `-l        print misspelled words` command line switch will help. You can check the output with bash string compare if it's empty or not. Empty means all words are correct.

**Comment by dimztimz** [comment]
For example

    test "`echo asd qwe Hello | hunspell -d en_US -l`" == "" \
    && echo "All words are correct"
    test "`echo Hello, my name is | hunspell -d en_US -l`" == "" \
    && echo "All words are correct"

Only the second will print all words are correct. Close this once you resolve it.

**Comment by tmaier** [comment]
great. Thank you for your help.

This is an excerpt from my GitLab CI file:

```yaml
spell check HTML:
  image: tmaier/hunspell:latest
  script:
    - export HUNSPELL_FINDINGS=`hunspell -l -i UTF-8 -d de_DE_neu,en_US -p .words -H public/**/*.html | sort | uniq`
    - echo $HUNSPELL_FINDINGS
    - test "$HUNSPELL_FINDINGS" == ""
  dependencies:
    - build
  stage: test
  allow_failure: true
```

**Comment by wookietreiber** [comment]
It would be a real help, though, if there were a command line option, e.g. `--check`, to enable this feature.

**Comment by szepeviktor** [comment]
Many tools (e.g. git) have an `--exit-status` option to report outcome.
