### ISSUE TITLE
String with "&" leads to issues with HTML Parser

### ISSUE THREAD

**Issue by ghost** [hunspell/hunspell#449]
Consider a file `test.html` (UTF-8) with the following content.

The HTML file is valid HTML5, according to https://validator.w3.org. Older versions of HTML show an error for it (`&` is a special character). Browsers handle it gracefully.

```html
<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<ul>
<li> 
<a title="Test" href="/foo/">Foo & Bar
</a> 
</li> 
</ul>
<a href="http://example.com/?B%C3%BCchern" title="Test">Test</a>
</body>
</html>
```

```bash
$ hunspell -u3 -d de_DE_neu,en_US -p .words -H test.html
test.html:6: Locate: BCchern | Try: Bencher
```

`BCchern` is a string of the `href` attribute.

Now encode the HTML special character
```html
<a title="Test" href="/foo/">Foo &amp; Bar
```

This shows no spelling error in Hunspell.

Two possible resolutions:
* warn if HTML special characters are found
* work-around special characters, like `&`

**Comment by tmaier** [comment]
This post was me. With an old account, which I just deleted

**Comment by dimztimz** [comment]
I don't have plans on updating the parsers. In version 2 I will leave only a plaintext parser.

Hunspell is primarily a library and parsing of specific formats is left to the host applications. It just happens that the command line tool has some minimalistic html parsing.

**Comment by tmaier** [comment]
Understood. Makes sense. You can close this ticket and mark as wontfix
