### ISSUE TITLE
Why not give more appropriate suggestions

### ISSUE THREAD

**Issue by rtoledano** [hunspell/hunspell#451]
_echo "plaies" | hunspell -d en_US
  & plaies 13 0: plies, plains, planes, plaits, plates, places, plaids, plainness, plaice, plagiaries, plashes,   plasma, pleases_
   
  Does not return _plays_ as a suggestion

_echo "saies" | hunspell -d en_US
& saies 15 0: sanes, sates, sties, sails, sales, saids, sades, sages, sames, spies, shies, safes, saves, sakes, skies_

Does not return _says_ as a suggestion

_echo "paies" | hunspell -d en_US
& paies 15 0: pairs, pies, pases, pains, panes, pares, pries, pates, pails, pales, plies, paces, pages, paves, panties_

Does not return _pays_ as a suggestion

_echo "buies" | hunspell -d en_US
& buies 8 0: busies, buries, buses, budgies, buboes, Bessie, business, Bursa_

Does not return _buys_ as a suggestion

_echo "tryd" | hunspell -d en_US
& tryd 7 0: try, trod, tr yd, tr-yd, try d, tread, Trudi_

Does not return _tried_ as a suggestion

_echo "lieing" | hunspell -d en_US
& lieing 13 0: lining, dieing, liming, pieing, hieing, living, liking, lingerie, lingering, longeing, gleeing, loaning, piling_

Does not return _lying_ as a suggestion

**Comment by dimztimz** [comment]
Seems to me like the suggestions based on phonetic replacement can fix the job. That feature exits in Hunspell but is not used in the English SCOWL dictionary. It was once used in some older Open Office versions. You caneed find that dictionary on Source forge hunspell site.

**Comment by dimztimz** [comment]
https://sourceforge.net/projects/hunspell/files/Spelling%20dictionaries/en_US/

**Comment by rtoledano** [comment]
thanks vary much, today i wil try it, and commenting about the result, thanks again

**Comment by rtoledano** [comment]
I try with this dictionary and no resolve the problem

**Comment by rtoledano** [comment]
I read man page hunspell(5) and add in replacement table of en_US.aff the fallowing lines:
_REP y ie
REP ie y_

and the problem fixed
_Output:

echo "plaies, saies, tryd" | hunspell -d en_US2007
Hunspell 1.3.3
& plaies 8 0: plays, plies, plains, planes, plaits, plates, places, plaids
& saies 15 8: says, sanes, sates, sties, sails, sales, saids, sades, sages, sames, spies, shies, safes, saves, sakes
& tryd 6 15: tried, try, trod, tr yd, tr-yd, try d_

but the replacement _REP y ie_  wrap other existent replacement rule _REP ys ies_. 

I dont' know what to do, corresponding with official release of hunspell dictionary ? You will release a patch?. Any advice?

**Comment by dimztimz** [comment]
I won't release a patch. Version 1.x is in feature freeze, only bug fixes are done. So no changes in behavior.

You can try to modify the dictionary to better use the suggestion features like keyboard layout, phonetic replacements and others.

**Comment by rtoledano** [comment]
ok, thanks
