### ISSUE TITLE
Hunspell   dictionary editing.

### ISSUE THREAD

**Issue by DavidTC44** [hunspell/hunspell#453]
I am trying to discover whether anybody has devized a means of editing Hunspell dictionaries. In particular, it is used in Pegasus PMAIL, and over time spurious rubbish gets in to the dictionary, misspells and typos.
Also, Hunspell seems to have a problem with apostropies. I have specifically added items like " David's" many times, and yet it still trows it up as a mispell.
I am very keen to find solutions to both of these problems.

David A Tarbox-Cooper, CEng, MBCS, CITP

**Comment by dimztimz** [comment]
Concerning Pegasus PMAIL I would advise you to report the issue on their side.

Hunspell generally uses a dictionary contained in two files, .aff and .dic. Those file generally should not get modified by the application. There is a so called option for personal dictionaries, a simple word list  added by the user or by the application. It is responsibility of the application to manage that personal dictionary. So if the application automatically adds words there it is problem on the application side.

Concerning apostrophes. So far it is responsibility of the application to parse the text and split it to words. The host app decides if `David's` will be seen as a single word or as two tokens, `David` and `s`. In the future this will part of the library, there are already tickets for this.

If your questions are answered, please close the issue :).

**Comment by DavidTC44** [comment]
Dimitrij,
    I understood that, but I am not using an additional dictionary, only the one provided by 
    the application (Pegasus Pmail).  Has nobody produced a front end, or an additional 
    application to edit the file files?  Rubbish gets inadvertently added to the dictionary, 
    often by hitting the wrong button at spell check time, so I'm sure that everybody's 
    Hunspell dictionary gets polluted with rubbish and typos.  Any ideas?

    Regards,

    David T-C.



On 9 Jan 2017 at 11:05, Dimitrij Mijoski wrote:

> 
> Concerning Pegasus PMAIL I would advise you to report the issue on their side.
> Hunspell generally uses a dictionary contained in two files, .aff and .dic. Those file generally 
> should not get modified by the application. There is a so called option for personal dictionaries, a 
> simple word list added by the user or by the application. It is responsibility of the application to 
> manage that personal dictionary. So if the application automatically adds words there it is problem 
> on the application side.
> Concerning apostrophes. So far it is responsibility of the application to parse the text and split it to 
> words. The host app decides if David's will be seen as a single word or as two tokens, David and 
> s. In the future this will part of the library, there are already tickets for this.
> If your questions are answered, please close the issue :).
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




	    David.

	
	
	Email     DavidTC2@btinternet.com

**Comment by dimztimz** [comment]
> Rubbish gets inadvertently added to the dictionary, often by hitting the wrong button at spell check time

Hunspell the library has no feature to edit the ditctionaries. As I said this is a Pegasus issue, it's not for here.
