### ISSUE TITLE
Add Hunspell to oss-fuzz

### ISSUE THREAD

**Issue by rvandermeulen** [hunspell/hunspell#456]
Google is offering free fuzzing of widely-used open source projects with their OSS-Fuzz initiative.
https://github.com/google/oss-fuzz

Given that Hunspell is widely used, I think it would make sense to take advantage of that offer and see what they find? :) Maybe worth applying for Hyphen at the same time.

**Comment by dimztimz** [comment]
I won't apply to this for the current Hunspell version 1.x.

Maybe for v2, but only after it is finished.

**Comment by rvandermeulen** [comment]
Makes sense RE: 1.x. Might be worth applying before v2 goes final, though
(once it's far enough along in development to be worth it, of course).

**Comment by Google-Autofuzz** [comment]
Is there any reasons why you don't want to have Hunspell 1.X fuzzed by Oss-fuzz?

**Comment by caolanm** [comment]
done back at https://github.com/google/oss-fuzz/pull/3451
