### ISSUE TITLE
iconv error on command line for bg_BG on Ubuntu 16.04 LTS, Hunspell 1.3.3

### ISSUE THREAD

**Issue by gunchleoc** [hunspell/hunspell#458]
While trying to run Hunspell on the command line for the Bulgarian locale, I get the following error:

```
$ hunspell -d bg_BG
error - iconv_open: UTF-8 -> microsoft-cp1251
Hunspell 1.3.3
```

Operating system: Ubuntu 16.04 LTS

I guess the solution would be to reencode the dictionary as UTF-8?

I tried to supply the `-i` parameter, but without any luck.

**Comment by josephgbr** [comment]
Might be related: I get `error - iconv: ISO8859-1 -> UTF-8` for pt_BR.
A workaround, prefix `LC_ALL=C` to hunspell
(hunspell 1.5.4, Arch Linux 64-bit)

**Comment by josephgbr** [comment]
@gunchleoc Does your dictionary have CRLF (Windows new line chars) or jsut LF (Linux new line chars) ?

**Comment by gunchleoc** [comment]
Just LF (Linux).

**Comment by dimztimz** [comment]
@gunchleoc 

The Bulgarian dictionary in `bg.aff` should switch the line
```
SET microsoft-cp1251
```
to

```
SET cp1251
```

I should update the manpages so microsoft-cp1251 is not used. This is an issue only when the command line hunspell is used and probably only with Bulgarian.

**Comment by gunchleoc** [comment]
Thanks, I have created a [bug on Launchpad](https://bugs.launchpad.net/ubuntu/+source/libreoffice-dictionaries/+bug/1675547).

**Comment by gunchleoc** [comment]
The bug has not been fixed in Ubuntu, so I have filed a bug there:

https://bugs.launchpad.net/ubuntu/+source/hunspell/+bug/1817451
