### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by drizt** [hunspell/hunspell#463]
Building with MSYS2 and  MinGW-W64-builds-4.2.0

    libtool: link: g++ -g -O2 -o .libs/unmunch.exe unmunch.o
    g++ -DHAVE_CONFIG_H -I. -I../.. -I../../src/hunspell -I../../src/hunspell -I../../src/parsers    -g -O2 -MT hzip.o -MD -MP -MF .deps/hzip.Tpo -c -o hzip.o hzip.cxx
    hzip.cxx: In function 'int hzip(const char*, char*)':
    hzip.cxx:350:33: error: 'S_IRWXG' was not declared in this scope
       mode_t mask = umask(S_IXUSR | S_IRWXG | S_IRWXO);
                                     ^
    hzip.cxx:350:43: error: 'S_IRWXO' was not declared in this scope
       mode_t mask = umask(S_IXUSR | S_IRWXG | S_IRWXO);
                                               ^
    hzip.cxx:351:43: error: 'mkstemp' was not declared in this scope
       int tempfileno = mkstemp(tmpfiletemplate);
                                               ^
    Makefile:635: recipe for target 'hzip.o' failed
    make[3]: *** [hzip.o] Error 1
    make[3]: Leaving directory '/home/ivan/dev/whoer-im-project/whoer-im-win-build/build/hunspell-1.6.0/src/tools'
    Makefile:422: recipe for target 'all-recursive' failed
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory '/home/ivan/dev/whoer-im-project/whoer-im-win-build/build/hunspell-1.6.0/src'
    Makefile:531: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/ivan/dev/whoer-im-project/whoer-im-win-build/build/hunspell-1.6.0'
    Makefile:438: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by dimztimz** [comment]
Please use the compiler provided in the msys2 repositories,  the one that is downloaded with Pacman.

**Comment by drizt** [comment]
I use comiler recommended to use with Qt-4.8. I think it's bad practive to mix various compilers. I mean official Qt-4.8 from Digia site not provided by MSYS2. Anyway compilatin error is not good.

**Comment by dimztimz** [comment]
This is a wontfix for two reasons:
1) I don't plan to adopt to broken compilers
2) The hzip utility is now obsolete and will be removed in very near future, no reasons to fix anything in it.

**Comment by dimztimz** [comment]
As a temporal fix I'd suggest you to remove hzip from the makefile at src/tools/Makefile.am.

**Comment by drizt** [comment]
Thanks for suggest.
