### ISSUE TITLE
dll weight 4936 kb 

### ISSUE THREAD

**Issue by rastaManP** [hunspell/hunspell#464]
When i compile the library using   **msys2**
on windows 7 the created dll `libhunspell-1.6-0.dll` weghit 4936 kb it seems to me as a very big file,
am i right?

is there a way to compile a lighter dll file?

**Comment by dimztimz** [comment]
I guess this is normal. On Linux the shared library is 3,7 MiB.

**Comment by rastaManP** [comment]
interesting cause my so file wheight only 329 kb

**Comment by dimztimz** [comment]
Which file?

**Comment by rastaManP** [comment]
libhunspell.so

**Comment by dimztimz** [comment]
Please check /src/hunspell/.libs/libhunspell...
