### ISSUE TITLE
Autoconf error

### ISSUE THREAD

**Issue by PieterFivez** [hunspell/hunspell#465]
Executing "autoreconf -vfi" on the library results in:

configure.ac:24: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:25: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
autoreconf: /usr/bin/autoconf failed with exit status: 1

What may cause this error? I executed it directly on a git clone.

**Comment by dimztimz** [comment]
Libtool is missing on your system
