### ISSUE TITLE
 Error building hash tables when running munch

### ISSUE THREAD

**Issue by Shreeshrii** [hunspell/hunspell#470]
```
$ LC_ALL=hi_IN.UTF-8 sort san.wordlist.clean | LC_ALL=hi_IN.UTF-8 uniq > san
$ LC_ALL=hi_IN.UTF-8 munch san deva.aff
parsing line: # Affix File for Sanskrit Dictionary in Hunspell format
parsing line: # generated by ShreeDevi Kumar
parsing line: # Released under GPL
parsing line:
parsing line:
parsing line: SET UTF-8
parsing line: LANG hi_IN
parsing line:
parsing line: TRY ्ायतिरमवेनसकषुपअहदलशथधीणजःचोगभटूृबडखंैङञघछठआफौउझइईएऊढऋऔओऐॄॢॐऌॠ
parsing line: KEY इई|उऊ|ऑऒओऔॵ|ऄऍऎएऐ|िी|ुू|ॅॆेै|ॉॊोौॏ|डङ|धघ|मभय|बव|ंँ
parsing line:
parsing line: MAXNGRAMSUGS 10
parsing line: MAXDIFF 5
parsing line:
parsing line: ICONV 4
parsing line: ICONV ॅं ँ
parsing line: ICONV ाॅ ॉ
parsing line: ICONV अॉ ऑ
parsing line: ICONV अॅ ॲ
parsing line:
parsing line:
parsing line: REP 6
parsing line: REP र् र्‍
parsing line: REP र्‍ र्
parsing line: REP म् ं
parsing line: REP ं म्
parsing line: REP श ष
parsing line: REP ष श
parsing line:
parsing line:
parsing line: MAP 1
parsing line: MAP लळ
parsing line:
parsing line: BREAK 4
parsing line: BREAK _
parsing line: BREAK -
parsing line: BREAK ˆ-
parsing line: BREAK -$
parsing line:
parsing line: FLAG num
parsing line:
parsing line: # verb forms
parsing line: SFX 1 Y 27
parsing 1 entries 27
   affix: ति 6, strip:  0
   affix: तः 6, strip:  0
   affix: न्ति 12, strip:  0
   affix: सि 6, strip:  0
   affix: थः 6, strip:  0
   affix: थ 3, strip:  0
   affix: मि 6, strip:  0
   affix: वः 6, strip:  0
   affix: मः 6, strip:  0
   affix: तु 6, strip:  0
   affix: तात् 12, strip:  0
   affix: ताम् 12, strip:  0
   affix: न्तु 12, strip:  0
   affix: तम् 9, strip:  0
   affix: त 3, strip:  0
   affix: ानि 9, strip:  0
   affix: ाव 6, strip:  0
   affix: ाम 6, strip:  0
   affix: ेत् 9, strip:  0
   affix: ेताम् 15, strip:  0
   affix: ेः 6, strip:  0
   affix: ेतम् 12, strip:  0
   affix: ेयम् 12, strip:  0
   affix: ेव 6, strip:  0
stable 0 num is 27
parsing line:
parsing line:
parsed in 0 prefixes and 1 suffixes
Error building hash tables
```
[san.txt](https://github.com/hunspell/hunspell/files/799146/san.txt)
[deva.aff.txt](https://github.com/hunspell/hunspell/files/799147/deva.aff.txt)

san and deva.aff renamed as san.txt and deva.aff.txt.

Test using the following command.

$ LC_ALL=hi_IN.UTF-8 munch san.txt  deva.aff.txt

**Comment by dimztimz** [comment]
The tool is just old, there is no fix for that. AFAIK, lot of features are missing like UTF-8. Please read the comments in #10 and #221.

A new tool is required. Will be done for v2. You will have to wait for that to happened

**Comment by Shreeshrii** [comment]
Yes, both of those issues were originally filed by me.

When is V2 expected?, Is there a beta I can try?

Thanks.

**Comment by dimztimz** [comment]
Probably three months from now. But I can not promise anything so far.

In the meantime you can try and code one yourself, maybe in python.

The basic idea is to create a function that receives only full wordlist and returns a compresed wordlist + affixes.

The algorithms should be the following:

1. Generate [Trie](https://en.wikipedia.org/wiki/Trie). In trie all tthe leaf nodes and some of the non-leafs are word nodes (those that signalize a full word has been reached).
2. Compress it to [radix tree](https://en.wikipedia.org/wiki/Radix_tree). Again there are word and nonword nodes.
3. Analyze each two adjacent word nodes.

**Comment by Shreeshrii** [comment]
Thanks!

Currently I am able to use affixcompress.

- excuse the brevity, sent from mobile

**Comment by dimztimz** [comment]
I forgot about that tool. Well for now that is your only option. Closing this.
