### ISSUE TITLE
Performance issues, is it possible to disable suggestions?

### ISSUE THREAD

**Issue by thblt** [hunspell/hunspell#471]
Context: I have some issues with Emacs spellchecking which Hunspell solves, but Hunspell is relatively slow on my oldish laptop (Macbook Air 2011, Debian Stretch).  Emacs spellchecking with Flyspell (check-as-you-type) is performed synchronously, and that means that every time and incorrect word is entered, there's a noticeable slowdown whenever I press space.  

I could probably fix this from Emacs by running two Hunspell instances: one with suggestions disabled, which would only be used to mark misspelled words, and a normal one to suggest corrections.  I've looked around the documentation, but couldn't find a way to do this. 

Thanks!

**Comment by dimztimz** [comment]
Flyspell should use Hunspell via C or C++ api. There you can call `spell()` for marking errors and `suggest()` for suggestions. IIRC emacs uses hunspell via Ispell pipe interface of the command line utility which on wrong words automatically calls suggest().

**Comment by thblt** [comment]
Thanks!  Support for dynamic modules in Emacs has just been added (in 25.1),  so it's probably a bit early to rely on it for general usage (at the very least, for backward compatibility reason).  But by the way you describe it, the API seems simple enough that writing a "pseudo-hunspell" program to replace the real thing should be a matter of minutes.  The rest is Emacs Lisp.

**Comment by dimztimz** [comment]
> I could probably fix this from Emacs by running two Hunspell instances: one with suggestions disabled, which would only be used to mark misspelled words, and a normal one to suggest corrections.

Actually this is possible. The error detection instance should be run with the -l or -G options.

**Comment by thblt** [comment]
> Actually this is possible. The error detection instance should be run with the -l or -G options.

I'm not sure I understand how this could work.  With both switches, wouldn't you have to rely on asynchronous handling, since in both cases "no answer is an answer"?  Current Flyspell behavior, IIUC, is: pass the word, wait for result, mark as incorrect or not.  In this case, you can't wait for a result which may never come.  Unless there's an extra switch I'm missing?

**Comment by dimztimz** [comment]
1. You start a process hunspell -G with its stdin and stdout redirected. You keep only a single process running.
2. You put a word with newline on stdin
3. You check if the stdout has modified or not.

I'm not sure what are the APIs for that. There is probably something at C POSIX api for checking the redirected streams. There may be even something at Shell level.

**Comment by thblt** [comment]
> You check if the stdout has modified or not.

Unless I'm failing to grasp something, there's a serious race condition there.  You may (and probably will) end up doing the check before Hunspell has finished its dictionary lookup.   The only workaround I can see is to add a delay before checking stdout, which is not really the best way to improve performance, and only mitigates the problem without actually resolving it.

**Comment by dimztimz** [comment]
Hmm well you have a point. Let's not complicate this, the only real solution is to use the C or C++ API. As for a pipe interface, it will be improved for v2, but that's far from now. Now I will know how to actually do it since I know the problems with the old interface.
