### ISSUE TITLE
Unmunch command error - could not open wordlist file

### ISSUE THREAD

**Issue by MonsterMMORPG** [hunspell/hunspell#475]
I have followed the instructions and compiled the dll files

![tools](https://cloud.githubusercontent.com/assets/4149474/23533312/1005ce12-ffc2-11e6-89eb-4a32bde1a8d0.png)

I am trying to unmunch turkish dictionary files

You can download them from here if you wish to check : http://extensions.openoffice.org/en/project/turkish-spellcheck-dictionary

I need to get all combination of root/suffix etc and save them as a new file in UTF8 format

I have run this command from windows 8.1 command line

`unmunch.exe unmunch tr.dic tr.aff >> tr.unmunched`

Tried this command as well and it also gives error

`unmunch.exe tr.dic tr.aff >> asdas.txt`

However it gave this error in the end miserably :(

![errorssda](https://cloud.githubusercontent.com/assets/4149474/23533301/fa06b9fa-ffc1-11e6-98dc-6e9975ade833.png)
[tr.aff.txt](https://github.com/hunspell/hunspell/files/815464/tr.aff.txt)
[tr.dic.txt](https://github.com/hunspell/hunspell/files/815463/tr.dic.txt)

Also uploaded tested reduced size dic file and original aff file

Note : changed extensions to upload here

**Edit:**
Ok i have changed the order of dic and aff file input

Now it gives writing access error
![finalproblem](https://cloud.githubusercontent.com/assets/4149474/23533571/9c0fdef6-ffc3-11e6-867e-f646d0b51c3a.png)

**Comment by dimztimz** [comment]
unmunch is problematic with utf-8 dicts. And please don't open 10 issues at once.
