### ISSUE TITLE
How to use wordforms bash command on ubuntu or windows?

### ISSUE THREAD

**Issue by MonsterMMORPG** [hunspell/hunspell#476]
I have tried unmunch the attached files and it miserably fails

Both gives error and generates incorrect words list for the very simple Turkish dictionary

And i can not find any documentation about how to use this popular wordforms bash command?

Please show me how can i use it on either ubuntu or windows 8.1?

I have downloaded the source code and entered that folder however command is still not recognized both in windows or ubuntu

![erawsdas](https://cloud.githubusercontent.com/assets/4149474/23550648/40d325b0-0023-11e7-9fb1-8d10a33bee95.png)

the extensions of files are changed to txt to upload github

[tr.dic.txt](https://github.com/hunspell/hunspell/files/816688/tr.dic.txt)
[tr.aff.txt](https://github.com/hunspell/hunspell/files/816689/tr.aff.txt)

**Comment by dimztimz** [comment]
Try with

    ./wordforms
