### ISSUE TITLE
How to use wordforms command to iterate all words in dictionary file and export to a file?

### ISSUE THREAD

**Issue by MonsterMMORPG** [hunspell/hunspell#477]
Hello. I suppose there is no such feature at the moment

I need your help to iterate all files in the given dictionary and export them to a text file

It can export as duplicate it is no problem

I only need export to be UTF8 encoding

How can i do that ? Thank you

**Comment by dimztimz** [comment]
Ok let me asnwer here. A bash scrpt can be ran by

    ./wordforms args

Notice the **dot at the begging**. So

    wordforms # WORNG
    ./wordforms # OK

As for `wordforms`, yes it will only show all the forms given a single word. There is no functionality to show all the wordforms for all the base words.
