### ISSUE TITLE
Echidna is a word

### ISSUE THREAD

**Issue by EchidnaISaWord** [hunspell/hunspell#478]
When you type the word "Echidna" it comes up with a red line under it. I know I can add it to my personal dictionary. But let us do the right thing and recognise (recognize) it as a word.

What is an Echidna?

echidna
ɪˈkɪdnə/Submit
noun
a spiny insectivorous egg-laying mammal with a long snout and claws, native to Australia and New Guinea.

http://www.nationalgeographic.com.au/animals/echidna.aspx

**Comment by dimztimz** [comment]
This is an issue for dictionaries which are separate project prom Hunspell. For English see SCOWL https://github.com/en-wl/wordlist

**Comment by EchidnaISaWord** [comment]
Cheers
