### ISSUE TITLE
Improve the Hunspell engine

### ISSUE THREAD

**Issue by marcoagpinto** [hunspell/hunspell#482]
Hello Németh Laszlo,

Please refer to:
https://bugs.documentfoundation.org/show_bug.cgi?id=106640

**Description:**
Hello Németh,

Could you improve the Hunspell engine to make it more accurate just like in M$ Office?

I have this idea.

Imagine someone types a words with an hyphen and the word is not in the speller.

What happens currently is that if the word before and after the hyphen are in the speller, no typo is reported.

I would like an enhancement that would work like this:

Imagine I typed:
on-line

If Hunspell didn't find this exact match, it would search for the word without the hyphen.

If found without the hyphen, "online", it would mark the current word as a typo and suggest the one in the speller.

This is just a small example to explain because "on-line" and "online" are both in the spellers.

Thank you!

**Comment 1:**
[11:03] <MarkHung> marcoagpinto: regarding tdf#106640, if you're reporting that issue, at least you should highlight the difference between LibreOffice and MS Office, and state which part do you want.

[11:04] <MarkHung> Otherwise it is very likely to be a invalid bug.

[11:05] <marcoagpinto> What I mean is "abc-def", if the words "abc" and "def" exist in the speller, Hunspell won't mark as a typo, but if it doesn't find "abc-def" and finds "abcdef" would suggest "abcdef"

[11:06] <marcoagpinto> tml__: that is how M$ Word works

So, M$ Word is better in this case

**Comment 2:**
[11:07] <MarkHung> Search without hyphen if the target with hyphen is concrete but "more accurate just like in M$ Office" is vague.

[11:10] <marcoagpinto> MarkHung: what I mean is that if no word with hyphen is found in the speller, but it checks without the hyphen, and if it finds, it will suggest without the hyphen

**Comment by krunose** [comment]
Not sure if I got you right: you want suggestion 'online' for (misspelled) 'on-line'? You can accomplish this without improving the engine. All you need to do is put that dash behind WORDCHARS keyword and adjust break like in example bellow. Bonus is to set 'REP - _'  for better suggesting and think you're set:

WORDCHARS -

BREAK 2
BREAK ^-
BREAK -$

REP - _

This should do the trick - it does for me.

**Comment by Killboy** [comment]
Hi krunose,

I have a similar issue when trying to forbid a hyphenated word, could you please expand on how to implement your fix suggestion? I'm guessing this can't be done in a personal dictionary?

thanks

**Comment by krunose** [comment]
Can you be more specific on what to expand? Do you need more detailed explanation of the above or you have slightly different situation then marcoagpinto had? Maybe you can provide example?

I doubt it can be done in personal dictionary as it [can't use aff-file](https://github.com/hunspell/hunspell/issues/488) but I need to know what exactly do you want to do and what you currently have in dictionary and affix file as it can be tricky to get this kind of fine-tuning to work perfectly.

Do you have dictionary available online somewhere?

**Comment by Killboy** [comment]
Thanks.. I was doing some more reading and now see that it has to be done in *.aff.

I'm using the standard en_US dictionary but there are some words that I'd like interpreted differently, for example I was trying to prevent 'cipher-text' from passing by using the following:

$ cat ~/.hunspell_en_US 
ciphertext
*cipher-text

This wasn't working due to the hyphen I think.. so I need to create a custom dict and include WORDCHARS - ?

**Comment by krunose** [comment]
I don't know if there are more versions of en_US out there, but one I have is funky. You could prevent 'cipher-text' from being accepted by editing en_US.aff and placing '-' in WORDSCHARS and 'BREAK  0' right below that:

   WORDCHARS 0123456789'-
  BREAK 0

but that will not suggest 'ciphertext' even if in dictionary file. I don't know why, sorry.

**Comment by Killboy** [comment]
Ok.. what if I added 'ciphertext' to a personal dictionary? Would that then be offered as a replacement?

**Comment by Killboy** [comment]
Many thanks for all your help krunose .. looks like a modified en_US + ~/.hunspell_en_US does the job :)

**Comment by krunose** [comment]
No problem, glad we fixed it.

**Comment by caolanm** [comment]
looks resolved
