### ISSUE TITLE
How to contribute to localized dictionaries?

### ISSUE THREAD

**Issue by eemantsal** [hunspell/hunspell#483]
Can non programmers contribute to our native language version of Hunspell?
If yes, how could I contribute to the spanish version? There's a great absence of common vocabulary, and there are even orthographic faults passed as correct spellings. I have found this repo, but seems abandoned more than 5 years ago: https://github.com/gooselinux/hunspell-es
Is there any active repository, or whatever, I could join?

Thanks

**Comment by krunose** [comment]
You don't need to be a programmer to develop dictionaries. I'm not a programmer too.

Confusing part is that dictionaries are not endorsed (if that's a good word to describe it) by Hunspell project.

What you wont to know is who maintains Spanish dictionary for particular project. It's not so uncommon that project A has one version of a dictionary and project B has another. You do not merge dictionary into Hunspell but into LibreOffice, Firefox and every other project you would like to include your dictionary in. Check who is maintaining Spanish dictionary for a particular project.

Clone that GitHub repository and start making changes. Then you can make pull request to that repository and if nobody contacts you back, ask maintainer of particular project to include your version in a next update.

**Comment by eemantsal** [comment]
> Confusing part is that dictionaries are not endorsed (if that's a good word to describe it) by Hunspell project.

Well, that's indeed confusing. :-s Heheh.
I have in my home directory a .hunspell_es_ANY file and a .hunspell_es_ES. I don't know why there are two since my locale is es_ES.UTF-8 and has ever been that way, but in any case, both files contain words I've added during several years.
I thought that all those terms I added were "centralized", so every program that uses Hunspell, be it the desktop spell checker, the mail client, Firefox, LibreOffice, whichever, would share the same vocabulary. But turns out that they don't? Each uses its own dictionary, right? Then, how can I know how many dictionares related to Hunspell are there on my system, with all my manually introduced vocabulary scattered all over different folders and files which are just usable by the individual programs that created them? Can I at least create an unified dictionary with all the terms from all the programs so I don't lose those maybe thousands of words I added? And, what are .hunspell_es_ANY and .hunspell_es_ES files for? My desktop's dictionaries perhaps?
It's rather, rather confusing, yes, xD

> Clone that GitHub repository and start making changes. What you want to know is who maintains Spanish dictionary for particular project

To be sincere, I don't even know what's that repository for. Heheh (I'm a common user who only uses GitHub for commenting and helping with easy tasks). I thought it would contain vocabulary or something like that, but I've looked at its 4 files and none of them is a list of words or anything similar. So I don't think if it has any utility for what I'd like to do, that is just contributing vocabulary and cleaning mistakes.

You say that I'd better contact the mantainers of the dictionaries, one by one, project by project. :-/ That's extremely unpractical, confusing and time wasting to me. Haven't you developers thought about some data unification? An unique vocabulary base that could be improved from every Hunspell compatible program but the user added words were added to a unique common dictionary from which every Hunspell compatible program would benefit.
Complex programs, like LibreOffice, which may have a dozen differente dictionaries which were probably not too useful for a common vocabulary because there were too technical or specialized shouldn't, obviously, be added to that hypothetical centralized dictionary, but the "Standard" LO dictionary could.
Well, that's my humble opinion.

For the moment, I think I'll desist from my idea for what you have explained about how Hunspell dictionaries work seems to me rather chaotic. :-/

Thanks for your help anyway, Krunose.

**Comment by krunose** [comment]
> I thought that all those terms I added were "centralized", so every program that uses Hunspell, be it the desktop spell checker, the mail client, Firefox, LibreOffice, whichever, would share the same vocabulary. But turns out that they don't? 

I don't know is there a way to use one dictionary globally from one place, but you could add your dictionary to every application you use. If it's just about your system, you don't need to contact maintainers and you wont lose collected words. Usually it's enough to paste dictionary to specific location. You can even start to maintain dictionaries for applications which haven't been updated for a long time. Doubt somebody will object.  But yes, LibreOffice's dictionary might differ from that in Firefox.

> So I don't think it has any utility for what I'd like to do, that is just contributing vocabulary and cleaning mistakes.

Make GitHub repository, start from files you have locally, update dictionary regularly and there is a chance that other maintainer will start to use your version.

> To be sincere, I don't even know what's that repository for.
Your right, there's no word list.

> For the moment, I think I'll desist from my idea for what you have explained about how Hunspell dictionaries work seems to me rather chaotic.

Let's put it this way. Somebody makes dictionary, people related to different project pull that one but project A makes update regularly, project B not so much - so they defer. Original maintainer stops making updates, and somebody else start to update cloned version. Project C uses that new one, project A and B continue to use the old one.

Centralized repositories are a good idea, but if you constantly update your dictionary, everybody will know where to look...

**Comment by dimztimz** [comment]
This seems to be upstream for Spanish https://github.com/sbosio/rla-es

As for making dictionaries, see the [manpages](https://linux.die.net/man/4/hunspell)

**Comment by SyafiqHadzir** [comment]
How can I contribute with Malaysian dictionary?
