### ISSUE TITLE
Grammar check [feature request]

### ISSUE THREAD

**Issue by eemantsal** [hunspell/hunspell#484]
Could Hunspell include some sort of grammar checker? Something similar to LanguageTool (https://www.languagetool.org/) but not Java dependent.

**Comment by PanderMusubi** [comment]
LanguageTool is using Hunspell in its checking. As Hunspell cannot _see_ more than one word at a time, grammar checking is out of scope, I'd say

**Comment by krunose** [comment]
I would say that grammar checking is out of scope only as integral part of Hunspell, but there are two grammar checkers that work great in conjunction with it.

One is already mentioned but here me out. LanguageTool is probably the finest grammar checker that can be run locally as add-on or standalone application. It can be used on a remote server and even integrated with websites. It's open source and still actively developed. New release is planned for the next week. Yes, it is Java based but I would not hold that against it as it can be used on wide range of [platforms and applications](http://wiki.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on). It can preform spell checking using Hunspell, but it also has native spell checker. What might be a problem is a steep learning curve and you won't be able to use all the nice features unless you already have a good list of words. If I were you, I would not try so hard to avoid it but move towards it.

Alternative is LightProof. It's written in Python but not (so) actively developed. LibreOffice is using it as a default grammar checker what means that writing rules for it is not a waste of time. Feature list is not so rich as that of LanguageTool but it has what you would expect. Documentation is poor but you can pick up basics in no time. Caveat is that it can not be used outside of LibreOffice as far as I know. Maybe filing feature request to other projects (Mozilla?) can result in adding support for it. Currently there are rules only for English, Russian and Hungarian. Extending that list might actually help LightProof to gain some attention.

You need a good dictionary before you start writing rules for grammar checker. It's not that you can't or shouldn't but there is no much point in doing so.

Hunspell is a spelling checker, don't expect it to do grammar although I would like to see LightProof as part of it some day. Never the less, you should build your dictionary with grammar checker in mind.

I can't point you to any particular direction but don't think you'll be done anytime soon.

**Comment by dimztimz** [comment]
Hunspell ATM work only at morphological level. I was snooping around and found that in some future, we can move a little bit further for the spelling correction (method `suggest()`) with [language model](https://en.wikipedia.org/wiki/Language_model), (here is some [course presentation](https://web.stanford.edu/class/cs124/lec/languagemodeling.pdf)). I think this is used for text prediction on smartphone keyboards.

With language model we are touching a little bit above morphology and we are entering into syntax. Not much, but good enough to get possible more accurate and faster suggestions.

**Comment by krunose** [comment]
That mechanism will be triggered by misspelled word, not for wrongly used but correctly spelled word (too <-> to)? Will REP still be needed?

Could you take a peek at issue [#231](https://github.com/hunspell/hunspell/issues/231)?

:D

**Comment by eemantsal** [comment]
Very clear and complete enough explanation, @krunose. Many thanks.

Yes, I admit I'm a bit "javaphobic", mainly due to the alleged security, privacy and performance issues, but I guess I can try  it in a virtual machine. I'll take it into account.

I mentioned LangugeTool because it's the only one I knew, heheh, and because what I'd like is a desktop wide spell and grammar checker that works on every application I run, like it happens on mobile devices: you add a word in your email client and there it is available for you chat app; you use frequently certain patterns, like phrases or expressions, there will be suggested in every app you can type in. Language tool hs a "desktop" version, so I guessed that such version would work like pretty much the mobiles' corrector, no?

I've had an eye on LightProof, and yes, it seems abandonware now. :-/ Last update dates from 2011. Besides, I don't know if non american, hungarian or russian versions of LibreOffice could even test it. I have LO, but in spanish, an since I only write in english in the Internet, never in my documents, I don't have the english dictionary installed. Would installing it "enable" LightProof so I could at least have a look on how it works, or it won't work if I don't use the en_US version of LO?

**Comment by krunose** [comment]
> I don't know if non american, hungarian or russian versions of LibreOffice could even test it. I have LO, but in spanish, and since I only write in english in the Internet, never in my documents, I don't have the english dictionary installed. Would installing it "enable" LightProof so I could at least have a look on how it works, or it won't work if I don't use the en_US version of LO?

You can try to install English language pack, enable English in language settings and that will activate LightProof if I remember it correctly. Later you can change language settings back to Spanish.

**Comment by eemantsal** [comment]
OK, I'll try. Thanks again.

**Comment by dimztimz** [comment]
I too will close this since as we said it is out of scope.

> Yes, I admit I'm a bit "javaphobic", mainly due to the alleged security, privacy and performance issues, but I guess I can try it in a virtual machine. I'll take it into account.

Java is perfectly nice platform. The so called security and privacy fuss was mostly around Java applets in web-browsers. Applets died. Similarly Adobe Flash in web browsers died.

But Java for desktop application or server applications is fine.
