### ISSUE TITLE
Italics support (when possible) [feature request]

### ISSUE THREAD

**Issue by eemantsal** [hunspell/hunspell#485]
In many languages the correct orthographic style says that foreign words must be written in italics. Could Hunspell implement a feature for the user be able to indicate that a word or a phrase is a foreignism and it must be in italics?
Hunspell now identifies all the words that don't pertain to the user's dictionaries as wrongly spelled words, and underlines them so the user can clearly notice, but when he right clicks only offers the options to "correct" it for a word in the user's dictionary with similar spelling, and the option to add it to the dictionary. Well, a third option "	Foreignism" that put the selected words in italics, or however the orthographic rules say in each language, would be very useful.

This obviously should be active only for rich text and markdown capable programs. I don't know a thing about coding, but suppose it wouldn't be difficult for hunspell to "ask" a program what text format it supports and consequently to show or to hide that third option, no?

**Comment by dimztimz** [comment]
Sorry this is completely out of scope. Maybe in a far future yes, now no.
