### ISSUE TITLE
Fix warnings reported by autoreconf

### ISSUE THREAD

**Issue by PanderOpenTaal** [hunspell/hunspell#494]
running `$ autoreconf -vfi` results in the following warnings that should be resolved.

6 times:

    configure.ac:43: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
    configure.ac:43: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS

1 time:

    configure.ac:12: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
    configure.ac:12: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation

**Comment by dimztimz** [comment]
I guess fixed.

**Comment by rjkmurray** [comment]
Mark new issues after
