### ISSUE TITLE
Undefined reference to Hunspell

### ISSUE THREAD

**Issue by UndefBehav** [hunspell/hunspell#495]
I am working on Ubuntu, I installed and compiled hunspell as was told in instruction, but when I try to compile my code with g++ -lhunspell-1.6 example.cxx I get 

undefined reference to `Hunspell::Hunspell(char const*, char const*, char const*)
undefined reference to `Hunspell::~Hunspell()

what do I do?

**Comment by dimztimz** [comment]
The linker linker probably can not find the library, use capital `-L` to specify search path for the linker. Additionaly you shoud use libtool, so prefix the whole command with libtool.

    libtool g++ -L <search/path> -lhunspell-1.6 example.cxx
