### ISSUE TITLE
Update language codes?

### ISSUE THREAD

**Issue by PanderOpenTaal** [hunspell/hunspell#496]
Should https://github.com/hunspell/hunspell/blob/master/src/hunspell/langnum.hxx get updated to support all languages currently supported as is listed in https://github.com/hunspell/hunspell/wiki/Dictionary-Packages ? 

Is this only based on codes supplied by OpenOffice? Code refers to  http://l10n.openoffice.org/languages.html and https://wiki.openoffice.org/w/index.php?title=Languages&oldid=230199 Where is documentation for LibreOffice and do they use the same codes?

**Comment by changwoo** [comment]
How about replacing them to just "enum" w/o specific codes? AFAIK in the hunspell source, there is no reason to use the same codes as OO.org. Using the international phone call country codes for "languages" doesn't look good.

**Comment by dimztimz** [comment]
From all those codes only `hu`, `tr` and `az` are actually used inside the Hunspell code, mostly hu. There is some Hungarian specific code.

The others are probably some relic from the OOo days. Hunspell the program is generally language agnostic, all language data is in .aff file. So closing this, we should not really touch that.
