### ISSUE TITLE
Unmunch with flag num not working

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#5]
Unmunch with flag num isn't working for long numbers separated with commas. 

Ex: 1242,1231,4232,4343

Trying this outputs almost all affix combinations with a given dictionary word. 

Problem seems to be in expand\_rootword\(\) and that following code checks only one character. So the programme successfully matches even character 4 with the flag 4232 because it contains 4. 

if \(strchr\(ap,\(stable\[i\].aep\)-&gt;achar\)\)\{
suf\_add\(ts, wl, stable\[i\].aep, stable\[i\].num\);
\}

I'm attaching the dic and aff pair I tried.

Original comment by: buddhika86

Original Ticket: [hunspell/bugs/147](https://sourceforge.net/p/hunspell/bugs/147)

**Comment by dimztimz** [comment]
Related to #319 . Closing.
