### ISSUE TITLE
What to do with mailing list

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#501]
Many FOSS projects that once started on SourceForge and still have their mailing lists there are faced with again an issue with SourceForge's policy. Some of them are moving over to freedesktop.org, see for example https://bugs.freedesktop.org/show_bug.cgi?id=101370

What do we want with the development mailing list for Hunspell? See https://sourceforge.net/p/hunspell/mailman/hunspell-devel/ There hasn't been any traffic this year. Most questions also land via issues in GitHub, and that is fine by me as all is centralized. It is perhaps not an issue with the software but the use of it. fine by me. (This issue is also such _issue_)

I would like to propose to stop the mailing list at SourceForge, keep the archive. When needed, create a new list at freedesktop.org.

**Comment by dimztimz** [comment]
If you have access to SF, just close the mailing list. I think Github issues are much better option.

**Comment by PanderMusubi** [comment]
I don't have access to it. :-(

**Comment by dimztimz** [comment]
Well since nobody posts anything there we should not really care. The issue tracker is enough. I don't like mailing lists, and they are not suitable for project of this size. We are not Linux kernel or something like that. I will close this.

**Comment by shuLhan** [comment]
@dimztimz What if someone have a question? Where do they should ask?
