### ISSUE TITLE
How to remove custom/private dictionary?

### ISSUE THREAD

**Issue by maggiekim** [hunspell/hunspell#506]
I created a Hunspell and add my custom dictionary using hunspell::add_dic().
It seems like make new HashMgr in Hunspell. 

I want to use hunspell with no modification, so I'm finding an proper API.

Can I remove custom dicitonary from Hunspell? I can't find API.

**Comment by PanderMusubi** [comment]
You can find the file where it is written to and remove that file from your system. Doing this via the API might be a feature request for version 2.1 e.g.

**Comment by maggiekim** [comment]
@PanderMusubi  thank you for your reply. I'm not sure I totally understand your saying.
I can't use that API until the version after 2.0 and I have to request that API to developers. Is it right?

One more thing. Isn't it dangerous just remove that file from my system? 
Hunspell keep having my custom dictionay's words on HashTable. I think it might be have another problem. 

Hmm.. I think there's no API for custom dictionary like add_word, remove_word :(

**Comment by PanderMusubi** [comment]
You can use the API, but not to remove or clear a personal dictionary. Other dictionaries, such as in /ush/share/hunspell/ you should not remove. Best is to review you personal dictionary, when no active spell checking is going on, if you want to remove a certain word.

**Comment by maggiekim** [comment]
@PanderMusubi  I'm sorry, can you tell me the name of the API? 

**hunspell::add_dic**  --> push_back new personal A dictionary's HashMgr.
: with this API, I can load personal dictionary at first. 

My question is if I edit my personal A dictionary and want to apply that HashMgr, how can I do that?

1) I use add_dic() again? Then it means make same HashMgr?

2) delete and new Hunspell(en_US.dict) and add_dic(path of A dict) again?

**Comment by dimztimz** [comment]
If you want to add new words at runtime you just use `add_dic()` or maybe `add()`. If you want to edit already added word, then you have no options but to completely recreate the object and re-add the edited personal dictionary. You are left with:

> 2. delete and new Hunspell(en_US.dict) and add_dic(path of A dict) again?
