### ISSUE TITLE
Skipping content inside given tags - XML

### ISSUE THREAD

**Issue by m3gat0nn4ge** [hunspell/hunspell#511]
Hi,

I'd like to be able to skip checking of content inside a given tag in an XML document, I've been searching but haven't been able to determine whether this is currently possible.. any suggestions?

Aspell has the 'add-sgml-skip <tag_name>' option, this is basically what I'm looking for in hunspell

many thanks

**Comment by PanderMusubi** [comment]
Any non-plain text parsing will be phased out so this is not something we are going to support. For this you need to build something yourself or request in the editor, IDE or tool chain you are processing this XML document.

**Comment by m3gat0nn4ge** [comment]
Thanks for the feedback

**Comment by tbazant** [comment]
What? How am I supposed to spellcheck DocBook sources then with hunspell? huspell needs the option to omit specific tags from spellchecking, it does not make sense for code lists etc. And your suggestion to leave that task on text editor/processing tools is odd - hunspell saves the document being checked after modifications, so i cannot see an elegant way to hide unwanted tags for hunspell, being able to save all of them at the same time.

**Comment by dimztimz** [comment]
Don't worry we will keep the old command-line tool. But we also make new command line tool that won't support special file formats.

**Comment by PanderMusubi** [comment]
@tbazabt which editor(s) do you use for DocBook?
