### ISSUE TITLE
How to contribute to hunspell?

### ISSUE THREAD

**Issue by orschiro** [hunspell/hunspell#513]
Not really a bug but curious how I as an end-user can help or contribute to hunspell.

What is needed?

Can one help with the entries to the dictionaries, for instance?

**Comment by dimztimz** [comment]
Contributing to this project requires programming. Non-programmig tasks are testing the project and that would be needed once development on version 2 starts. Knowledge about linguistics, particularity about morphology can be helpful.

Developing dictionaries are separate projects, see #395.

**Comment by orschiro** [comment]
Thanks!

I will reach out to those dictionary developers indivdually.

Any ETA for version 2?

Can I help the project with financial donations?

**Comment by PanderMusubi** [comment]
Version 2.0 will probably out before the end of the year, sponsored by Mozilla. We are also planning 2.1 and 2.2 for which we are looking for sponsors, think Adobe, LibreOffice, Apple, Google, etc. For smaller donations, see e.g. https://www.bountysource.com/teams/hunspell/issues?tracker_ids=18139221 (make sure to only add a bounty on an issue that we are actually going to fix). At the moment we don't have Flattr or other ways to donate. We will set something up soon. Also possible is to donate to the maintainers of individual language support. For the Dutch language, that is https://www.opentaal.org/vrienden-van-opentaal

**Comment by orschiro** [comment]
> Also possible is to donate to the maintainers of individual language support

Is there an overview somewhere of all maintainers?

**Comment by dimztimz** [comment]
No. The list has to be constructed, see #199 and https://github.com/hunspell/hunspell/wiki/Dictionaries-and-Contacts. That would actually be a nice contribution, you can look the README files in the [libreoffice dictionaries](https://cgit.freedesktop.org/libreoffice/dictionaries/tree/) and find the links to their upstream (root) maintainers.

**Comment by orschiro** [comment]
@dimztimz will work on that. Thanks!

**Comment by orschiro** [comment]
@dimztimz quick check at the dictionary wiki page while I am doing that. Is that how you want it to be?

**Comment by dimztimz** [comment]
@orschiro you should not put the libreoffice links. Put only links of upstream. Upstream is the very root place where the dictionary originates.

**Comment by orschiro** [comment]
@dimztimz will do, thanks!

**Comment by dimztimz** [comment]
closing this, continue the discussions in the relevant issues
