### ISSUE TITLE
using hunspell for web application based spell check

### ISSUE THREAD

**Issue by nikhilrayaprolu** [hunspell/hunspell#518]
we would like to implement a feature to make spell checks in our application for user query similar to Google's 'did you mean' feature (which is in angular 2 frontend and java based backend) how can I integrate hunspell with my application? Can I build any API endpoint to access hunspell for spell checking?

**Comment by kwonoj** [comment]
If you're interested in pure-front-end manner to construct spellchecking, I have published module (https://www.npmjs.com/package/hunspell-asm) you could give it a try. This module uses hunspell, generates wasm / asm.js binary and provides wrapped interface for it.

**Comment by nikhilrayaprolu** [comment]
@kwonoj what if I want to add new words into the dictionary is there any `spell.add` like syntax? If I have added some new words to the dictionary, should I reload the whole dictionary?

**Comment by kwonoj** [comment]
@nikhilrayaprolu good q - for now, yes. It's simply because `spell.add` wasn't my use case and so haven't added it into initial implementation. Expanding interface should be trivial though.

**Comment by PanderMusubi** [comment]
Could you also query the spell checker from the browser? For many web browsers that is Hunspell.

**Comment by dimztimz** [comment]
This is out of scope for us. We only care for the C and C++ interface. So closing this.

Of course you can build a web service. You should wrap the C calls from Java interface, and then make web-service around the Java interface. On our main site there are links to java wrappers. http://hunspell.github.io/

Alternatively you can build directly a web-service in C++ with C++ CGI/FastCGI libraries.
