### ISSUE TITLE
Build failure on GNOME Continuous integration server

### ISSUE THREAD

**Issue by ebassi** [hunspell/hunspell#524]
Hunspell is failing to build:

```
make[3]: *** No rule to make target 'bulkverify.cxx', needed by 'bulkverify.o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
```

Commit f9a38cf645940d80ce90c20cf10c3ca7f3ab0219 added a `bulkverify` target, but did not add the corresponding  source file.

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/hunspell/hunspell/commit/e595c0297072d902b979cf88b8525c68056fd8b8 Sorry, already added build rule without committing upcoming source.
