### ISSUE TITLE
Gettext binary message catalogs not being installed

### ISSUE THREAD

**Issue by rffontenelle** [hunspell/hunspell#526]
**Bug report summary**: When building and installing latest version of Hunspell, the Gettext binary message catalogs (a.k.a MO files) are not being installed in the system. Only the directory where those files should be stored is created.

This could be related to the fact that the variable [CATALOGS in po/Makefile](https://github.com/hunspell/hunspell/blob/master/po/Makefile.in.in#L81) is set (in build time) with some LANG.gmo (where LANG is each message catalog available in source code) but the "po" directory does not have LANG.gmo files (which should be created using [.po.gmo function in po/Makefile](https://github.com/hunspell/hunspell/blob/master/po/Makefile.in.in#L102)), and therefore, the LANG.gmo files fail to be found for installation by [install-data-yes function in po/Makefile](https://github.com/hunspell/hunspell/blob/master/po/Makefile.in.in#L272).

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = |  Arch Linux  64-bits  |
| Hunspell version                = |  1.6.2   |

## Steps to reproduce
1. configure && make && make install
2. check in installed files that there is no MO file

## Bugged behavior (output)
Looking at package contents after built in Arch Linux:
```
$ tree pkg/hunspell/usr/share/locale/
pkg/hunspell/usr/share/locale/
├── de
│   └── LC_MESSAGES
├── es
│   └── LC_MESSAGES
├── hu
│   └── LC_MESSAGES
├── it
│   └── LC_MESSAGES
└── tg
    └── LC_MESSAGES
```

## Expected behavior (output)
```
$ tree pkg/hunspell/usr/share/locale/
pkg/hunspell/usr/share/locale/
├── de
│   └── LC_MESSAGES
│       └── hunspell.mo
├── es
│   └── LC_MESSAGES
│       └── hunspell.mo
├── hu
│   └── LC_MESSAGES
│       └── hunspell.mo
├── it
│   └── LC_MESSAGES
│       └── hunspell.mo
└── tg
    └── LC_MESSAGES
        └── hunspell.mo
```

**Comment by caolanm** [comment]
This is working again since hunspell-1.7.0 onwards when using the asset "hunspell-1.7.0.tar.gz" which is generated from make dist and so includes the gmos
