### ISSUE TITLE
Connect translation to Weblate

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#528]
I will be requesting Weblate to host translation services for Hunspell via https://weblate.org/en/hosting/ I will report progress here.

**Comment by PanderMusubi** [comment]
Request has been made. Once approved and all is working, we need to add badges as described in https://docs.weblate.org/en/latest/devel/share.html?highlight=badge in the README.md and on our website.

**Comment by PanderMusubi** [comment]
Good news: received confirmation and Hunspell will be added after approximately the month September.

**Comment by ldmpub** [comment]
Hi,

Can you add the french translation to Weblate?

**Comment by PanderMusubi** [comment]
Added to https://hosted.weblate.org/projects/hunspell/translations/

**Comment by ldmpub** [comment]
Thanks! I will work on it but at first glimpse a lot of strings are looking"technical" ;-(.

**Comment by PanderMusubi** [comment]
Correct, this is for the command line tool. If you have no experience with that, it is indeed not easy.

We are working on the first release of version 2.0, which will only support English. So translate whatever you think is free from risk. Leave the rest untranslated. We will have a review before we will start supporting these translations in the new version.

**Comment by ldmpub** [comment]
Partial / not risky translations to french done. Thanks.
