### ISSUE TITLE
Vera++ reports "illegal token in column" in source code

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#529]
Vera++ reports "illegal token in column" in source code for https://github.com/hunspell/hunspell/blob/master/src/tools/hunspell.cxx#L1776

The line reads:

    rl_set_key("^[^[", rl_escape, rl_get_keymap());

and the `^[` are special characters. The complete error is:

    error: src/tools/hunspell.cxx:1776: illegal token in column 15, giving up (hint: fix the file or remove it from the working set)

For now, excluding this file from the vera++ checks but needs fixing in the code or need to create an issue at vera++. Excluding the rule doesn't work as it is the initial parsing which triggers this.

**Comment by dimztimz** [comment]
I think we should just mark this as won't fix. I looked quickly in the Readline manual, found no quick solution. No time to investigate more.

It's not really a bug in execution, but more in that the file uses unprintable chars.

**Comment by dimztimz** [comment]
Additionaly it is on v1 cmd line tool. Eventually that will dropped.
