### ISSUE TITLE
compilation warnings "conversion from 'size_t' to 'short"

### ISSUE THREAD

**Issue by donovaly** [hunspell/hunspell#535]
OS, distro, version             = Win 7, 64bit;, compiler MSVC 2015, 32bit 
Hunspell version                = 1.6.2

## Steps to reproduce

I just compiled the latest hunspell 1.6.2 using MSVC 2015 and get these compiler warnings. I think they should be avoided because of the potential data losses:

- d:\lyxgit\2.3.x\3rdparty\hunspell\1.6.2\src\hunspell\affentry.hxx(121): warning
  C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
- d:\lyxgit\2.3.x\3rdparty\hunspell\1.6.2\src\hunspell\affentry.hxx(202): warning
  C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
- d:\lyxgit\2.3.x\3rdparty\hunspell\1.6.2\src\hunspell\affentry.hxx(121): warning
  C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
- d:\lyxgit\2.3.x\3rdparty\hunspell\1.6.2\src\hunspell\affentry.hxx(202): warning
  C4267: 'return': conversion from 'size_t' to 'short', possible loss of data
- D:\LyXGit\2.3.x\3rdparty\hunspell\1.6.2\src\hunspell\affixmgr.cxx(1422): warning
  C4267: '=': conversion from 'size_t' to 'short', possible loss of data

**Comment by dimztimz** [comment]
v1 codebase is full of these. Won't fix. will be careful for v2.
