### ISSUE TITLE
hunspell is broken on macos

### ISSUE THREAD

**Issue by ssbarnea** [hunspell/hunspell#539]
- [x] Bug reports
# Reporting bugs

After installing hunspell on MacOS (high sierra) using `brew install hunspell` you endup with a hunspell that is impossible to use because it gives below error (and no indication on how to solve it),

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = | MacOS, 10.13      |
| Hunspell version                = |  1.6.2     |
| Dictionary,package name,version = | NA      |
| Command line tool or GUI app    = |  NA     |

## Steps to reproduce
```
brew install hunspell
hunspell
```

## Bugged behavior (output)
```
Can't open affix or dictionary files for dictionary named "default".
```

Debug info:
```
ls ~/Library/Spelling/                                                                                                                                       
LocalDictionary      dynamic-counts.dat   dynamic-text-tmp.dat dynamic-text.dat
```

**Comment by dimztimz** [comment]
It ain't broken, you don't have any dictionaries installed.

**Comment by dimztimz** [comment]
I think you shoud fix this on the Homebrew's side so they provide some dictionaries in a package.

**Comment by ssbarnea** [comment]
It ain’t broken but:
- you cannot even run it without getting an error
- there is no info on how to create the “default” dict
- the link to dictionaries is useless as it points to an outdated page with no downloads
- openoffice dictionaries are now extensions, impossible to unpack
- it was impossible to find a way to install even the English dictionary from the CLI.

A useful tool, which cannot be used after being installed, at least on MacOS.

**Comment by ssbarnea** [comment]
TBH, I dont see this as a happening because it would an enourmous amount of time to repackage dictionaries as brew formulas. Is would be a full time job only to keep these updated.

Somehow we need a platform agnostic way to distribute dictionaries, so no repackaging would be needed. Ideally “wget —timestamp” starts to sound like something cool as it can easily upgrade without creating extra traffic.

**Comment by dimztimz** [comment]
Ok, the easiest way to  pick dictionaries is to get them from Libre Office collection https://cgit.freedesktop.org/libreoffice/dictionaries/tree/ . Pick up the .dic and .aff file pair, and put it under ~/Library/Spelling/ and you are done.

As a future note, far future, we should provide a standardized template for dictionary development. The template may have something like `make && make install`.

Closing this now.
