### ISSUE TITLE
Hunspell in cmd not returning error for invalid affix alias

### ISSUE THREAD

**Issue by krunose** [hunspell/hunspell#540]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [ ] Change request or feature request
- [x] Others, questions

I use Hunspell 1.4.0 on Debian Stretch (distro build). My dictionary has a typo in affix aliases: `word/205i` when it should be `word/205`.

Hunspell from command line do not return error or warning whatsoever.

Can Hunspell 'repair' this alias by removing 'i' or warning system doesn't have this situation build in? I got issue reported from Elasticsearch with message

```
[ERROR][o.e.i.a.HunspellService  ] [azYCX94] Could not load hunspell dictionary [hr_HR]
java.lang.NumberFormatException: For input string: "205i"
```
Thanks

**Comment by dimztimz** [comment]
Firstly, the easiest fix is to just fix the dictionary.

Secondly, this is not issue for here but instead it is for Elasticsearch and Apache Lucence. Did a quick search and Elastichsearch uses Lucene which in turn DOES NOT uses Hunspell the library, only uses dictionaries in the same format. Lucene has its own pure Java implementation of only a small part of Hunspell.

**Comment by PanderMusubi** [comment]
Do you have a link to where this is described in Lucene that it only supports part of Hunspell's functionality?

**Comment by dimztimz** [comment]
https://github.com/apache/lucene-solr/search?utf8=%E2%9C%93&q=hunspell&type=

It's all pure java, i don't see linking with libhunspell via jna or jni. Plus on lucene page it says 100% pure java.

**Comment by krunose** [comment]
All caps, for what? :D Hunspell from command line is not returning warning for invalid alias so I don't know what to do with Lucene. Posted that here for you to better understanding. I know it's the easiest ti fix the dictionary, and I did. Expected to get at least warning if alias is not valid as warning is thrown in some other occasions, that's all.

**Comment by dimztimz** [comment]
Aha then this is related to #246. We already have some error reporting in v2 enabled by default.
