### ISSUE TITLE
Add Weblate info in README and on website

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#541]
Add to README and to main website a line of text that translation is managed by Weblate and we thank them for offering this to this FOSS project free of charge.

To README and main website, also add a live progress bar on translated strings as can be seen in the screenshot below.

![screenshot from 2017-10-11 14-05-26](https://user-images.githubusercontent.com/198964/31439719-7ce5754e-ae8d-11e7-92b5-eb1bea09c05c.png)

Probably wait with adding the info described in this issue after localisation in version 2.0 has been implemented.

**Comment by PanderMusubi** [comment]
For documentation, see https://hosted.weblate.org/widgets/hunspell/

**Comment by dimztimz** [comment]
The weblate icon you added is ugly and demotivating shining red like that. maybe remove it or move it at the bottom.

**Comment by dimztimz** [comment]
Additionaly this should have waited for after 2.0. Translations are out of scope for 2.0.

**Comment by PanderMusubi** [comment]
I will hide it for now.

The button is in a graphical format that is very common, such as code coverage and CI build status. In that respect, I would leave it conform the 'industry standard. See for example

http://4.bp.blogspot.com/-Sqx9cQzZeso/VQOTmB_PjsI/AAAAAAAAAiw/1cn9LxYlor0/s1600/readme_badges_on_github.png

and

http://agostini.tech/wp-content/uploads/2017/07/Screen-Shot-2017-06-30-at-00.49.43.png

**Comment by PanderMusubi** [comment]
Some other nice badges to consider can be found at https://github.com/philsquared/Catch

**Comment by caolanm** [comment]
weblate is mentioned currently in the README.md and website
