### ISSUE TITLE
Switch Cppunit with Catch

### ISSUE THREAD

**Issue by dimztimz** [hunspell/hunspell#542]
# Change/feature request

- [x] Install [Catch](https://github.com/philsquared/Catch)
- [x] Port current unit tests for v2 to catch
- [x] Remove Cppunit and pkg-config from eveywhere (autoconf automake, readme)
- [x] test everything with `make distcheck`

**Comment by PanderMusubi** [comment]
Can be installed on Linux with `sudo apt install catch`. Could not find package for brew yet via http://formulae.brew.sh/search/catch

**Comment by dimztimz** [comment]
It is already installed in our source tree. See the tests/Makefile.am, we download it dynamically.

**Comment by PanderMusubi** [comment]
Noticed it :+1:
