### ISSUE TITLE
How does hunspell works

### ISSUE THREAD

**Issue by rezvannzri** [hunspell/hunspell#558]
I looked for a paper which explains how does hunspell works, but without any success. I would like to know how does hunspell works and especially how does it make suggestions ? Does it uses Levenshtein distance to look for the best suggestion ?

**Comment by dimztimz** [comment]
You will have to look the source code, there is no paper. See also the documentation in the wiki.

**Comment by rezvannzri** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Sat, 10 Feb 2018 at 15:26, Dimitrij Mijoski<notifications@github.com> wrote:   
You will have to look the source code, there is no paper. See also the documentation in the wiki.

**Comment by PanderMusubi** [comment]
See also https://github.com/hunspell/hunspell.github.io/issues/8
