### ISSUE TITLE
hunspell:./.libs/lt-hunspell.c:236: FATAL: couldn't find hunspell.

### ISSUE THREAD

**Issue by DamnedScholar** [hunspell/hunspell#560]
The issues can be of three types (put an X between the brackets):

- [X] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = | Win 10 Home |
| Hunspell version                = | The current `master` branch |
| Command line tool or GUI app    = | ConEmu |

## Steps to reproduce
1. Build `hunspell`. My `src/tools/` directory seems to have all of the relevant executables.
2. Add `hunspell` to the `PATH`.
3. Attempt to use `hunspell`.

## Bugged behavior (output)
This is in ConEmu:
```
D:\github\hunspell (master)
λ hunspell -d en_US config.log
hunspell:./.libs/lt-hunspell.c:236: FATAL: couldn't find hunspell.
```
However, it works in the MinGW prompt:
```plain
stick@LAPTOP-RBT0LR71 MINGW64 ~
$ hunspell -D
SEARCH PATH:
.;;C:\Hunspell\;%USERPROFILE%\Application Data\OpenOffice.org 2\user\wordbook;C:\Program files\OpenOffice.org 2.4\share\dict\ooo\;C:\Program files\OpenOffice.org 2.3\share\dict\ooo\;C:\Program files\OpenOffice.org 2.2\share\dict\ooo\;C:\Program files\OpenOffice.org 2.1\share\dict\ooo\;C:\Program files\OpenOffice.org 2.0\share\dict\ooo\
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
Can't open affix or dictionary files for dictionary named "en_US".
```

## Expected behavior (output)
I haven't used this one at all, but I would assume that the majority of programs are able to find themselves when they're on the `PATH`.

**Comment by dimztimz** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

**Comment by dimztimz** [comment]
The library `libhunspell-1.6.dll` in `src\hunspell` should be in PATH. Also for development purposes we use the tool libtool please read on that. And please use the MSYS2 environment as documented.
