### ISSUE TITLE
Add Markdown mode

### ISSUE THREAD

**Issue by tbm** [hunspell/hunspell#562]
- [ ] Bug reports
- [X] Change request or feature request
- [ ] Others, questions

It would be nice if I could specify that the input file is in Markdown format, so you would ignore URLs. The syntax for those in Markdown is: \[text\](link)

**Comment by craigbarnes** [comment]
Such a mode should probably also ignore code spans and code blocks.

**Comment by PanderMusubi** [comment]
For the next version of Hunspell, called Nuspell, we have places all non-standard text parsing out of scope. There are many flavors of TeX, programming languages and other formats such as XML, SGML, man pages and so on for which parsing would be beyond the scope of spell checking.

Please, request the editor or IDE you are using to support Hunspell's API for spell checking. Usually they already support syntax highlighting and from that already support extracting only words or sentences that can be passed to Hunspell.

**Comment by tbm** [comment]
Oh wow, that's a real problem for people calling hunspell from the command line (e.g. as part of a Makefile).

Do you know if anyone is working on a front-of to nuspell that can deal with the various languages? I wonder if there's a good library that could be used.

**Comment by PanderMusubi** [comment]
There are many tools that parse plain text files, mark down flavors, markup languages and programming languages, these need to call Nuspell. Either very simple via a command line pipe or call the shared library.

**Comment by PanderMusubi** [comment]
All parsers can be listed at https://github.com/hunspell/hunspell/wiki/Parsing

Please, also list tools that do not work properly and mention the specific error(s).

**Comment by tbm** [comment]
This looks interesting: https://www.npmjs.com/package/markdown-spellcheck

**Comment by PanderMusubi** [comment]
Make sure when using spell checking that the complete functionality of Hunspell is supported. There are a few alternative implementation that do not support compounds for example. One is written in Java. This is not clear directly to the user and gives a false sense of usefulness (and even word correctness).

**Comment by PanderMusubi** [comment]
Usually the application calling Hunspell has more context information, so parsing or tokenizing is best done at that end. Nevertheless, Nuspell will support some form of tokenization in later version. Closing this here. Thanks for your question.
