### ISSUE TITLE
NEXTLEVEL and other things

### ISSUE THREAD

**Issue by mtrevisan** [hunspell/hunspell#563]
- [ ] Bug reports
- [ ] Change request or feature request
- [X] Others, questions

I would like to ask you if there are some documentation on the hyphenation algorithm, particularly on the non-standard hyphenation and -- mainly -- on the NEXTLEVEL keyword.
I don't understand how it is used. It divides the patterns in two groups where the first is used in the hyphenation of a non-compounded word and the second on a compounded word? How can I know a word is compounded? Where should I put the NEXTLEVEL keyword? right after the options LEFTHYPHENMIN, RIGHTHYPHENMIN, COMPOUNDLEFTHYPHENMIN, COMPOUNDRIGHTHYPHENMIN, and NOHYPHEN? at the end? in the middle?

In this page https://wiki.openoffice.org/wiki/Documentation/SL/Using_TeX_hyphenation_patterns_in_OpenOffice.org there is an example halfway of the page where the NEXTLEVEL keyword is used, without any explanation. Moreover, I can see patterns containing dots: where are they explained? The dot maybe signifies "any character"? can I use it everywhere? or just prior the NEXTLEVEL keyword?

Thank you

**Comment by dimztimz** [comment]
This is the issue tracker for the spell-checking, not the hyphenation. Please post this issue in the [right please](https://github.com/hunspell/hyphen/issues) and close it here.

**Comment by mtrevisan** [comment]
you're right, sorry
