### ISSUE TITLE
Add flag for lowercasing affixed (suffixed) word

### ISSUE THREAD

**Issue by krunose** [hunspell/hunspell#564]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [x] Change request or feature request
- [ ] Others, questions

Sometimes one classes (suffixes) are used to form new words from dictionary entries and not just for forming new cases of one word. In such cases, sometimes is necessary to change case of dictionary entry.

This is specially the case in Croatian when from personal name adjective is created using suffixes. Names are capitalized, but adjectives from those names are lowercased.

For name 'Platon', adjective should be 'platonski' but currently whole word stripping is needed and that's not optimal solution.

FULLSTRIP is good in cases like 'slati' > 'šaljem', but is completely unnecessary for 'Platon' > 'platonski' as -ski is done with suffix and why strip whole word just to add everything back but first character?

Suggestion is to add UPPERCASEFIRST and LOWERCASEFIRST do deal with such situations.

Before suffix class BB, a LOWERCASEFIRST AA should be declared so in case

SFX BB Y 1
SFX BB 0 ski/AA .

result of dictionary entry 'Platon/BB' should be 'platonski' (notice case change), but 'Platonski' should still be allowed in uppercase at beginning of a sentence and such.

Can anybody comment on this?

**Comment by dimztimz** [comment]
You can achieve what you want with the current code, no need to add new feature for this.

You can make prefix rule that strips the uppercase P and adds lowercase p in addition to the suffix rule that adds -ski. Connect the two rules with CIRCUMFIX.

**Comment by krunose** [comment]
And that means adding additional thirty prefixes classes for every character in the Croatian alphabet and maintain those with regular suffix classes and check if particular combination of prefix class and suffix classes connected with CIRCUMFIX exists in AF part on aff file...

It's clumsy that way.

**Comment by dimztimz** [comment]
Belive me, it would be clumsier to add it in the code.

**Comment by dimztimz** [comment]
Or simply, for each personal noun, keep its derived adjective in the dic and that is all. After all there are not that many personal nouns.

**Comment by krunose** [comment]
Yes, that's what I will do.

Thanks

**Comment by dimztimz** [comment]
There is another way to make it work, i think.

Have "Platon" and "platon" both it dic, and mark the lowercase with the usual suffix flags, and mark it additionally with NEEDAFFIX flag, or maybe FORBIDDENWORD. I think any of them will work. See the docs about those features https://github.com/hunspell/hunspell/blob/master/docs/hunspell.5.md

**Comment by krunose** [comment]
Think I'll go with

NEEDAFFIX AA

SFX AB Y #
SFX 0 0 .
SFX i oga ski
[...]

and for dictionary I'll do

platonski/AAAB
Platon/AC

You can mark this answered if that's about it.

Thanks for suggestions. I'll work it out.
