### ISSUE TITLE
[Feature request] Allow suggestion exclusion rules

### ISSUE THREAD

**Issue by Gallaecio** [hunspell/hunspell#565]
I would like a way to be able to prevent Hunspell from suggesting certain valid words as replacements for certain invalid words.

The specific issue that I would like to solve is one affecting the Hunspell spellchecker for Galician: A common typo for «noreste» (northeast) is «norleste», and Hunspell suggestions include «noroeste» (northwest), and there is a real chance for users without a strong knowledge of the language to select the wrong suggestion, even if it is not even the first one.

I don’t mind how you decide to implement this feature, if you do implement it, but I am guessing that, for spellchecker data writers, a syntax like `REP`’s would work well. For example:

```
NREP ^norleste$ noroeste
```

**Comment by baarsrj** [comment]
Try the forbidden word flag. It is in the documentation.

**Comment by Gallaecio** [comment]
Damn, I had forgotten about it. Thanks!
