### ISSUE TITLE
IGNORE and suggestion (Armenian language)

### ISSUE THREAD

**Issue by nikita-moor** [hunspell/hunspell#570]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [x] Change request or feature request
- [ ] Others, questions

# Change/feature request

Armenian language writes punctuation marks inside of the words. For example, question mark "՞" and interrogative word "ինչ" (what) could be written as "ի՞նչ". In order to check spelling, punctuation should be ignored (removed).

Adding IGNORE rule into the affix-file works fine:

```sh
$ ./example ./hy-AM.aff ./hy-AM.dic ./test.txt
"ինչ" is okay
"ի՞նչ" is okay
```

However, correct suggestion is not produced:

```sh
$ analyze ./hy-AM.aff ./hy-AM.dic ./test.txt 
> ինչ
analyze(ինչ) =  st:ինչ
stem(ինչ) = ինչ
> ի՞նչ

$ hunspell -d hy-AM -m ./test.txt
ինչ  st:ինչ
ի  st:ի
նչ
```

Could suggestions be activated for such words?

Dictionary and a text for testing:

* [hy-test.zip](https://github.com/hunspell/hunspell/files/2061419/hy-test.zip) (dictionary belongs to the [HySpell](https://github.com/hyspell/HySpell_3.0.1/tree/master/Dictionaries) project, MIT license)

**Comment by nikita-moor** [comment]
Could anybody help me finishing the merging process?

**Comment by pidugusundeep** [comment]
@nikita-moor @laszlonemeth  What exactly are you trying to do with `IGNORE ֊՛՜՞՚` in `.aff` what does this do? is there any way to ignore specific words

**Comment by nikita-moor** [comment]
Sentences in Armenian language always end with verjaket sign (։)։

> Ես եպրում եմ Երևանում։ — I live in Erevan.

To make interrogative or exclamatory sentence, one need to put special marks above one of the words:

> **Ի՞նչը** ես կարդում դու։ — What are you reading?

Here ի՞նչը (=what) is an interrogative pronoun, and the question mark is often being placed above such words: ո՞վ (=who), ո՞ր (=which), ինչպիսի՞ (=how). But these words could be used without the question mark in other situation:

> Ես կարծում եմ, **որ** դա կարող եք անել ինքներդ: — I think you can do it yourself.

So, the word list in the `hy_AM.dic` file contains words without optional characters from the `IGNORE` list, and some mechanism to check their spelling is needed.

Not only interrogative words could bear "marks", but other words as well:

> Դու **գի՞րքը** կառդում ես։ — Are you reading the **book**?\
> Դու գիրքը **կառդու՞մ** ես։ — Are you **reading** the book?

The same could be said about other chars from the list.

To the date, existing rule, i.e. `IGNORE` list, works fine to me, but I am ready to listen your opinion.

**P.S.** Don't forget that I am not an inventor of the `IGNORE` rule, it existed long before and is used for some languages (e.g. Arabic Language).

**Comment by pidugusundeep** [comment]
Thanks for the explanation @nikita-moor. I would like to understand how can certain words be neglected with the `IGNORE` as you were doing with the characters.

**Comment by nikita-moor** [comment]
@pidugusundeep 
I don't think it's possible to `IGNORE` words, because it works only with singular characters.
