### ISSUE TITLE
Win 10 build fails in C:\Program Files

### ISSUE THREAD

**Issue by willbush** [hunspell/hunspell#572]
The issues can be of three types (put an X between the brackets):

- [X] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

| key                               | value  |
|-----------------------------------|--------|
| OS, distro, version             = | Win 10 |
| Hunspell version                = | 1.6.2  |

This might be a bug or might simply be easier to update the README's Windows
build steps.

I found that the build using Msys2 in Windows 10 will not work if done from a
directory that needs Administrator privileges despite running
`C:\msys64\msys2_shell.cmd` as Administrator. For example, if I extract the
zipped source to `C:\Program Files\hunspell-1.6.2`, then I will get build
errors.

Here are one of the build errors:

```
./.libs/lt-bulkcheck.c:163:73: error: stray '\' in program
 const char * LIB_PATH_VALUE   = ""C:\\Program Files\\hunspell-1.6.2\\src\\hunspell\\.libs";";
                                                                         ^
```

However, if I simply drop the `hunspell-1.6.2` source on my Desktop and perform
the same build steps, then it works.

It didn't occur to me until after I got it building and did `which hunspell` that there was no point 
to putting it in `C:\Program Files` to begin with.
 
## Steps to reproduce

1. Install https://www.msys2.org/ and follow installation steps.

2. Copy source obtained from latest
   [release](https://github.com/hunspell/hunspell/releases) to `C:\Program
   Files\`

3. Run Msys64 as Administrator. 
The shortcut I run as Administrator resolves to `C:\msys64\msys2_shell.cmd`

4. Install `pacman -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-boost`

5. Cd into `C:\Program Files\hunspell-1.6.2` and build. 

```bash 
autoreconf -vfi
./configure
make
```

Make should fail with build errors.

**Comment by PanderMusubi** [comment]
@willbush Thanks you for reporting this issue. One of the other maintainers with Windows experience will hopefully replicate this and add it to the README.

A related question for you is the following. We are currently developing the successor of Hunspell named Nuspell. We are working mainly on Linux at the moment but it should also build on other platforms such as Windows. In order to have a wide support, we try to get experienced users of all platforms on board. Recently we got some help from the FreeBSD community. Could you please help Nuspell by trying to build https://github.com/hunspell/nuspell on Windows and report back on what needs to be improved for supporting that platform?

**Comment by willbush** [comment]
I pulled latest from master for nuspell, followed the build steps, and got the following error:

```bash
make[3]: Entering directory '/c/Users/will/Desktop/nuspell/nuspell/src/tools'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/hunspell -I../../src/hunspell -I../                                                                                                                                                                                                                                                                                           ../src/parsers  -I/mingw64/include -std=c++14  -g -O2 -MT hunspell.o -MD -MP -MF                                                                                                                                                                                                                                                                                            .deps/hunspell.Tpo -c -o hunspell.o hunspell.cxx
hunspell.cxx: In function 'char* mymkdtemp(char*)':
hunspell.cxx:649:10: error: 'mkdtemp' was not declared in this scope
   return mkdtemp(templ);
          ^~~~~~~
hunspell.cxx:649:10: note: suggested alternative: 'mktemp'
   return mkdtemp(templ);
          ^~~~~~~
          mktemp
make[3]: *** [Makefile:476: hunspell.o] Error 1
make[3]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src/tools'
make[2]: *** [Makefile:386: all-recursive] Error 1
make[2]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell/src'
make[1]: *** [Makefile:491: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/will/Desktop/nuspell/nuspell'
make: *** [Makefile:400: all] Error 2
```

Do you want me to open a separate issue for this?

**Comment by PanderMusubi** [comment]
@willbush thanks. Yes, please at https://github.com/hunspell/nuspell/issues

This is code that will not make it into the final release. It is part of Hunspell and we use it for regression testing. If you can, could you also make a PR with a fix? Probably a macro `__MINGW32__` and/or `__MINGW32__` needs to be added.

    char* mymkdtemp(char *templ) {
    #ifdef WIN32
      char *odftmpdir = tmpnam(NULL);
      if (!odftmpdir) {
        return NULL;
      }
      if (system((std::string("mkdir ") + odftmpdir).c_str()) != 0) {
        return NULL;
      }
      return odftmpdir;
    #else
      return mkdtemp(templ);
    #endif
    }

**Comment by willbush** [comment]
Here is the issue: https://github.com/hunspell/nuspell/issues/19

**Comment by willbush** [comment]
Looking through me outstanding open issues, I think I can close this because it was opened elsewhere.
