### ISSUE TITLE
Parameters for COMPOUNDWORDMAX

### ISSUE THREAD

**Issue by PanderMusubi** [hunspell/hunspell#576]
@laszlonemeth, is the line:

    COMPOUNDWORDMAX 2 y

and error in package hunspell-hu version 1:a6.0.3-3 in file `/usr/share/hunspell/hu_HU.aff`? `COMPOUNDWORDMAX` only takes one parameter, so is the `y` an error/typo or was it intended for future usage (that allows a second parameter)?

**Comment by laszlonemeth** [comment]
It is only for back-compatibility.
