### ISSUE TITLE
can't use 'pt'

### ISSUE THREAD

**Issue by esthercamilo** [hunspell/hunspell#577]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [ ] Change request or feature request
- [x] Others, questions

# Other issues

I wrote the following lines:

`import spacy
from spacy_hunspell import spaCyHunSpell

nlp = spacy.load('pt')
hunspell = spaCyHunSpell(nlp, 'linux')

nlp.add_pipe(hunspell)
doc = nlp('feninino')
haz = doc[0]
print(haz._.hunspell_spell)
print(haz._.hunspell_suggest)`

I have all libraries above working. I have installed pt 
`python -m spacy download pt`

But, when I execute the script it is checking in English, and I get the following lines:

`/usr/bin/python3.6 /home/netshoes/PycharmProjects/migracao-sas/modelo_NICHO2/main.py
/usr/share/hunspell/en_US.dic /usr/share/hunspell/en_US.aff
False
['feminine', 'femininity', 'Beniamino', 'Fenian', 'Fernandina', 'Fernando']

Process finished with exit code 0`

As you see, it is not checking in PT.

**Comment by deronnax** [comment]
looks like a bug in Spacy, not Hunspell

**Comment by laszlonemeth** [comment]
It seems, Spacy can use the system-installed or the selected Hunspell dictionary files: 

https://pypi.org/project/spacy_hunspell/

Please, check the installation of the pt dictionary, for example, on Ubuntu Linux:

sudo apt-get install hunspell-pt-pt or hunspell-pt-br

or download the .aff and .dic dictionary files from

https://github.com/LibreOffice/dictionaries
