### ISSUE TITLE
Issue with hunspell install

### ISSUE THREAD

**Issue by willstout** [hunspell/hunspell#582]
The issues can be of three types (put an X between the brackets):

- [ ] Bug reports
- [ ] Change request or feature request
- [X ] Others, questions

# Other issues
I'm having issue with the installation process. I'm following these steps:

Download Msys2, update everything and install the following packages:
pacman -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool \
          mingw-w64-x86_64-boost
Open Mingw-w64 Win64 prompt and compile the same way as on Linux, see above.

I'm on the last part with compiling and I'm confused as to what I'm supposed to be doing. I think I'm supposed to be doing the following commands 

autoreconf -vfi
./configure
make
sudo make install
sudo ldconfig

But when I enter "autoreconf -vfi" I get the error 

"autoreconf: 'configure.ac' or 'configure.in' is required"

Where am I going wrong?

**Comment by stevencollinscn** [comment]
Have the same issue on Windows. I'm so confused how to do it.
![snap2](https://user-images.githubusercontent.com/33796896/42719826-4ec03448-86ea-11e8-8afa-f67704e603fc.jpg)

**Comment by janissl** [comment]
@stevencollinscn At least, there is no sudo command on msys64 (or msys2). You are already acting as a root user. Therefore, you do not need to add sudo to execute make install.

Concerning 'apt install' - msys64 is not a Linux. Any update or upgrade must be executed through the msys64 consoles using pacman. Refer to https://github.com/msys2/msys2 for a detailed information.

**Comment by sinistersnare** [comment]
When I installed this: I did the following commands: 

```bash
$ pacman -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool \
          mingw-w64-x86_64-boost
$ pacman -S gcc # this one is the thing i added that seemed to make it work
$ autoreconf -vfi
$ ./configure
$ make
$ make install
```

Then the `hunspell.exe` executable was located in `H:\Programs\MSYS2\usr\bin` (i installed MSYS2 into `H:\Programs\MSYS2` so that bit may differ for you).

Hope that helps.

**Comment by willstout** [comment]
When i put in verbatim

```
$ pacman -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool \
          mingw-w64-x86_64-boost
$ pacman -S gcc # this one is the thing i added that seemed to make it work
$ autoreconf -vfi
```

 I still get 

```
$ autoreconf -vfi
autoreconf: 'configure.ac' or 'configure.in' is required
```

I'm not sure if there is something really basic that I'm skipping over, I don't think so.

**Comment by sinistersnare** [comment]
Are you running `autoreconf -vfi` in the hunspell base directory? That is where `configure.ac` is, and `autoreconf` should see it there.

**Comment by willstout** [comment]
Oh yeah I'm not, where is that under?

**Comment by sinistersnare** [comment]
```bash
$ git clone HUNSPELL_REPO
$ cd hunspell
$ commands_from_above_including_the_autoreconf_call
```

Just in the base directory of the repo (where the `.git/` and the `src/` folders are).

**Comment by willstout** [comment]
Ah yes, I've got it now! Thanks!
