### ISSUE TITLE
memory overflow with emoji with JAVA JNA

### ISSUE THREAD

**Issue by lyahim** [hunspell/hunspell#583]
The issues can be of three types (put an X between the brackets):

- [X] Bug reports
- [ ] Change request or feature request
- [ ] Others, questions

# Reporting bugs

When reporting a bug you must tell us the state of your system and the
steps to reproduce the bug. For the state please specify the following:

| key                               | value |
|-----------------------------------|-------|
| OS, distro, version             = |   Debian 8 jessie    |
| Hunspell version                = |   1.3.2, 1.6.2    |
| Dictionary,package name,version = |   http://magyarispell.sourceforge.net/  v1.6.1    |
| Command line tool or GUI app    = |   JAVA JNA https://github.com/dren-dk/HunspellJNA    |

## Steps to reproduce
We use this tool to correct text from chat platforms, like facebook, and some times users send us emoji-s what we try to filter out with https://github.com/vdurmont/emoji-java tool and regex, but some of unfilterable at now, like https://emojipedia.org/bearded-person/, therefore the system send to hunspell, what we use through JNA(https://github.com/dren-dk/HunspellJNA). When Hunspell try to analize the emoji, we got the following JAVA crash

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f78034b9fc8, pid=26430, tid=0x00007f77de110700

JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libhunspell-linux-x86-64.so+0x27fc8]  SuggestMgr::leftcommonsubstring(char*, char const*)+0x108

## Bugged behavior (output)
crash the system

## Expected behavior (output)

# Change/feature request

If you want current behavior to get changed, please explain how do you
want it changed. If it's completely new, please explain it how do you
want it, as verbose as possible.

# Other issues

Do you can offer some workaround, how we need to observe any signal what need to avoid, because at now the whole application down when the user send an emoji.

Thank you,
Mihaly

**Comment by caolanm** [comment]
I don't see any crash with an hunspell 1.7.0 and

echo 🧔‍♂️| hunspell -d hu_HU

but its hard to know if this actually got fixed or if I just can't reproduce it. I'll assume its fixed, but if there is a reproducer via the command line and some specific .aff/.dic combo that can be provided then feel free to reopen.
