### ISSUE TITLE
Is there a way to run Hunspell and not have it ask you to accept/replace/etc words?

### ISSUE THREAD

**Issue by willstout** [hunspell/hunspell#586]
- [ ] Bug reports
- [ ] Change request or feature request
- [X ] Others, questions

# Other issues

I have a large database of text files I need to run through a spell checker. There is no way to go through **millions** of text files and accept or replace all the misspelled words. Is there a way to disable interactive mode?

**Comment by pkolbus** [comment]
Yes, several. The `-l` option lists the mis-spelled words; `-L` will list lines with mis-spellings. With `-a`, hunspell runs in a mode more suitable for use through a pipe.

The man page has a lot more detail.

**Comment by laszlonemeth** [comment]
Also you can list only the correct words, using -G 

Manual pages: https://github.com/hunspell/hunspell/tree/master/docs

or see hunspell -h

By the way, you can list bad/good words of office documents, too:

hunspell -l something.odt

or from MSO documents, too, converting them to ODF by libreoffice:

libreoffice --headless --convert-to odt *.docx
hunspell -l *.odt

Thanks for your question and comment!
