### ISSUE TITLE
Malay Language (Malaysia) Dictionary

### ISSUE THREAD

**Issue by SyafiqHadzir** [hunspell/hunspell#592]
How can I contribute with Malay language dictionary? There's a great absence of common vocabulary, and there are even orthographic faults passed as correct spellings. I have found this repo, but seems abandoned more than 5 years ago: https://github.com/gooselinux/hunspell-ms
Is there any active repository, or whatever, I could join?

**Comment by caolanm** [comment]
hunspell itself doesn't provide dictionaries, just the engine to do the spell checking
