### ISSUE TITLE
Debugging Source / Contributing

### ISSUE THREAD

**Issue by PamilerinId** [hunspell/hunspell#622]
Hello everyone and good day,

I have been trying to locate the morphological analysis routines in core hunspell, so i can test out a theory. I couldnt locate it from the readme or any of the manuals, so after setting it up(following the readme).I tried to step through debug on vs code, however when i run this to get an executable file of main script;

`gcc hunspell.cxx -g
`
it returns a lot of "unreferenced" errors with exit code:

`collect2: error: ld returned 1 exit status`

Am i going about this correctly?

thank you

**Comment by creiterer** [comment]
To compile hunspell you need to follow the "Compiling on ..." (e.g. [Compiling on GNU/Linux and Unixes](https://github.com/hunspell/hunspell#compiling-on-gnulinux-and-unixes)) instructions from the README.

**Comment by PamilerinId** [comment]
Thank you for responding.
I've followed the readme to the letter and all works fine.
I want to step through debug now.
