### ISSUE TITLE
1.7 huge performance hit

### ISSUE THREAD

**Issue by Carmina16** [hunspell/hunspell#630]
The version 1.3.1, under Windows, performed `hunspell -d xx -l` command on a 2MB text file in 650ms.

The version 1.7.0, under Linux, performs the same command in 12s.

Both the dictionary and the file are UTF-8 encoded.

As a side note, compiling 1.7 with `--enable-warnings` increases the operation time to 2 minutes.

**Comment by zdenop** [comment]
Testing case (3,0M txt file from Project Gutenberg):
`$ wget http://www.gutenberg.org/files/58030/58030-0.txt`

```
$ time hunspell-1.3.1/src/tools/hunspell -d en_GB -l 58030-0.txt >131.log

real    0m5,860s
user    0m5,772s
sys     0m0,088s
```

```
$ time hunspell-1.7.0/src/tools/hunspell -d en_GB -l 58030-0.txt >170.log

real    0m53,005s
user    0m52,396s
sys     0m0,555s
```

Test was run on Raspberry Pi 3 Model B with "Raspbian GNU/Linux 10 (buster)".
Both versions were compiled with `./configure --enable-static && make`

**Comment by zdenop** [comment]
Here are results of some version (1.3.4 is the first github version): 

| Version| real     |
| ------ | -------- |
| 1.3.1  | 0m5,860s |
| 1.3.4  | 0m7,990s |
| 1.4.2  | 0m50,173s |
| 1.5.4  | 0m49,684s |
| 1.6.2  | 0m51,353s |
| 1.7.0  | 0m53,005s |

This indicate major speed drop in 1.3.4 -> 1.4.2, but it seems that each new version is slower that previous one (excluding 1.5.4)

**Comment by caolanm** [comment]
the reproducer gives me better times in trunk now than in hunspell-1.3.4 so I'll claim its fixed, though variable on dictionary and input
