### ISSUE TITLE
Missing check for malloc() failure

### ISSUE THREAD

**Issue by jfkthame** [hunspell/hunspell#640]
Normally, hunspell code checks for allocation failure in malloc() and bails out, but I noticed this instance where it calls malloc() to allocate a string and then immediately strcpy's a value into it with no null-check:

https://github.com/hunspell/hunspell/blob/4eafbec55fa0b4b92db5216bfaa4a421dad998a2/src/hunspell/suggestmgr.cxx#L799-L800

In the (admittedly unlikely) event that malloc() returns null here, that would be bad.

**Comment by jfkthame** [comment]
Hmm, there are also some unchecked uses of `mystrdup` in AffixMgr::expand_rootword which look suspicious, although I haven't analysed exactly what happens if entries where `wlst[nh].word` is NULL are allowed to get into the list:

https://github.com/hunspell/hunspell/blob/4eafbec55fa0b4b92db5216bfaa4a421dad998a2/src/hunspell/affixmgr.cxx#L3391

https://github.com/hunspell/hunspell/blob/4eafbec55fa0b4b92db5216bfaa4a421dad998a2/src/hunspell/affixmgr.cxx#L3434

https://github.com/hunspell/hunspell/blob/4eafbec55fa0b4b92db5216bfaa4a421dad998a2/src/hunspell/affixmgr.cxx#L3466

Other nearby instances check for failure and bail out, so I suspect these ones should too.

**Comment by caolanm** [comment]
in trunk internal hunspell mystrdup now uses new[] so null checking is redundant
