### ISSUE TITLE
Memory Leak by HunspellPlugin

### ISSUE THREAD

**Issue by shchhabr** [hunspell/hunspell#644]
In a simple workflow of Search/Find & Edit in Acrobat DC, **5.72MB** is being leaked by AdobeHunspellPlugin.dll alone (Hunspell version used 1.6).

File attached for reference:
![MemoryLeak_Lilo](https://user-images.githubusercontent.com/54983518/64437273-a7083f80-d0e3-11e9-9042-084a54319bc9.jpeg)

**Comment by zdenop** [comment]
IMO you are complaining on wrong place - you should go to creator AdobeHunspellPlugin and raise issue there.
Or to replicate problem with tools provided by hunspell project.
