### ISSUE TITLE
`add_dic` documentation

### ISSUE THREAD

**Issue by Wulf** [hunspell/hunspell#651]
What's the return value of `add_dic` supposed to represent?

I was assuming the returned `int` represented success `true (1)` or failure `false (0)`, but it seems to return `false(0)` on success.

https://github.com/hunspell/hunspell/blob/30bd4bdbe776e5356d5394d277d1df489a6f53f1/src/hunspell/hunspell.cxx#L218-L224

Is this a mistake? If not, can we make it clear in the documentation?

All the best and thanks for your time :)

**Comment by zhbanito** [comment]
By convention, programms should return return zero when execution succeeds and non-zero when execution fails (at the same time this value is number of error)

**Comment by Wulf** [comment]
Thanks @zhbanito, that make sense. How can I apply that logic to the `spell` function though?

https://github.com/hunspell/hunspell/blob/master/src/hunspell/hunspell.cxx#L1937-L1948

The signature returns an `int`:
```
int HunspellImpl::spell(const char* word, int* info, char** root)
```

But the return values indicate `true (1)` or `false (0)` for whether the spelling is correct or not.

**Comment by zhbanito** [comment]
That's normal :)
Programmers are constantly trying to kill themselves with a shot in the leg.

**Comment by Wulf** [comment]
Hahahahahhahahahahahaha
