### ISSUE TITLE
Win32: `listdicpath()` not run

### ISSUE THREAD

**Issue by michaelmhoffman** [hunspell/hunspell#669]
[`hunspell.cxx`](https://github.com/hunspell/hunspell/blob/d6a5ae5986c0f0d6e280aa177c017b0cb0fc7fda/src/tools/hunspell.cxx#L1737)'s `search()` includes the following:

```
#if !defined(WIN32) || defined(__MINGW32__)
      listdicpath(begin, end - begin);
#endif

```

This means that when `hunspell -D` is run on the Win32 version, the available dictionaries are never printed. This means that spell-checking won't work with Windows Emacs and it will report errors like `ispell-phaf: No matching entry for en_US in ‘ispell-hunspell-dict-paths-alist’`.

**Comment by zdenop** [comment]
PR https://github.com/hunspell/hunspell/pull/672 should fix it

**Comment by zdenop** [comment]
duplicate to #661
