### ISSUE TITLE
Any plan for finnish dictonaries?

### ISSUE THREAD

**Issue by pjalsGit** [hunspell/hunspell#675]

**Comment by drahnr** [comment]
While this might not solve your problem, https://lib.rs/crates/voikko-rs or the C/C++ equiv https://github.com/voikko/corevoikko might be of interest to you

**Comment by devomaa** [comment]
Thanks, but the program I'm using requires Hunspell, and I need a Finnish dictionary of  that, hope you understand!

**Comment by zdenop** [comment]
Dictionaries are created by local people/community.
You can not expect that developers of library will create dictionary (data) for you.

Few second of googling and I find it https://github.com/fluks/fi-FI-mozilla-spellchecker

Or you can transform [Finish aspell dictionary](https://ftp.gnu.org/gnu/aspell/dict/fi/aspell6-fi-0.7-0.tar.bz2) to hunspell dictionary (at least I created Slovak hunspell dictionary several years ago that way).
