### ISSUE TITLE
🐞: Is not the word "analytics" in the dictionary?

### ISSUE THREAD

**Issue by joe733** [hunspell/hunspell#679]
## Steps to reproduce
1. Type the word analytics.
2. It is underlined in red.

## Expected behaviour
I think Analytics is pretty much an [English word](https://duckduckgo.com/?q=is+analytics+a+word&t=canonical&atb=v203-1&ia=definition). 

## Actual behaviour
Analytics is underlined in red.

## Configuration
**Operating system:**
elementary OS 5.1.4 Hera

<details><summary><b>Screenshot</b>:</summary>

![photo_2020-06-05_16-08-31](https://user-images.githubusercontent.com/38415384/83867880-bdf9c200-a747-11ea-9073-c0654a572d03.jpg)

Even the Firefox is showing it wrong when posting this issue. 
![image](https://user-images.githubusercontent.com/38415384/83904264-2e6f0600-a77d-11ea-9b45-91e82fcf9e0b.png)

Language & Region Configuration:
![image](https://user-images.githubusercontent.com/38415384/83904431-768e2880-a77d-11ea-8c55-0017bca8f22a.png)

</details>

**Comment by zdenop** [comment]
This is library project, so you are posting issue on wrong place.
You should complain to dictionary author/packager/yourself for providing/installing  wrong/outdated/... dictionary.
I use brave/firefox has no problem with word "analytics"

**Comment by joe733** [comment]
> This is library project, so you are posting issue on wrong place.
You should complain to dictionary author/packager/yourself for providing/installing wrong/outdated/... dictionary.

Sorry, can you please provide a link (or a pointer) to where I should file the issue.

I'm using [elementaryOS](https://elementary.io) which probably ships with hunspell dictionaries. May I also know how to find out the `author / package` of as well as the installed dictionary on Linux any commands / scripts etc?

**Comment by zdenop** [comment]
You should contact support of your system.

**Comment by joe733** [comment]
Okay thanks closing.
