### ISSUE TITLE
Building on Apple Silicon (ARM) Mac

### ISSUE THREAD

**Issue by nbrachfogel** [hunspell/hunspell#681]
There's currently no way to build on the new Apple Silicon (ARM) Mac.

**Comment by zdenop** [comment]
What is exact problem? Hunspell works fine on ARM (e.g. raspbery pi )

**Comment by nbrachfogel** [comment]
Sorry, not exactly a "problem", I just wanted to request a target to build on the new Apple machines.

**Comment by zdenop** [comment]
Build target is setup by your configuration tools (e.g. autotools, cmake...). So what exactly should be solved?
What did you try?
Why you was not able to build hunspell for ARM?
If you are not able to describe your problem that there is not issue ;-)

**Comment by nbrachfogel** [comment]
Give me a bit of time, I'll see with my developer and come back to you with the information you request (and also try to get a better understanding of the situation).

Thank you for your kindness.

**Comment by nbrachfogel** [comment]
I've seen with my developer and it looks like we made a mistake. You're right, we are the one handling the target and as such the change must be done on our side.

Sorry for that and thanks again for your help.

**Comment by zdenop** [comment]
Please close the issue.

**Comment by nbrachfogel** [comment]
Done.
