### ISSUE TITLE
autoreconf -vfi i  windows and MacOs gives error configure.ac and .in is required

### ISSUE THREAD

**Issue by jwtiyar** [hunspell/hunspell#683]
Hey
I have installed mysys correctly and updated all, but in compiling when i enter autoreconf -vfi in mingw64 it gives an error:
`jwtiyar@DESKTOP-VQHOU3C MINGW64 ~
$ autoreconf -vfi
autoreconf: 'configure.ac' or 'configure.in' is required`

**Comment by zdenop** [comment]
as you can check [configure.ac is part of code](https://github.com/hunspell/hunspell).
