### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [hunspell/hunspell#689]
I think that it would be good to flush currently committed changes and make new release as it is already almost two years since last release :)

**Comment by nijikon** [comment]
Any plans for a new release?

**Comment by caolanm** [comment]
finally done with https://github.com/hunspell/hunspell/releases/tag/v1.7.1

**Comment by kloczek** [comment]
Thank you.
Just tested that new version buids correcrly 😄

**Comment by nijikon** [comment]
@caolanm thank you 💜

**Comment by kloczek** [comment]
As at the moment is +50 commits since last release (https://github.com/hunspell/hunspell/compare/v1.7.2...master) I think that it would be good again flush all those fixes as new minor release.
Doable? 😋
