### ISSUE TITLE
politically-charged spellcheck in libreoffice, suspect certain groups are gaming your engine 

### ISSUE THREAD

**Issue by tuggerfub** [hunspell/hunspell#697]
https://www.youtube.com/watch?v=diBuFOK6Uhg 

For some reason your spellcheck dictionary returns specific corrections for the word 'voting'; "shooting", "looting" and "rioting".

**Comment by phillipseamore** [comment]
Hunspell is a spell checking library and does not create or distribute any dictionaries.  If you have an issue with a specific dictionary you would need to find the repository for that dictionary.

**Comment by tuggerfub** [comment]
Would hunspell be able to evaluate which of its libraries produced this?
These are the dictionaries it references.


[image: includes.jpg]

**Comment by tuggerfub** [comment]
How would I be able to discern which dictionary this came from? This is
hunspell's spellcheck system making these selections from these
dictionaries.

**Comment by phillipseamore** [comment]
The video show LibreOffice, here are the dictionaries that they distribute: https://github.com/LibreOffice/dictionaries/
All the data and rules for spell checking comes from those dictionaries (dic, aff files).

**Comment by tuggerfub** [comment]
According to http://hunspell.github.io/, at the very top of the 'About' page: 

"**Hunspell is the spell checker of LibreOffice,** OpenOffice.org, Mozilla Firefox 3 & Thunderbird, Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign, memoQ, Opera and SDL Trados." 

I am not a spellcheck library analyst. If the word-selection process draws from dictionaries, are you saying that those dictionaries come with predefined substitutions that would discern 'voting' as a non-word and suggest '_shooting_'? 
This seems to defy the role of Hunspell to this layperson.

**Comment by phillipseamore** [comment]
Hunspell is simply a library that does spell checking based on dictionary and affix files.  It only parses the text, follows the rules of the dictionary and supplies the results. I've already pointed you in the right direction to find the possible source in the LibreOffice dictionaries.

**Comment by kevina** [comment]
If your locale is "en_US" I would be the author of the dictionary in question.  The spell checker correctly flagged "voting's" as incorrect as "voting" is not a noun and thus can not take a possessive form.  I can not do a single thing about the other suggestions except perhaps remove of the possessive forms of the word if they are incorrect (of which "rioting's" and "looting's" might be candidates).

**Comment by tuggerfub** [comment]
> 
> 
> If your locale is "en_US" I would be the author of the dictionary in question. The spell checker correctly flagged "voting's" as incorrect as "voting" is not a noun and thus can not take a possessive form. I can not do a single thing about the other suggestions except perhaps remove of the possessive forms of the word if they are incorrect (of which "rioting's" and "looting's" might be candidates).

It was the en_CA. This has been a rabbit hole but I think I found the dev responsible. 
The guy's website is practically dedicated to the neo nazi Alex Chiu.

**Comment by swan46** [comment]
What is your problem with the suggestions?
