### ISSUE TITLE
error in Delphi Interface

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#7]
The component synspellcheck is probably obsolete or is not compatible with new uniSynEdit...
Constantly gives out errors in an operating time Delphi7 IDE...

Original comment by: *anonymous

Original Ticket: "hunspell/bugs/68":https://sourceforge.net/p/hunspell/bugs/68

**Comment by dimztimz** [comment]
Closing, no comment for 8 years, probably issue was resolved.
