### ISSUE TITLE
reverse_condition in affixmgr.cxx may overwrite the null terminator of a std::string

### ISSUE THREAD

**Issue by rnk** [hunspell/hunspell#714]
Originally discovered in https://crbug.com/1175933 I've pasted the explanation of the bug in the context of Chrome below. I checked the upstream hunspell sources, and it seems like the same explanation applies to ToT hunspell:
https://github.com/hunspell/hunspell/blob/8a2fdfe5a6bb1cbafc04b0c8486abcefd17ad903/src/hunspell/affixmgr.cxx#L4363

I have a "fix" for the bug, but I'm not sure that it's behavior preserving. My question is, what should the behavior of reverse_condition be when the input ends in the `^` character?

-------------

The UMR comes from this code:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/hunspell/src/hunspell/affixmgr.cxx;drc=ba36291731404cfa22b167b3b9b318e1f4bb148f;l=4763
```
        // piece 5 - is the conditions descriptions
        case 4: {
          std::string chunk(start_piece, iter);
          np++;
```

Note the use of the string(iter, iter) constructor. In this case, the constructed string contains the UTF-8 string "^весь". This is less than 23 bytes long, so it uses the short libc++ string representation. Before the libc++ roll, the entire short string was zero initialized. After the roll, only the bytes of the string and the null terminator are initialized. The string starts out null terminated, and something breaks it later to allow C string functions to read uninitialized memory.

Later, this does this:
```
  reverseword(chunk);
  reverse_condition(chunk):
```

reverseword works fine and does the obvious reversal. reverse_condition is defined here:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/hunspell/src/hunspell/affixmgr.cxx;drc=ba36291731404cfa22b167b3b9b318e1f4bb148f;l=4448
```
void AffixMgr::reverse_condition(std::string& piece) {
...
  for (std::string::reverse_iterator k = piece.rbegin(); k != piece.rend(); ++k) {
    switch (*k) {
...
      case '^': {
        if (*(k - 1) == ']')
          neg = 1;
        else
          *(k - 1) = *k;
        break;
      }
...
    }
  }
}
```

The original string starts with ^, which is now at the end position, and the write to '*(k - 1)' is an OOB write to the null terminator. Later on, the string is used as a C string, and the MSan report is triggered while searching for a null terminator in encodeit:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/hunspell/src/hunspell/affixmgr.cxx;l=1113;drc=ba36291731404cfa22b167b3b9b318e1f4bb148f

This hacky patch fixes the UMR by putting back the null terminator:

```
@@ -4479,6 +4482,8 @@ void AffixMgr::reverse_condition(std::string& piece) {
       }
     }
   }
+
+  const_cast<char*>(piece.data())[piece.size()] = '\0';
 }
```

**Comment by nico** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1175933#c8 for a fix suggestion that might be better.

**Comment by nico** [comment]
> See https://bugs.chromium.org/p/chromium/issues/detail?id=1175933#c8 for a fix suggestion that might be better.

We went with that change in chromium's downstream version, see https://chromium.googlesource.com/chromium/src/+/05a80c4f3d18994cb411ae01b97bc97b327272e7%5E%21/#F3

Please consider merging this change upstream.
