### ISSUE TITLE
hunspell-pl don't work

### ISSUE THREAD

**Issue by maciejosuch** [hunspell/hunspell#720]
Hi,

I have problem with **hunspell-pl**, this package don't work with **Collabora Online** in **NextCloud**. Collabora don't read polish language in dictionary.
![1](https://user-images.githubusercontent.com/71645626/114164464-9d803280-992b-11eb-8d78-f6b34631d113.png)
I can install -en-us, -en-gb or -es and they work without any configuration.
![Screenshot from 2021-04-09 12-03-14](https://user-images.githubusercontent.com/71645626/114164498-a96bf480-992b-11eb-8160-29be5146d02b.png)

I noticed that the dictionary packages in the -pl package are old but uploading the latest packages from the same source doesn't help.

Has anyone had a similar problem with the Polish dictionary? Or any other?

Thanks for your help, best regards.

**Comment by caolanm** [comment]
hunspell doesn't include any dictionaries, just the code to apply the rules described by a dictionary to implement the spellcheck, The above sounds like an issue with a specific dictionary, or general system config like where/how is collabora online is configured to search for system spellchecking dictionaries
