### ISSUE TITLE
Hunspell suggests profanity words

### ISSUE THREAD

**Issue by zalex-wrike** [hunspell/hunspell#726]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/85687801/121532944-1a00c180-ca00-11eb-85c8-ce08073a6935.png">

Hey guys, we've been using Electron for our Desktop app. Electron has built-in support for Chromium’s spellchecker since Electron 8. On Windows and Linux this is powered by Hunspell dictionaries. One of our clients reported the spellchecker suggests profanity for the word 'untucking'. 

Please help us make the spellchecking more user-friendly and add untucking word into dictionary by default :) thanks!

**Comment by phuzi** [comment]
@zalex-wrike I don't believe that the project actually includes any dictionaries!

**Comment by lajo-gh** [comment]
Hunspell already allows marking words that should not be suggested. From the "hunspell5" part of the manual:

> NOSUGGEST flag
> Words signed with NOSUGGEST flag are not suggested (but still accepted when typed correctly).
> Proposed flag for vulgar and obscene words (see also SUBSTANDARD).

(the SUBSTANDARD flag is for different, "less-official", spellings of the word, allomorphs, i.e. not what is needed here.)

Thus, Hunspell already has the option, but it need to be used in the dictionary. The test files coming with the Hunspell distribution contains examples, look for the test files with "nosuggest" in their name.

**Comment by caolanm** [comment]
yeah, this is up to the dictionary itself, not the software which does provide a mechanism to accept a word as spelled correctly without suggesting that word as a replacement for a misspelling
