### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by tmccombs** [hunspell/hunspell#727]
It seems that even even constructing a new `Hunspell` isn't thread safe, because of the use of global state for the utf_tbl in csutil.cxx.

The only solutions I've found for working around that are to use a single global lock for all calls to hunspell, which is unacceptable for my use case, or modify hunspell to have at least some level of locking (see https://github.com/lucidsoftware/hunspell/commit/76e91c3f98ff6369c6c7ca880577a39cd55a08fd). 

Would adding some level of thread safety be acceptable for this project?

**Comment by tmccombs** [comment]
If there is interest, I would be happy to make a PR from our fork.

**Comment by aarondandy** [comment]
There are other variables that are used during check and suggest operations too such as `sfxappnd` which are shared: https://github.com/hunspell/hunspell/blob/31e6d6323026a3bef12c5912ce032d88bfef2091/src/hunspell/affixmgr.hxx#L146-L152 .
In my port I stack allocate space for those variables for each query to make things thread safe.

**Comment by caolanm** [comment]
sure, turn it into a PR
