### ISSUE TITLE
Adding new dictionary to hunspell

### ISSUE THREAD

**Issue by jwtiyar** [hunspell/hunspell#735]
Hey
I don't know if it's a right place or not, But As you know hunspell does not support central kurdish(ckb), How we can add it? Any documentation?

**Comment by ErikAnderson3** [comment]
Check the man pages.  These are available online in various places.

You'll need to create two files -- one `*.aff` file that defines the options (rules for affixes, replacements, any characters to ignore, that kind of thing), and one `*.dic` file that lists the words to treat as "correct", along with any flags to indicate which rules in the `*.aff` file should apply to each word.

It is theoretically possible to create Hunspell spellcheck lists for anything and call it a "language".  We've experimented with creating spellcheck files for API identifiers, so things like `class::name::CamelCaseFunction(with, parameter)` can be usefully spellchecked, even with the punctuation characters and case-sensitivity.  So we have the standard `en_US` spellcheck working in combination with our custom `SDK-API` spellcheck.

Best of luck!

**Comment by caolanm** [comment]
looks like this is well in train by now: https://github.com/sinaahmadi/KurdishHunspell
