### ISSUE TITLE
Misspelling not flagged for es-ES

### ISSUE THREAD

**Issue by msoutopico** [hunspell/hunspell#736]
# Steps to reproduce

1. Select Spanish (Spain) as the language of the document in LibreOffice Writer or any other application that relies on Hunspell for spellchecking.
2. Write the sentence: `Los vecinos elijen al alcalde.`

# Expected results

The word "elijen" is flagged as mispelled and the correct spelling "eligen" is proposed on right click.

# Actual results

No misspellings are flagged.

**Comment by msoutopico** [comment]
For reference: https://www.rae.es/dpd/elegir

**Comment by caolanm** [comment]
hunspell doesn't include any dictionaries, just the code to apply the dictionary rules to do the spellchecking. The above, on the face of things, sounds like an issue with that specific dictionary.
