### ISSUE TITLE
Test issue with "allcaps.aff" file

### ISSUE THREAD

**Issue by aarondandy** [hunspell/hunspell#760]
While catching up my port to hunspell, I noticed some test failures with the recent changes to allcaps.aff . I'm a bit rusty so I could be misremembering, but I also can't get a test environment running and the CI seems to be offline. I think the last line in the file has both an incorrect command name, which should be PFX instead of PFS, but is also missing part of the command. I think it should be the following:
```
PFX L   0     L'      .
```

Change: https://github.com/hunspell/hunspell/pull/710/files#diff-9f63eadb804dc589c468b458cdea7891e03ce80420860f4946e21d9df9187f9dR8

**Comment by caolanm** [comment]
done now
