### ISSUE TITLE
 No such file or directory at /usr/share/autoconf2.7/Autom4te/FileUtils.pm line 293

### ISSUE THREAD

**Issue by NeoFahrenheit** [hunspell/hunspell#782]
Hi, I downloaded Cygwin and downloaded all the recommended tools, but when I try to compile, I have this errors:
```
$ autoreconf -vfi
autoreconf-2.71: export WARNINGS=
autoreconf-2.71: Entering directory '.'
autoreconf-2.71: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf2.7/Autom4te/FileUtils.pm line 293.
autoreconf-2.71: error: autopoint failed with exit status: 1
```

I'm on Windows 11. I don't understand much of this stuff.
Thank you!

**Comment by zdenop** [comment]
This is not a hunspell problem (but an autopoint problem - it seems you do not have all the dependencies you need installed). Use tools you are familiar with.

**Comment by NeoFahrenheit** [comment]
Well, I don't know how to solve this. I have installed all the tool the README page suggests.

**Comment by NeoFahrenheit** [comment]
I finally found a way to compile with Visual Studio 2022. It gave me a lot of work!
Thanks
