### ISSUE TITLE
FLAG UTF-8 on arm devices

### ISSUE THREAD

**Issue by zdenop** [hunspell/hunspell#896]
According the [man page](https://github.com/hunspell/hunspell/blob/master/man/hunspell.5#L126) `FLAG UTF-8` is broken on arm devices. Is still true or man page is not updated?

**Comment by caolanm** [comment]
It has claimed that since the initial git checkin in 2010. But there were a bunch of fixes since then, and no one has an explicit arm bug open so I suspect its an out of date claim
