### ISSUE TITLE
Cannot add the word "Javascript" to custom dictionary with a capital J

### ISSUE THREAD

**Issue by staticf0x** [hunspell/hunspell#905]
hunspell always marks the word `Javascript` as incorrect even when added in a custom dictionary.

Minimal example:

**words.txt**:

```
Javascript
```

**text.txt**:

```
Javascript cannot be marked as correct.
```

Command: `hunspell -l -d en_US -p words.txt test.txt`

Output:

```
Javascript
```

However, if `words.txt` contains `javascript` with lowercase `j`, it's all good. This however **doesn't happen** for other words, for example when I add my username:

**words.txt**

```
Javascript
Staticfox
```

**text.txt**

```
Javascript cannot be marked as correct.
Staticfox on the other hand.
```

Output:

```
Javascript
```

Version: `International Ispell Version 3.2.06 (but really Hunspell 1.7.0)`
OS: Fedora 37
Packages:
```
hunspell.x86_64                                  1.7.0-21.fc37
hunspell-en-US.noarch                            0.20140811.1-23.fc37
```

**Comment by caolanm** [comment]
This is probably due to the presence of "JavaScript/M" in /usr/share/hunspell/en_US.dic
