### ISSUE TITLE
Unable to retrieve hunspell aarch64 repo package

### ISSUE THREAD

**Issue by nixyhustle** [hunspell/hunspell#907]
I am trying to install code:blocks which unfortunately is mandatory for my class. It is unable to install because the hunspell aarch64 tar.gz file is unable to be retireved with a 404 error. Has anyone also had this issue? How can I install hunspell properly? Thanks

**Comment by caolanm** [comment]
what link do you refer to?

**Comment by soosistvangithub** [comment]
> When I try to install hunspell through the AUR I get the following message:
> 
> :: Retrieving packages... hunspell-1.7.1-1-aarch64.pkg.tar.xz failed to download error: failed retrieving file 'hunspell-1.7.1-1-aarch64.pkg.tar.xz' from mirror.archlinuxarm.org : The requested URL returned error: 404 warning: failed to retrieve some files error: failed to commit transaction (failed to retrieve some files) Errors occurred, no packages were upgraded. -> error installing repo packages
> 
> Thank you for your time, appreciate you!

It is not the hunspell project mistake. 
The hunspell package missing from the repo of archlinuxarm.org. The 404 warning means that target of url  does not exist.

**Comment by nixyhustle** [comment]
Oh, my apologies. Rather new to all this and wasn't sure how it worked. Is there a way for me to get hunspell from you guys directly?

**Comment by caolanm** [comment]
No, not from here, this is just where the source code comes from, not the distro binaries.

**Comment by nixyhustle** [comment]
@caolanm Thank you for the response, and explanation. I'll also have you know the issue on the AUR was resolved and I was able to properly install the package. Thank you and the hunspell team for everything you do. Have a great day!
