### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [hunspell/hunspell#917]
Would you like to add more error handling for return values from functions like the following?
* [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [save_privdic](https://github.com/hunspell/hunspell/blob/de9fe28008eb0761c33bd83847f282602c599fda/src/tools/hunspell.cxx#L553)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [newitem](https://github.com/hunspell/hunspell/blob/60980f2bfe6678cca98bea2bf37f0b11bb34f4c5/src/tools/hzip.cxx#L104)
* [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [LLVMFuzzerInitialize](https://github.com/hunspell/hunspell/blob/8a2fdfe5a6bb1cbafc04b0c8486abcefd17ad903/src/tools/fuzzer.cxx#L44)

**Comment by caolanm** [comment]
The strdup is just in the fuzzer, not worth checking IMO. I doubt there's anything meaningful we could do on a fail return from close. Would be better to replace the malloc/free in newitem etc with new/delete though if you wanted to try that.

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by caolanm** [comment]
wrt static source code analysis we run coverity over this occasionally, haven't tried any others. wrt 2nd query, its rather non specific.

**Comment by elfring** [comment]
>…, haven't tried any others.

It is just safer to [handle more “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it? :thinking:


>wrt 2nd query, its rather non specific.

Can you become more aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns? :thinking:
