### ISSUE TITLE
License: what is it?

### ISSUE THREAD

**Issue by lucasgonze** [hunspell/hunspell#921]
The project contains a number of contradictory licenses, including GPL. Can you explain what the intended license is?

**Comment by caolanm** [comment]
You'll probably have to be more specific on what you see as contradictory

**Comment by lucasgonze** [comment]
I beg your pardon for writing such a poorly documented bug. I was reading a copy of the code where different files had different licenses in the headers. When I investigated further I found that this was permitted by the master tri-license statement.
