### ISSUE TITLE
RepList class define the "near" method

### ISSUE THREAD

**Issue by phajdan** [hunspell/hunspell#94]
RepList class has a method called "near".

In the MS Windows SDK WINDEF.H include file the "near" keyword has been undefined in a way similar to the following one:

...
\#ifdef near 
\#undef near
\#define near
\#endif
...

This cause that the RepList.hxx file \(included by affixmgr.hxx, include by hunspell.hxx included ny hunspelldll.h\) is included with a method called

...
int \(const char \* word\);
...

causing a compile error in programs using the libhunspell.dll v.1.2.8

Original comment by: *anonymous

Original Ticket: "hunspell/bugs/98":https://sourceforge.net/p/hunspell/bugs/98

**Comment by dimztimz** [comment]
Already fixed in 73b1cad1af7ab94252f75784fa6724cf062a6966
