### ISSUE TITLE
Function to search for duplicate words

### ISSUE THREAD

**Issue by discoleo** [hunspell/hunspell#951]
# Function to search for duplicate words

It would be practical to be able to search also for duplicate words: "some of the the words can be duplicated"!

The text is already tokenized: searching for adjacent duplicate words would be practical.

Note:
- the search term "duplicate" does not work well in Bugzilla and it was not practical to search for any existing issues on this topic;

**Comment by caolanm** [comment]
I suppose hunspell is really just for spell checking and a duplicate word issue is more a grammar checking issue. Duplicate words isn't necessarily an error anyway so needs another layer of messiness: https://english.stackexchange.com/questions/492349/is-my-use-of-that-that-in-this-sentence-gramaticaly-correct
