### ISSUE TITLE
Qt 6.5.2 hunspell license

### ISSUE THREAD

**Issue by rdubler** [hunspell/hunspell#969]
I looked at the sources of Qt 6.5.2, specifically hunspell (qtwebengine/src/3rdparty/chromium/third_party/hunspell inside the source tarball).

COPYING.LESSER shows:

                  GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

When I look at the official hunspell github repo it shows:

                  GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

So my question is:  Is hunspell now available via LGPL version 3?

**Comment by caolanm** [comment]
Qt is bundling chromium, and chromium is bundling hunspell., and the version of hunspell in chromium is 1.6.something

Historically hunspell includes a "Version 2.1" of the LGPL. But version 1.6 of hunspell was released with a COPYING.LESSER as you see above with the "Version 3" while this was changed back to the "Version 2.1" somewhere along the line for current releases.

Most of the source state:

'... the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL")'

 so they could be used under the LGPL version 3 if desired, but there are some subset of files which explicitly have:
'you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1'
so including "Version 2.1" of the LGPL is probably a more faithful presentation of the overall situation.
