### ISSUE TITLE
Solution files for win are too old.

### ISSUE THREAD

**Issue by kovacshviktor** [hunspell/hunspell#988]
Windows 7 is no longer supported. Visual Studio can not compile hunspell.

**Comment by kovacshviktor** [comment]
Sorry... The hunspell project files specify Windows XP as the target platform. This is an even older platform. You need to set at least Windows 10 as the target platform, maybe 8.1.

**Comment by caolanm** [comment]
you didn't mention what failed, its quite likely the c++ requirements have crept up quietly to leave the docs out of date?

**Comment by kovacshviktor** [comment]
> you didn't mention what failed, its quite likely the c++ requirements have crept up quietly to leave the docs out of date?

I tried  compile it with Visual Studio 2020 and 2017 (SDKs installed) This failed, Visual Studio told me that Windows XP was the target platform. I tried MSYS2. I don't know where it installed the compiled hunspell.
