### ISSUE TITLE
hunspell dictionary for python and c++

### ISSUE THREAD

**Issue by KirillGermanov** [hunspell/hunspell#994]
Hi, can someone help?
Do we have dictionaries/rules for checking python and c++ languages
i'm going to use hunspell in project instead of cspell and noticed that hunspell
(using en_US) does not understand camel case/snake case and other specific syntax

**Comment by caolanm** [comment]
That's more a question about dictionaries, hunspell itself doesn't provide any dictionaries, just parses them, so I'm unaware of any specific coding dicts.
